<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="IsValidImage" Id="{4f5abcd5-0122-0350-3fa7-716c6d734fe9}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidImage : BOOL
VAR_INPUT
    Image : ITcVnImage;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidImage := Image <> 0;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>