<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="IsValidContainer" Id="{28bdfab1-acc8-4d33-8d0a-eabac17c8d76}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION IsValidContainer : BOOL
VAR_INPUT
    Container : ITcVnContainer;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[IsValidContainer := Container <> 0;
]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>