<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.12">
  <POU Name="MAIN" Id="{a546692e-f77d-4dc9-b456-635ae84187da}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
    // enums
    _ETcVn2dCodeSearchStrategy_TestSuite : _ETcVn2dCodeSearchStrategy_TestSuite;
    _ETcVnAdaptiveThresholdMethod_TestSuite : _ETcVnAdaptiveThresholdMethod_TestSuite;
    _ETcVnBarcodeSearchDirection_TestSuite : _ETcVnBarcodeSearchDirection_TestSuite;
    _ETcVnBarcodeType_TestSuite : _ETcVnBarcodeType_TestSuite;
    _ETcVnBlobCombination_TestSuite : _ETcVnBlobCombination_TestSuite;
    _ETcVnBorderInterpolationMethod_TestSuite : _ETcVnBorderInterpolationMethod_TestSuite;
    //_ETcVnCalibrationPattern_TestSuite : _ETcVnCalibrationPattern_TestSuite;
    //_ETcVnCalibrationPatternOrigin_TestSuite : _ETcVnCalibrationPatternOrigin_TestSuite;
    //_ETcVnCameraState_TestSuite : _ETcVnCameraState_TestSuite;
    //_ETcVnClusteringAlgorithm_TestSuite : _ETcVnClusteringAlgorithm_TestSuite;
    //_ETcVnColorMap_TestSuite : _ETcVnColorMap_TestSuite;
    //_ETcVnColorMapSize_TestSuite : _ETcVnColorMapSize_TestSuite;
    _ETcVnColorSpaceTransform_TestSuite : _ETcVnColorSpaceTransform_TestSuite;
    //_ETcVnColorTrainingMethod_TestSuite : _ETcVnColorTrainingMethod_TestSuite;
    //_ETcVnConnectedComponentsAlgorithm_TestSuite : _ETcVnConnectedComponentsAlgorithm_TestSuite;
    //_ETcVnContainerExportFormat_TestSuite : _ETcVnContainerExportFormat_TestSuite;
    //_ETcVnContourApproximationMethod_TestSuite : _ETcVnContourApproximationMethod_TestSuite;
    //_ETcVnContourRetrievalMode_TestSuite : _ETcVnContourRetrievalMode_TestSuite;
    //_ETcVnContoursMatchComparisonMethod_TestSuite : _ETcVnContoursMatchComparisonMethod_TestSuite;
    //_ETcVnDiffusivityTypeKAZE_TestSuite : _ETcVnDiffusivityTypeKAZE_TestSuite;
    //_ETcVnDistanceTransformationLabel_TestSuite : _ETcVnDistanceTransformationLabel_TestSuite;
    //_ETcVnDistanceTransformationMask_TestSuite : _ETcVnDistanceTransformationMask_TestSuite;
    //_ETcVnDistanceType_TestSuite : _ETcVnDistanceType_TestSuite;
    //_ETcVnDrawMatchesFlags_TestSuite : _ETcVnDrawMatchesFlags_TestSuite;
    //_ETcVnDrawShape_TestSuite : _ETcVnDrawShape_TestSuite;
    //_ETcVnEdgeDetectionAlgorithm_TestSuite : _ETcVnEdgeDetectionAlgorithm_TestSuite;
    //_ETcVnEdgeDirection_TestSuite : _ETcVnEdgeDirection_TestSuite;
    //_ETcVnElementType_TestSuite : _ETcVnElementType_TestSuite;
    //_ETcVnEstimationAlgorithm_TestSuite : _ETcVnEstimationAlgorithm_TestSuite;
    //_ETcVnExtremePointDirection_TestSuite : _ETcVnExtremePointDirection_TestSuite;
    //_ETcVnFeatureDescriptorTypeAKAZE_TestSuite : _ETcVnFeatureDescriptorTypeAKAZE_TestSuite;
    //_ETcVnFeatureScalingType_TestSuite : _ETcVnFeatureScalingType_TestSuite;
    //_ETcVnFeatureScoreTypeORB_TestSuite : _ETcVnFeatureScoreTypeORB_TestSuite;
    //_ETcVnFilterDirection_TestSuite : _ETcVnFilterDirection_TestSuite;
    //_ETcVnFlipAxis_TestSuite : _ETcVnFlipAxis_TestSuite;
    //_ETcVnFontType_TestSuite : _ETcVnFontType_TestSuite;
    //_ETcVnHoughMethod_TestSuite : _ETcVnHoughMethod_TestSuite;
    //_ETcVnInitializableFunction_TestSuite : _ETcVnInitializableFunction_TestSuite;
    //_ETcVnInterpolationType_TestSuite : _ETcVnInterpolationType_TestSuite;
    //_ETcVnKeypointDetectionTypeAGAST_TestSuite : _ETcVnKeypointDetectionTypeAGAST_TestSuite;
    //_ETcVnKeypointDetectionTypeFAST_TestSuite : _ETcVnKeypointDetectionTypeFAST_TestSuite;
    //_ETcVnKnn_TestSuite : _ETcVnKnn_TestSuite;
    //_ETcVnLineType_TestSuite : _ETcVnLineType_TestSuite;
    //_ETcVnMorphologicalOperator_TestSuite : _ETcVnMorphologicalOperator_TestSuite;
    //_ETcVnNbc_TestSuite : _ETcVnNbc_TestSuite;
    //_ETcVnNormalizationType_TestSuite : _ETcVnNormalizationType_TestSuite;
    //_ETcVnOcrModelType_TestSuite : _ETcVnOcrModelType_TestSuite;
    //_ETcVnOcrOptions_TestSuite : _ETcVnOcrOptions_TestSuite;
    //_ETcVnOrientationMethod_TestSuite : _ETcVnOrientationMethod_TestSuite;
    //_ETcVnPaddingMode_TestSuite : _ETcVnPaddingMode_TestSuite;
    //_ETcVnPixelConnectivity_TestSuite : _ETcVnPixelConnectivity_TestSuite;
    //_ETcVnPixelEncoding_TestSuite : _ETcVnPixelEncoding_TestSuite;
    //_ETcVnPixelPackMode_TestSuite : _ETcVnPixelPackMode_TestSuite;
    //_ETcVnPrototypeClusterer_TestSuite : _ETcVnPrototypeClusterer_TestSuite;
    //_ETcVnRectangleIntersection_TestSuite : _ETcVnRectangleIntersection_TestSuite;
    //_ETcVnRotationAngle_TestSuite : _ETcVnRotationAngle_TestSuite;
    //_ETcVnRTrees_TestSuite : _ETcVnRTrees_TestSuite;
    //_ETcVnSignedNormalization_TestSuite : _ETcVnSignedNormalization_TestSuite;
    //_ETcVnSolvePnPMethod_TestSuite : _ETcVnSolvePnPMethod_TestSuite;
    //_ETcVnSta_TestSuite : _ETcVnSta_TestSuite;
    //_ETcVnStructuringElementShape_TestSuite : _ETcVnStructuringElementShape_TestSuite;
    //_ETcVnSvm_TestSuite : _ETcVnSvm_TestSuite;
    //_ETcVnSvmKernelType_TestSuite : _ETcVnSvmKernelType_TestSuite;
    //_ETcVnSvmSgdClassifierMarginType_TestSuite : _ETcVnSvmSgdClassifierMarginType_TestSuite;
    //_ETcVnSvmSgdClassifierType_TestSuite : _ETcVnSvmSgdClassifierType_TestSuite;
    //_ETcVnTemplateMatchMethod_TestSuite : _ETcVnTemplateMatchMethod_TestSuite;
    //_ETcVnThresholdType_TestSuite : _ETcVnThresholdType_TestSuite;
    //_ETcVnVectorCompareMethod_TestSuite : _ETcVnVectorCompareMethod_TestSuite;
    //_ETcVnWorldCoordinateSystem_TestSuite : _ETcVnWorldCoordinateSystem_TestSuite;
    //_ETcWatchdogAccumulationType_TestSuite : _ETcWatchdogAccumulationType_TestSuite;
    //_GEV_CAMERA_STATE_TestSuite : _GEV_CAMERA_STATE_TestSuite;
    
    //structs
	
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>