<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="VisionNodePack" Id="{257fc325-f932-4b89-a50a-e9a0a38418f4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK VisionNodePack IMPLEMENTS I_NodePack
VAR
    // Algebraic Container Operations
    //F_VN_AddContainers
    //F_VN_BitwiseAndContainers
    //F_VN_BitwiseNotContainer
    //F_VN_BitwiseOrContainers
    //F_VN_BitwiseXorContainers
    //F_VN_DivideContainers
    //F_VN_DivideContainersExp
    //F_VN_MaxContainer
    //F_VN_MinContainer
    //F_VN_MultiplyContainers
    //F_VN_MultiplyWithContainerElements1
    //F_VN_MultiplyWithContainerElements2
    //F_VN_MultiplyWithContainerElements3
    //F_VN_MultiplyWithContainerElements4
    //F_VN_NegateContainer
    //F_VN_SubtractContainers
   
    // Algebraic Image Operations
    //F_VN_AddImages
    //F_VN_AddImagesWeighted
    //F_VN_AddImagesWeightedExp
    //F_VN_AddScalarToImage
    //F_VN_AddVectorToImage
    //F_VN_BitwiseAndImages
    //F_VN_BitwiseAndImagesExp
    //F_VN_BitwiseAndScalarWithImage
    //F_VN_BitwiseAndVectorWithImage
    node_F_VN_BitwiseNotImage : Node_F_VN_BitwiseNotImage;
    //F_VN_BitwiseNotImageExp
    //F_VN_BitwiseOrImages
    //F_VN_BitwiseOrImagesExp
    //F_VN_BitwiseOrScalarWithImage
    //F_VN_BitwiseOrVectorWithImage
    //F_VN_BitwiseXorImages
    //F_VN_BitwiseXorImagesExp
    //F_VN_BitwiseXorScalarWithImage
    //F_VN_BitwiseXorVectorWithImage
    //F_VN_BlendImages
    //F_VN_DivideImageByScalar
    //F_VN_DivideImageByVector
    //F_VN_DivideImages
    //F_VN_DivideScalarByImage
    //F_VN_DivideVectorByImage
    //F_VN_ElementwiseExp
    //F_VN_ElementwiseLog
    //F_VN_MaxImage
    //F_VN_MaxImageExp
    //F_VN_MaxImageWithScalar
    //F_VN_MaxImageWithScalarExp
    //F_VN_MaxImageWithVector
    //F_VN_MaxImageWithVectorExp
    //F_VN_MinImage
    //F_VN_MinImageExp
    //F_VN_MinImageWithScalar
    //F_VN_MinImageWithScalarExp
    //F_VN_MinImageWithVector
    //F_VN_MinImageWithVectorExp
    //F_VN_MultiplyImages
    //F_VN_MultiplyImageWithScalar
    //F_VN_MultiplyImageWithVector
    //F_VN_SubtractImageFromScalar
    //F_VN_SubtractImageFromVector
    //F_VN_SubtractImages
    //F_VN_SubtractScalarFromImage
    //F_VN_SubtractVectorFromImage
        
    // Basic Container Operations
    node_F_VN_AppendToContainer_DINT : Node_F_VN_AppendToContainer_DINT;
    node_F_VN_AppendToContainer_INT : Node_F_VN_AppendToContainer_INT;
    node_F_VN_AppendToContainer_ITcVnContainer : Node_F_VN_AppendToContainer_ITcVnContainer;
    //node_F_VN_AppendToContainer_ITcVnForwardIterator : Node_F_VN_AppendToContainer_ITcVnForwardIterator;
    node_F_VN_AppendToContainer_ITcVnImage : Node_F_VN_AppendToContainer_ITcVnImage;
    node_F_VN_AppendToContainer_LREAL : Node_F_VN_AppendToContainer_LREAL;
    node_F_VN_AppendToContainer_REAL : Node_F_VN_AppendToContainer_REAL;
    node_F_VN_AppendToContainer_SINT : Node_F_VN_AppendToContainer_SINT;
    node_F_VN_AppendToContainer_TcVnDMatch : Node_F_VN_AppendToContainer_TcVnDMatch;
    node_F_VN_AppendToContainer_TcVnKeyPoint : Node_F_VN_AppendToContainer_TcVnKeyPoint;
    node_F_VN_AppendToContainer_TcVnPoint2_DINT : Node_F_VN_AppendToContainer_TcVnPoint2_DINT;
    node_F_VN_AppendToContainer_TcVnPoint2_LREAL : Node_F_VN_AppendToContainer_TcVnPoint2_LREAL;
    node_F_VN_AppendToContainer_TcVnPoint2_REAL : Node_F_VN_AppendToContainer_TcVnPoint2_REAL;
    node_F_VN_AppendToContainer_TcVnPoint3_LREAL : Node_F_VN_AppendToContainer_TcVnPoint3_LREAL;
    node_F_VN_AppendToContainer_TcVnPoint3_REAL : Node_F_VN_AppendToContainer_TcVnPoint3_REAL;
    node_F_VN_AppendToContainer_TcVnRectangle_DINT : Node_F_VN_AppendToContainer_TcVnRectangle_DINT;
    node_F_VN_AppendToContainer_TcVnVector2_DINT : Node_F_VN_AppendToContainer_TcVnVector2_DINT;
    node_F_VN_AppendToContainer_TcVnVector2_INT : Node_F_VN_AppendToContainer_TcVnVector2_INT;
    node_F_VN_AppendToContainer_TcVnVector2_REAL : Node_F_VN_AppendToContainer_TcVnVector2_REAL;
    node_F_VN_AppendToContainer_TcVnVector2_SINT : Node_F_VN_AppendToContainer_TcVnVector2_SINT;
    node_F_VN_AppendToContainer_TcVnVector2_UINT : Node_F_VN_AppendToContainer_TcVnVector2_UINT;
    node_F_VN_AppendToContainer_TcVnVector2_USINT : Node_F_VN_AppendToContainer_TcVnVector2_USINT;
    node_F_VN_AppendToContainer_TcVnVector3_INT : Node_F_VN_AppendToContainer_TcVnVector3_INT;
    node_F_VN_AppendToContainer_TcVnVector3_REAL : Node_F_VN_AppendToContainer_TcVnVector3_REAL;
    node_F_VN_AppendToContainer_TcVnVector3_SINT : Node_F_VN_AppendToContainer_TcVnVector3_SINT;
    node_F_VN_AppendToContainer_TcVnVector3_UINT : Node_F_VN_AppendToContainer_TcVnVector3_UINT;
    node_F_VN_AppendToContainer_TcVnVector3_USINT : Node_F_VN_AppendToContainer_TcVnVector3_USINT;
    node_F_VN_AppendToContainer_TcVnVector4_DINT : Node_F_VN_AppendToContainer_TcVnVector4_DINT;
    node_F_VN_AppendToContainer_TcVnVector4_INT : Node_F_VN_AppendToContainer_TcVnVector4_INT;
    node_F_VN_AppendToContainer_TcVnVector4_LREAL : Node_F_VN_AppendToContainer_TcVnVector4_LREAL;
    node_F_VN_AppendToContainer_TcVnVector4_SINT : Node_F_VN_AppendToContainer_TcVnVector4_SINT;
    node_F_VN_AppendToContainer_TcVnVector4_UINT : Node_F_VN_AppendToContainer_TcVnVector4_UINT;
    node_F_VN_AppendToContainer_TcVnVector4_USINT : Node_F_VN_AppendToContainer_TcVnVector4_USINT;
    node_F_VN_AppendToContainer_UDINT : Node_F_VN_AppendToContainer_UDINT;
    node_F_VN_AppendToContainer_UINT : node_F_VN_AppendToContainer_UINT;
    node_F_VN_AppendToContainer_ULINT : Node_F_VN_AppendToContainer_ULINT;
    node_F_VN_AppendToContainer_USINT : Node_F_VN_AppendToContainer_USINT;
    
    node_F_VN_FillContainer_DINT : Node_F_VN_FillContainer_DINT;
    node_F_VN_FillContainer_INT : Node_F_VN_FillContainer_INT;
    node_F_VN_FillContainer_ITcVnImage : Node_F_VN_FillContainer_ITcVnImage;
    node_F_VN_FillContainer_LREAL : Node_F_VN_FillContainer_LREAL;
    node_F_VN_FillContainer_REAL : Node_F_VN_FillContainer_REAL;
    node_F_VN_FillContainer_SINT : Node_F_VN_FillContainer_SINT;
    node_F_VN_FillContainer_TcVnDMatch : Node_F_VN_FillContainer_TcVnDMatch;
    node_F_VN_FillContainer_TcVnKeyPoint : Node_F_VN_FillContainer_TcVnKeyPoint;
    node_F_VN_FillContainer_TcVnPoint2_DINT : Node_F_VN_FillContainer_TcVnPoint2_DINT;
    node_F_VN_FillContainer_TcVnPoint2_LREAL : Node_F_VN_FillContainer_TcVnPoint2_LREAL;
    node_F_VN_FillContainer_TcVnPoint2_REAL : Node_F_VN_FillContainer_TcVnPoint2_REAL;
    node_F_VN_FillContainer_TcVnPoint3_LREAL : Node_F_VN_FillContainer_TcVnPoint3_LREAL;
    node_F_VN_FillContainer_TcVnPoint3_REAL : Node_F_VN_FillContainer_TcVnPoint3_REAL;
    node_F_VN_FillContainer_TcVnRectangle_DINT : Node_F_VN_FillContainer_TcVnRectangle_DINT;
    node_F_VN_FillContainer_TcVnVector2_DINT : Node_F_VN_FillContainer_TcVnVector2_DINT;
    node_F_VN_FillContainer_TcVnVector2_INT : Node_F_VN_FillContainer_TcVnVector2_INT;
    node_F_VN_FillContainer_TcVnVector2_REAL : Node_F_VN_FillContainer_TcVnVector2_REAL;
    node_F_VN_FillContainer_TcVnVector2_SINT : Node_F_VN_FillContainer_TcVnVector2_SINT;
    node_F_VN_FillContainer_TcVnVector2_UINT : Node_F_VN_FillContainer_TcVnVector2_UINT;
    node_F_VN_FillContainer_TcVnVector2_USINT : Node_F_VN_FillContainer_TcVnVector2_USINT;
    node_F_VN_FillContainer_TcVnVector3_INT : Node_F_VN_FillContainer_TcVnVector3_INT;
    node_F_VN_FillContainer_TcVnVector3_REAL : Node_F_VN_FillContainer_TcVnVector3_REAL;
    node_F_VN_FillContainer_TcVnVector3_SINT : Node_F_VN_FillContainer_TcVnVector3_SINT;
    node_F_VN_FillContainer_TcVnVector3_UINT : Node_F_VN_FillContainer_TcVnVector3_UINT;
    node_F_VN_FillContainer_TcVnVector3_USINT : Node_F_VN_FillContainer_TcVnVector3_USINT;
    node_F_VN_FillContainer_TcVnVector4_DINT : Node_F_VN_FillContainer_TcVnVector4_DINT;
    node_F_VN_FillContainer_TcVnVector4_INT : Node_F_VN_FillContainer_TcVnVector4_INT;
    node_F_VN_FillContainer_TcVnVector4_LREAL : Node_F_VN_FillContainer_TcVnVector4_LREAL;
    node_F_VN_FillContainer_TcVnVector4_SINT : Node_F_VN_FillContainer_TcVnVector4_SINT;
    node_F_VN_FillContainer_TcVnVector4_UINT : Node_F_VN_FillContainer_TcVnVector4_UINT;
    node_F_VN_FillContainer_TcVnVector4_USINT : Node_F_VN_FillContainer_TcVnVector4_USINT;
    node_F_VN_FillContainer_UDINT : Node_F_VN_FillContainer_UDINT;
    node_F_VN_FillContainer_UINT : node_F_VN_FillContainer_UINT;
    node_F_VN_FillContainer_ULINT : Node_F_VN_FillContainer_ULINT;
    node_F_VN_FillContainer_USINT : Node_F_VN_FillContainer_USINT;
    
    //F_VN_FillContainerExp_DINT
    //F_VN_FillContainerExp_INT
    //F_VN_FillContainerExp_ITcVnImage
    //F_VN_FillContainerExp_LREAL
    //F_VN_FillContainerExp_REAL
    //F_VN_FillContainerExp_SINT
    //F_VN_FillContainerExp_TcVnDMatch
    //F_VN_FillContainerExp_TcVnKeyPoint
    //F_VN_FillContainerExp_TcVnPoint2_DINT
    //F_VN_FillContainerExp_TcVnPoint2_LREAL
    //F_VN_FillContainerExp_TcVnPoint2_REAL
    //F_VN_FillContainerExp_TcVnPoint3_LREAL
    //F_VN_FillContainerExp_TcVnPoint3_REAL
    //F_VN_FillContainerExp_TcVnRectangle_DINT
    //F_VN_FillContainerExp_TcVnVector2_DINT
    //F_VN_FillContainerExp_TcVnVector2_INT
    //F_VN_FillContainerExp_TcVnVector2_REAL
    //F_VN_FillContainerExp_TcVnVector2_SINT
    //F_VN_FillContainerExp_TcVnVector2_UINT
    //F_VN_FillContainerExp_TcVnVector2_USINT
    //F_VN_FillContainerExp_TcVnVector3_INT
    //F_VN_FillContainerExp_TcVnVector3_REAL
    //F_VN_FillContainerExp_TcVnVector3_SINT
    //F_VN_FillContainerExp_TcVnVector3_UINT
    //F_VN_FillContainerExp_TcVnVector3_USINT
    //F_VN_FillContainerExp_TcVnVector4_DINT
    //F_VN_FillContainerExp_TcVnVector4_INT
    //F_VN_FillContainerExp_TcVnVector4_LREAL
    //F_VN_FillContainerExp_TcVnVector4_SINT
    //F_VN_FillContainerExp_TcVnVector4_UINT
    //F_VN_FillContainerExp_TcVnVector4_USINT
    //F_VN_FillContainerExp_UDINT
    //F_VN_FillContainerExp_UINT
    //F_VN_FillContainerExp_ULINT
    //F_VN_FillContainerExp_USINT
    
    //F_VN_GetAt_DINT
    //F_VN_GetAt_INT
    //F_VN_GetAt_ITcVnContainer
    //F_VN_GetAt_ITcVnImage
    //F_VN_GetAt_LREAL
    //F_VN_GetAt_REAL
    //F_VN_GetAt_SINT
    //F_VN_GetAt_TcVnDMatch
    //F_VN_GetAt_TcVnKeyPoint
    //F_VN_GetAt_TcVnPoint2_DINT
    //F_VN_GetAt_TcVnPoint2_LREAL
    //F_VN_GetAt_TcVnPoint2_REAL
    //F_VN_GetAt_TcVnPoint3_LREAL
    //F_VN_GetAt_TcVnPoint3_REAL
    //F_VN_GetAt_TcVnRectangle_DINT
    //F_VN_GetAt_TcVnVector2_DINT
    //F_VN_GetAt_TcVnVector2_INT
    //F_VN_GetAt_TcVnVector2_REAL
    //F_VN_GetAt_TcVnVector2_SINT
    //F_VN_GetAt_TcVnVector2_UINT
    //F_VN_GetAt_TcVnVector2_USINT
    //F_VN_GetAt_TcVnVector3_INT
    //F_VN_GetAt_TcVnVector3_REAL
    //F_VN_GetAt_TcVnVector3_SINT
    //F_VN_GetAt_TcVnVector3_UINT
    //F_VN_GetAt_TcVnVector3_USINT
    //F_VN_GetAt_TcVnVector4_DINT
    //F_VN_GetAt_TcVnVector4_INT
    //F_VN_GetAt_TcVnVector4_LREAL
    //F_VN_GetAt_TcVnVector4_SINT
    //F_VN_GetAt_TcVnVector4_UINT
    //F_VN_GetAt_TcVnVector4_USINT
    //F_VN_GetAt_UDINT
    //F_VN_GetAt_UINT
    //F_VN_GetAt_ULINT
    //F_VN_GetAt_USINT
    
    node_F_VN_InsertIntoContainer_DINT : Node_F_VN_InsertIntoContainer_DINT;
    node_F_VN_InsertIntoContainer_INT : Node_F_VN_InsertIntoContainer_INT;
    node_F_VN_InsertIntoContainer_ITcVnContainer : Node_F_VN_InsertIntoContainer_ITcVnContainer;
    //node_F_VN_InsertIntoContainer_ITcVnForwardIterator : Node_F_VN_InsertIntoContainer_ITcVnForwardIterator;
    node_F_VN_InsertIntoContainer_ITcVnImage : Node_F_VN_InsertIntoContainer_ITcVnImage;
    node_F_VN_InsertIntoContainer_LREAL : Node_F_VN_InsertIntoContainer_LREAL;
    node_F_VN_InsertIntoContainer_REAL : Node_F_VN_InsertIntoContainer_REAL;
    node_F_VN_InsertIntoContainer_SINT : Node_F_VN_InsertIntoContainer_SINT;
    node_F_VN_InsertIntoContainer_TcVnDMatch : Node_F_VN_InsertIntoContainer_TcVnDMatch;
    node_F_VN_InsertIntoContainer_TcVnKeyPoint : Node_F_VN_InsertIntoContainer_TcVnKeyPoint;
    node_F_VN_InsertIntoContainer_TcVnPoint2_DINT : Node_F_VN_InsertIntoContainer_TcVnPoint2_DINT;
    node_F_VN_InsertIntoContainer_TcVnPoint2_LREAL : Node_F_VN_InsertIntoContainer_TcVnPoint2_LREAL;
    node_F_VN_InsertIntoContainer_TcVnPoint2_REAL : Node_F_VN_InsertIntoContainer_TcVnPoint2_REAL;
    node_F_VN_InsertIntoContainer_TcVnPoint3_LREAL : Node_F_VN_InsertIntoContainer_TcVnPoint3_LREAL;
    node_F_VN_InsertIntoContainer_TcVnPoint3_REAL : Node_F_VN_InsertIntoContainer_TcVnPoint3_REAL;
    node_F_VN_InsertIntoContainer_TcVnRectangle_DINT : Node_F_VN_InsertIntoContainer_TcVnRectangle_DINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_DINT : Node_F_VN_InsertIntoContainer_TcVnVector2_DINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_INT : Node_F_VN_InsertIntoContainer_TcVnVector2_INT;
    node_F_VN_InsertIntoContainer_TcVnVector2_REAL : Node_F_VN_InsertIntoContainer_TcVnVector2_REAL;
    node_F_VN_InsertIntoContainer_TcVnVector2_SINT : Node_F_VN_InsertIntoContainer_TcVnVector2_SINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_UINT : Node_F_VN_InsertIntoContainer_TcVnVector2_UINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_USINT : Node_F_VN_InsertIntoContainer_TcVnVector2_USINT;
    node_F_VN_InsertIntoContainer_TcVnVector3_INT : Node_F_VN_InsertIntoContainer_TcVnVector3_INT;
    node_F_VN_InsertIntoContainer_TcVnVector3_REAL : Node_F_VN_InsertIntoContainer_TcVnVector3_REAL;
    node_F_VN_InsertIntoContainer_TcVnVector3_SINT : Node_F_VN_InsertIntoContainer_TcVnVector3_SINT;
    node_F_VN_InsertIntoContainer_TcVnVector3_UINT : Node_F_VN_InsertIntoContainer_TcVnVector3_UINT;
    node_F_VN_InsertIntoContainer_TcVnVector3_USINT : Node_F_VN_InsertIntoContainer_TcVnVector3_USINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_DINT : Node_F_VN_InsertIntoContainer_TcVnVector4_DINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_INT : Node_F_VN_InsertIntoContainer_TcVnVector4_INT;
    node_F_VN_InsertIntoContainer_TcVnVector4_LREAL : Node_F_VN_InsertIntoContainer_TcVnVector4_LREAL;
    node_F_VN_InsertIntoContainer_TcVnVector4_SINT : Node_F_VN_InsertIntoContainer_TcVnVector4_SINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_UINT : Node_F_VN_InsertIntoContainer_TcVnVector4_UINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_USINT : Node_F_VN_InsertIntoContainer_TcVnVector4_USINT;
    node_F_VN_InsertIntoContainer_UDINT : Node_F_VN_InsertIntoContainer_UDINT;
    node_F_VN_InsertIntoContainer_UINT : node_F_VN_InsertIntoContainer_UINT;
    node_F_VN_InsertIntoContainer_ULINT : Node_F_VN_InsertIntoContainer_ULINT;
    node_F_VN_InsertIntoContainer_USINT : Node_F_VN_InsertIntoContainer_USINT;
    
    node_F_VN_SetAt_DINT : Node_F_VN_SetAt_DINT;
    node_F_VN_SetAt_INT : Node_F_VN_SetAt_INT;
    node_F_VN_SetAt_ITcVnContainer : Node_F_VN_SetAt_ITcVnContainer;
    node_F_VN_SetAt_ITcVnImage : Node_F_VN_SetAt_ITcVnImage;
    node_F_VN_SetAt_LREAL : Node_F_VN_SetAt_LREAL;
    node_F_VN_SetAt_REAL : Node_F_VN_SetAt_REAL;
    node_F_VN_SetAt_SINT : Node_F_VN_SetAt_SINT;
    node_F_VN_SetAt_TcVnDMatch : Node_F_VN_SetAt_TcVnDMatch;
    node_F_VN_SetAt_TcVnKeyPoint : Node_F_VN_SetAt_TcVnKeyPoint;
    node_F_VN_SetAt_TcVnPoint2_DINT : Node_F_VN_SetAt_TcVnPoint2_DINT;
    node_F_VN_SetAt_TcVnPoint2_LREAL : Node_F_VN_SetAt_TcVnPoint2_LREAL;
    node_F_VN_SetAt_TcVnPoint2_REAL : Node_F_VN_SetAt_TcVnPoint2_REAL;
    node_F_VN_SetAt_TcVnPoint3_LREAL : Node_F_VN_SetAt_TcVnPoint3_LREAL;
    node_F_VN_SetAt_TcVnPoint3_REAL : Node_F_VN_SetAt_TcVnPoint3_REAL;
    node_F_VN_SetAt_TcVnRectangle_DINT : Node_F_VN_SetAt_TcVnRectangle_DINT;
    node_F_VN_SetAt_TcVnVector2_DINT : Node_F_VN_SetAt_TcVnVector2_DINT;
    node_F_VN_SetAt_TcVnVector2_INT : Node_F_VN_SetAt_TcVnVector2_INT;
    node_F_VN_SetAt_TcVnVector2_REAL : Node_F_VN_SetAt_TcVnVector2_REAL;
    node_F_VN_SetAt_TcVnVector2_SINT : Node_F_VN_SetAt_TcVnVector2_SINT;
    node_F_VN_SetAt_TcVnVector2_UINT : Node_F_VN_SetAt_TcVnVector2_UINT;
    node_F_VN_SetAt_TcVnVector2_USINT : Node_F_VN_SetAt_TcVnVector2_USINT;
    node_F_VN_SetAt_TcVnVector3_INT : Node_F_VN_SetAt_TcVnVector3_INT;
    node_F_VN_SetAt_TcVnVector3_REAL : Node_F_VN_SetAt_TcVnVector3_REAL;
    node_F_VN_SetAt_TcVnVector3_SINT : Node_F_VN_SetAt_TcVnVector3_SINT;
    node_F_VN_SetAt_TcVnVector3_UINT : Node_F_VN_SetAt_TcVnVector3_UINT;
    node_F_VN_SetAt_TcVnVector3_USINT : Node_F_VN_SetAt_TcVnVector3_USINT;
    node_F_VN_SetAt_TcVnVector4_DINT : Node_F_VN_SetAt_TcVnVector4_DINT;
    node_F_VN_SetAt_TcVnVector4_INT : Node_F_VN_SetAt_TcVnVector4_INT;
    node_F_VN_SetAt_TcVnVector4_LREAL : Node_F_VN_SetAt_TcVnVector4_LREAL;
    node_F_VN_SetAt_TcVnVector4_SINT : Node_F_VN_SetAt_TcVnVector4_SINT;
    node_F_VN_SetAt_TcVnVector4_UINT : Node_F_VN_SetAt_TcVnVector4_UINT;
    node_F_VN_SetAt_TcVnVector4_USINT : Node_F_VN_SetAt_TcVnVector4_USINT;
    node_F_VN_SetAt_UDINT : Node_F_VN_SetAt_UDINT;
    node_F_VN_SetAt_UINT : node_F_VN_SetAt_UINT;
    node_F_VN_SetAt_ULINT : Node_F_VN_SetAt_ULINT;
    node_F_VN_SetAt_USINT : Node_F_VN_SetAt_USINT;
    
    //F_VN_AdvanceIterator
    //F_VN_CheckIfEmpty
    //F_VN_CheckIfIteratorIsAtEnd
    //F_VN_ConvertContainerType
    //F_VN_CopyContainer
    //F_VN_CopyContainerElementsConditional_ITcVnContainer
    //F_VN_CopyContainerElementsConditional_ITcVnForwardIterator
    //F_VN_CreateContainer
    //F_VN_CreateContainerFromArray
    //F_VN_EraseFromContainer
    //F_VN_ExportContainer
    //F_VN_ExportContainer_String
    //F_VN_ExportContainerSize
    //F_VN_ExportSubContainer
    //F_VN_ExportSubContainer_String
    //F_VN_ExportSubContainerSize
    //F_VN_ExtractContainerRange
    //F_VN_GetContainer
    //F_VN_GetContainerExp
    //F_VN_GetForwardIterator
    node_F_VN_GetNumberOfElements : Node_F_VN_GetNumberOfElements;
    //F_VN_GetRandomAccessIterator
    //F_VN_IncrementIterator
    //F_VN_IteratorDistance
    //F_VN_ReserveContainerMemory
    //F_VN_ReverseContainer
    //F_VN_SetContainer
    //F_VN_SetIteratorToBegin
    
    // Basic Image Operations
    //F_VN_CombineImageChannels
    //F_VN_ConvertElementType
    //F_VN_ConvertElementTypeExp
    node_F_VN_CopyImage : Node_F_VN_CopyImage;
    //F_VN_CopyImageRegion
    //F_VN_CopyImageRegionToRegion
    //F_VN_CopyIntoDisplayableImage
    //F_VN_CreateAssociatedImage
    //F_VN_CreateEmptyImage
    //F_VN_CreateImage
    //F_VN_CreateImageAndSetPixels
    //F_VN_CreateImageFromArray
    //F_VN_ExportImage
    //F_VN_ExportImageAsBmp
    //F_VN_ExportImageAsBmpExp
    //F_VN_ExportImageAsBmpSize
    //F_VN_ExportImageAsBmpSizeExp
    //F_VN_ExportImageSize
    //F_VN_FuseImages
    //F_VN_FuseImagesArray
    node_F_VN_GetImageChannel : Node_F_VN_GetImageChannel;
    node_F_VN_GetImageHeight : Node_F_VN_GetImageHeight;
    node_F_VN_GetImageInfo : Node_F_VN_GetImageInfo;
    node_F_VN_GetImageWidth : Node_F_VN_GetImageWidth;
    //F_VN_GetPixel
     node_F_VN_GetPixelFormat : Node_F_VN_GetPixelFormat;
    //F_VN_GetRoi
    //F_VN_MixImageChannels
    //F_VN_ResetRoi
    //F_VN_SetImageChannel
    //F_VN_SetPixel
    //F_VN_SetPixels
    //F_VN_SetPixelsExp
    node_F_VN_SetRoi : Node_F_VN_SetRoi;
    //node_F_VN_SetRoi_TcVnRectangle_DINT : Node_F_VN_SetRoi_TcVnRectangle_DINT;
    //F_VN_SetRoi_TcVnRectangle_UDINT
    //F_VN_SplitImageChannels
    //F_VN_TransformIntoDisplayableImage
    //F_VN_TransformIntoDisplayableImageExp
    
    // Code Quality
    //F_VN_GradeBarcode
    //F_VN_GradeBarcodeExp
    //F_VN_GradeDataMatrixCode
    //F_VN_GradeDataMatrixCodeExp
    //F_VN_GradeQRCode
    //F_VN_GradeQRCodeExp
    
    // Code Reading
    // node_F_VN_ReadBarcode : Node_F_VN_ReadBarcode
    // node_F_VN_ReadBarcodeExp : Node_F_VN_ReadBarcodeExp
    // node_F_VN_ReadBarcodeExp2 : Node_F_VN_ReadBarcodeExp2
    // node_F_VN_ReadDataMatrixCode : Node_F_VN_ReadDataMatrixCode
    // node_F_VN_ReadDataMatrixCodeExp : Node_F_VN_ReadDataMatrixCodeExp
    // node_F_VN_ReadDataMatrixCodeExp2 : Node_F_VN_ReadDataMatrixCodeExp2
    // node_F_VN_ReadPharmaCode : Node_F_VN_ReadPharmaCode
    // node_F_VN_ReadPharmaCodeExp : Node_F_VN_ReadPharmaCodeExp
    // node_F_VN_ReadPharmaCodeExp2 : Node_F_VN_ReadPharmaCodeExp2
    // node_F_VN_ReadQRCode : Node_F_VN_ReadQRCode
    // node_F_VN_ReadQRCodeExp : Node_F_VN_ReadQRCodeExp
    // node_F_VN_ReadQRCodeExp2 : Node_F_VN_ReadQRCodeExp2
    
    // Constants
    node_RGBA_BLACK : Node_RGBA_BLACK;
    node_RGBA_RED : Node_RGBA_RED;
    node_RGBA_YELLOW : Node_RGBA_YELLOW;
    node_RGBA_GREEN : Node_RGBA_GREEN;
    node_RGBA_CYAN : Node_RGBA_CYAN;
    node_RGBA_BLUE : Node_RGBA_BLUE;
    node_RGBA_MAGENTA : Node_RGBA_MAGENTA;
    node_RGBA_WHITE : Node_RGBA_WHITE;
    
    // Container Statistics
    //F_VN_MaxElementElementwise_DINT
    //F_VN_MaxElementElementwise_INT
    //F_VN_MaxElementElementwise_LREAL
    //F_VN_MaxElementElementwise_REAL
    //F_VN_MaxElementElementwise_SINT
    //F_VN_MaxElementElementwise_TcVnPoint2_DINT
    //F_VN_MaxElementElementwise_TcVnPoint2_LREAL
    //F_VN_MaxElementElementwise_TcVnPoint2_REAL
    //F_VN_MaxElementElementwise_TcVnPoint3_LREAL
    //F_VN_MaxElementElementwise_TcVnPoint3_REAL
    //F_VN_MaxElementElementwise_TcVnVector2_DINT
    //F_VN_MaxElementElementwise_TcVnVector2_INT
    //F_VN_MaxElementElementwise_TcVnVector2_REAL
    //F_VN_MaxElementElementwise_TcVnVector2_SINT
    //F_VN_MaxElementElementwise_TcVnVector2_UINT
    //F_VN_MaxElementElementwise_TcVnVector2_USINT
    //F_VN_MaxElementElementwise_TcVnVector3_INT
    //F_VN_MaxElementElementwise_TcVnVector3_REAL
    //F_VN_MaxElementElementwise_TcVnVector3_SINT
    //F_VN_MaxElementElementwise_TcVnVector3_UINT
    //F_VN_MaxElementElementwise_TcVnVector3_USINT
    //F_VN_MaxElementElementwise_TcVnVector4_DINT
    //F_VN_MaxElementElementwise_TcVnVector4_INT
    //F_VN_MaxElementElementwise_TcVnVector4_LREAL
    //F_VN_MaxElementElementwise_TcVnVector4_SINT
    //F_VN_MaxElementElementwise_TcVnVector4_UINT
    //F_VN_MaxElementElementwise_TcVnVector4_USINT
    //F_VN_MaxElementElementwise_UDINT
    //F_VN_MaxElementElementwise_UINT
    //F_VN_MaxElementElementwise_ULINT
    //F_VN_MaxElementElementwise_USINT
    //F_VN_MedianElementElementwise_DINT
    //F_VN_MedianElementElementwise_INT
    //F_VN_MedianElementElementwise_LREAL
    //F_VN_MedianElementElementwise_REAL
    //F_VN_MedianElementElementwise_SINT
    //F_VN_MedianElementElementwise_TcVnPoint2_DINT
    //F_VN_MedianElementElementwise_TcVnPoint2_LREAL
    //F_VN_MedianElementElementwise_TcVnPoint2_REAL
    //F_VN_MedianElementElementwise_TcVnPoint3_LREAL
    //F_VN_MedianElementElementwise_TcVnPoint3_REAL
    //F_VN_MedianElementElementwise_TcVnVector2_DINT
    //F_VN_MedianElementElementwise_TcVnVector2_INT
    //F_VN_MedianElementElementwise_TcVnVector2_REAL
    //F_VN_MedianElementElementwise_TcVnVector2_SINT
    //F_VN_MedianElementElementwise_TcVnVector2_UINT
    //F_VN_MedianElementElementwise_TcVnVector2_USINT
    //F_VN_MedianElementElementwise_TcVnVector3_INT
    //F_VN_MedianElementElementwise_TcVnVector3_REAL
    //F_VN_MedianElementElementwise_TcVnVector3_SINT
    //F_VN_MedianElementElementwise_TcVnVector3_UINT
    //F_VN_MedianElementElementwise_TcVnVector3_USINT
    //F_VN_MedianElementElementwise_TcVnVector4_DINT
    //F_VN_MedianElementElementwise_TcVnVector4_INT
    //F_VN_MedianElementElementwise_TcVnVector4_LREAL
    //F_VN_MedianElementElementwise_TcVnVector4_SINT
    //F_VN_MedianElementElementwise_TcVnVector4_UINT
    //F_VN_MedianElementElementwise_TcVnVector4_USINT
    //F_VN_MedianElementElementwise_UDINT
    //F_VN_MedianElementElementwise_UINT
    //F_VN_MedianElementElementwise_ULINT
    //F_VN_MedianElementElementwise_USINT
    //F_VN_MinElementElementwise_DINT
    //F_VN_MinElementElementwise_INT
    //F_VN_MinElementElementwise_LREAL
    //F_VN_MinElementElementwise_REAL
    //F_VN_MinElementElementwise_SINT
    //F_VN_MinElementElementwise_TcVnPoint2_DINT
    //F_VN_MinElementElementwise_TcVnPoint2_LREAL
    //F_VN_MinElementElementwise_TcVnPoint2_REAL
    //F_VN_MinElementElementwise_TcVnPoint3_LREAL
    //F_VN_MinElementElementwise_TcVnPoint3_REAL
    //F_VN_MinElementElementwise_TcVnVector2_DINT
    //F_VN_MinElementElementwise_TcVnVector2_INT
    //F_VN_MinElementElementwise_TcVnVector2_REAL
    //F_VN_MinElementElementwise_TcVnVector2_SINT
    //F_VN_MinElementElementwise_TcVnVector2_UINT
    //F_VN_MinElementElementwise_TcVnVector2_USINT
    //F_VN_MinElementElementwise_TcVnVector3_INT
    //F_VN_MinElementElementwise_TcVnVector3_REAL
    //F_VN_MinElementElementwise_TcVnVector3_SINT
    //F_VN_MinElementElementwise_TcVnVector3_UINT
    //F_VN_MinElementElementwise_TcVnVector3_USINT
    //F_VN_MinElementElementwise_TcVnVector4_DINT
    //F_VN_MinElementElementwise_TcVnVector4_INT
    //F_VN_MinElementElementwise_TcVnVector4_LREAL
    //F_VN_MinElementElementwise_TcVnVector4_SINT
    //F_VN_MinElementElementwise_TcVnVector4_UINT
    //F_VN_MinElementElementwise_TcVnVector4_USINT
    //F_VN_MinElementElementwise_UDINT
    //F_VN_MinElementElementwise_UINT
    //F_VN_MinElementElementwise_ULINT
    //F_VN_MinElementElementwise_USINT
    //F_VN_ContainerAverage
    //F_VN_ContainerAverageElementwise2
    //F_VN_ContainerAverageElementwise3
    //F_VN_ContainerAverageElementwise4
    //F_VN_ContainerAverageVariance
    //F_VN_ContainerAverageVarianceElementwise2
    //F_VN_ContainerAverageVarianceElementwise3
    //F_VN_ContainerAverageVarianceElementwise4
    //F_VN_MaxElement
    //F_VN_MedianElement
    //F_VN_MinElement
   
    // Contour Analysis
    //F_VN_ApproximatePolygon
    //F_VN_CheckIfPointIsInsideContour
    //F_VN_ContourArea
    //F_VN_ContourCenterOfMass
    //F_VN_ContourCircularity
    //F_VN_ContourConvexity
    //F_VN_ContourEccentricity
    //F_VN_ContourElongation
    //F_VN_ContourExtremePoint
    //F_VN_ContourInertiaRatio
    //F_VN_ContourMoments
    //F_VN_ContourOrientation
    //F_VN_ContourOrientationExp
    //F_VN_ContourPerimeter
    //F_VN_ContourRoundness
    //F_VN_ConvexHullPoints
    //F_VN_ConvexHullPointsExp
    //F_VN_ConvexityDefects
    //F_VN_CustomElementWiseContainerOperation_ITcVnContainer
    //F_VN_CustomElementWiseContainerOperation_ITcVnForwardIterator
    //F_VN_EnclosingCircle
    //F_VN_EnclosingRectangle
    //F_VN_EnclosingTriangle
    //F_VN_FitEllipse
    node_F_VN_FitLine : Node_F_VN_FitLine;
    //F_VN_FitLineExp
    //F_VN_FourierDescriptors
    //F_VN_MatchContours
    //F_VN_MatchContours1vsN
    //F_VN_MatchContours1vsNExp
    //F_VN_MatchContoursExp
    //F_VN_UprightBoundingRectangle
    
    // Control Functions
    //F_VN_StartAbsWatchdog
    //F_VN_StartAbsWatchdogExp
    //F_VN_StartRelWatchdog
    //F_VN_StartRelWatchdogExp
    //F_VN_StopWatchdog
    
    // Drawing
    //F_VN_DrawArrow
    //F_VN_DrawArrow_TcVnVector4_DINT
    //F_VN_DrawArrowExp
    //F_VN_DrawArrowExp_TcVnVector4_DINT
    //F_VN_DrawCircle
    //F_VN_DrawCircleExp
    //F_VN_DrawCircles
    //F_VN_DrawCirclesExp
    //F_VN_DrawCircularArc
    //F_VN_DrawCircularArcExp
    //F_VN_DrawComponents
    //F_VN_DrawComponentsExp
    node_F_VN_DrawContours : Node_F_VN_DrawContours;
    //F_VN_DrawContoursExp
    //F_VN_DrawEllipse
    //F_VN_DrawEllipseExp
    //F_VN_DrawKeypoints
    //F_VN_DrawKeypointsExp
    node_F_VN_DrawLine : Node_F_VN_DrawLine;
    //F_VN_DrawLine_TcVnVector4_DINT
    node_F_VN_DrawLine_TcVnVector4_LREAL : Node_F_VN_DrawLine_TcVnVector4_LREAL;
    //F_VN_DrawLineExp
    //F_VN_DrawLineExp_TcVnVector4_DINT
    //F_VN_DrawLineExp_TcVnVector4_LREAL
    //F_VN_DrawLines
    //F_VN_DrawLinesExp
    //F_VN_DrawMatches
    //F_VN_DrawMatchesExp
    //F_VN_DrawOrientation
    //F_VN_DrawOrientationExp
    //F_VN_DrawPoint
    //F_VN_DrawPointExp
    //F_VN_DrawPoints
    //F_VN_DrawPointsExp
    //F_VN_DrawPolygon
    //F_VN_DrawPolygonExp
    //F_VN_DrawRectangle
    //F_VN_DrawRectangle_TcVnRectangle_DINT
    //F_VN_DrawRectangle_TcVnRectangle_UDINT
    //F_VN_DrawRotatedRectangle
    //F_VN_DrawRotatedRectangleExp
    //F_VN_FillCircle
    //F_VN_FillContours
    //F_VN_FillEllipse
    //F_VN_FillPolygon
    //F_VN_FillRectangle
    //F_VN_FillRotatedRectangle
    //F_VN_PlotIntensityProfile
    //F_VN_PlotIntensityProfileExp
    node_F_VN_PutLabel : Node_F_VN_PutLabel;
    //F_VN_PutLabelExp
    node_F_VN_PutText : Node_F_VN_PutText;
    //F_VN_PutTextExp
    
    // Fourier Analysis
    //F_VN_CreateBandpassButterworthFilter
    //F_VN_CreateBandpassGaussianFilter
    //F_VN_CreateBandrejectButterworthFilter
    //F_VN_CreateBandrejectGaussianFilter
    //F_VN_CreateHighpassButterworthFilter
    //F_VN_CreateHighpassGaussianFilter
    //F_VN_CreateLowpassButterworthFilter
    //F_VN_CreateLowpassGaussianFilter
    //F_VN_Dft
    //F_VN_InverseDft
    //F_VN_OptimalDftSize
    //F_VN_PadImageBorder
    //F_VN_PadImageBorderExp
    
    // Geometric and Coordinate Transformations
    //F_VN_CalibrateCamera
    //F_VN_CalibrateCameraExp
    //F_VN_CalibrateCameraExp2
    //F_VN_CalibrateCameraExp3
    //F_VN_CalibrateCameraManually
    //F_VN_CalibrateCameraManuallyExp
    //F_VN_CalibrateCameraPlanar
    //F_VN_CalibrateCameraPlanarExp
    //F_VN_CalibrateLinescanCamera
    //F_VN_CalibrateLinescanCameraExp
    //F_VN_CompensateLensDistortion
    //F_VN_CompensateLensDistortionExp1
    //F_VN_CompensateLensDistortionExp2
    //F_VN_CompensateLensDistortionForPoints
    //F_VN_CompensateLensDistortionForPointsExp1
    //F_VN_CompensateLensDistortionForPointsExp2
    //F_VN_DetectPatternPoints
    //F_VN_DetectPatternPointsExp
    //F_VN_GenerateCalibrationPatternReferencePoints
    //F_VN_ImagePointsWorldDistance
    //F_VN_SolvePnP
    //F_VN_SolvePnPExp
    //F_VN_SortDetectedPatternPoints
    //F_VN_TransformCoordinatesImageToWorld_Container
    //F_VN_TransformCoordinatesImageToWorld_Point
    //F_VN_TransformCoordinatesPlanar_Container
    //F_VN_TransformCoordinatesPlanar_Point
    //F_VN_TransformCoordinatesWorldToImage_Container
    //F_VN_TransformCoordinatesWorldToImage_Point
    //F_VN_AlignRotatedImageRegion
    //F_VN_AlignRotatedImageRegionExp
    //F_VN_ApplyRotationToAffineTransformation
    //F_VN_ApplyRotationToAffineTransformationExp
    //F_VN_ApplyScalingToAffineTransformation
    //F_VN_ApplyScalingToAffineTransformationExp
    //F_VN_ApplyTranslationToAffineTransformation
    //F_VN_ApplyTranslationToAffineTransformationExp
    //F_VN_ApplyYAxisInversionToAffineTransformation
    //F_VN_ApplyYAxisInversionToAffineTransformationExp
    //F_VN_ConvertCartesianToPolarAngleImage
    //F_VN_ConvertCartesianToPolarAngleImageExp
    //F_VN_ConvertCartesianToPolarAngles
    //F_VN_ConvertCartesianToPolarAnglesExp
    //F_VN_ConvertCartesianToPolarImages
    //F_VN_ConvertCartesianToPolarImagesExp
    //F_VN_ConvertCartesianToPolarMagnitudeImage
    //F_VN_ConvertCartesianToPolarMagnitudes
    //F_VN_ConvertCartesianToPolarPoints
    //F_VN_ConvertCartesianToPolarPointsExp
    //F_VN_ConvertPolarToCartesianImages
    //F_VN_ConvertPolarToCartesianImagesExp
    //F_VN_ConvertPolarToCartesianPoints
    //F_VN_ConvertPolarToCartesianPointsExp
    //F_VN_DecomposeAffineTransformation
    //F_VN_DecomposeAffineTransformationExp
    //F_VN_DecomposeHomography
    //F_VN_DecomposeHomographyExp
    node_F_VN_FlipImage : Node_F_VN_FlipImage;
    //F_VN_GenerateAffineTransformationUnitMatrix2D
    //F_VN_GetAffineTransformation
    //F_VN_GetAffineTransformation2D
    //F_VN_GetAffineTransformation2DExp
    //F_VN_GetPerspectiveTransformation
    //F_VN_Homography
    //F_VN_HomographyExp
    //F_VN_InvertAffineTransformation
    //F_VN_PerspectiveTransformation
    //F_VN_PyramidDown
    //F_VN_PyramidUp
    //F_VN_RemapImageToLogPolarSpace
    //F_VN_RemapImageToLogPolarSpaceExp
    //F_VN_RemapImageToLogPolarSpaceExp2
    //F_VN_RemapImageToPolarSpace
    //F_VN_RemapImageToPolarSpaceExp
    //F_VN_RemapImageToPolarSpaceExp2
    //F_VN_ResizeImage
    //F_VN_ResizeImageExp
    //F_VN_RotateImage
    //F_VN_RotateImageExp
    //F_VN_RotateImageExp2
    //F_VN_WarpAffine
    //F_VN_WarpAffine_Container
    //F_VN_WarpAffine_Point
    //F_VN_WarpAffine_Rectangle
    //F_VN_WarpAffineExp
    //F_VN_WarpPerspective
    //F_VN_WarpPerspective_Container
    //F_VN_WarpPerspective_Point
    //F_VN_WarpPerspective_Rectangle
    //F_VN_WarpPerspectiveExp
    
    // Image Analysis
    //F_VN_AdjustActiveContour
    node_F_VN_DetectBlobs : Node_F_VN_DetectBlobs;
    //F_VN_DetectBlobsExp
    //F_VN_FindContourHierarchyExp
    //F_VN_FindContours
    //F_VN_FindContoursExp
    //F_VN_HoughCircles
    //F_VN_HoughCirclesExp
    //F_VN_HoughLines
    //F_VN_HoughLinesExp
    //F_VN_HoughLinesP
    //F_VN_HoughLinesPExp
    //F_VN_MatchImageHuMoments
    //F_VN_MatchTemplate
    //F_VN_MatchTemplateAndEvaluate
    //F_VN_MatchTemplateAndEvaluateExp
    //F_VN_MatchTemplateExp
    //F_VN_CannyEdgeDetection
    //F_VN_CannyEdgeDetectionExp
    //F_VN_ConnectedComponents
    //F_VN_ConnectedComponentsExp
    //F_VN_ConnectedComponentsWithStats
    //F_VN_ConnectedComponentsWithStatsExp
    //F_VN_CountNonZeroPixels
    //F_VN_DistanceTransformation
    //F_VN_DistanceTransformationExp
    //F_VN_GetConnectedComponent
    //F_VN_GetConnectedComponentExp
    //F_VN_ImageAverage
    //F_VN_ImageAverageExp
    //F_VN_ImageAverageStdDev
    //F_VN_ImageAverageStdDevExp
    //F_VN_ImageCenterOfMass
    //F_VN_ImageCenterOfMassExp
    //F_VN_ImageMedian
    //F_VN_ImageMedianExp
    //F_VN_ImageMoments
    //F_VN_MaxPixelValue
    //F_VN_MaxPixelValueExp
    //F_VN_MinPixelValue
    //F_VN_MinPixelValueExp
    //F_VN_RegionOrientation
    //F_VN_RegionOrientationExp
    
    // Image Color and Contrast Processing
    node_F_VN_ApplyColorMap : Node_F_VN_ApplyColorMap;
    //F_VN_ApplyLut
    //F_VN_Clahe
    //F_VN_ClaheExp
    node_F_VN_ConvertColorSpace : Node_F_VN_ConvertColorSpace;
    node_F_VN_GenerateColorMap : Node_F_VN_GenerateColorMap;
    //F_VN_GenerateCustomColorMap
    //F_VN_Histogram
    //F_VN_HistogramEqualization
    //F_VN_HistogramEqualizationExp
    //F_VN_HistogramExp
    //F_VN_InvertImageColor
    //F_VN_InvertImageColorExp
    //F_VN_NormalizeImage
    //F_VN_NormalizeImageExp
    //F_VN_NormalizeImageForDisplay
    //F_VN_ReferenceColorSimilarity_ITcVnColorModel
    //F_VN_ReferenceColorSimilarity_ITcVnMlModel
    //F_VN_ReferenceColorSimilarity_TcVnVector3_LREAL
    //F_VN_ReferenceColorSimilarityExp_ITcVnColorModel
    //F_VN_ReferenceColorSimilarityExp_ITcVnMlModel
    //F_VN_ReferenceColorSimilarityExp_TcVnVector3_LREAL
    //F_VN_TrainImageColor
    //F_VN_TrainImageColor_ITcVnMlModel
    //F_VN_TrainImageColorExp
    //F_VN_TrainImageColorExp_ITcVnMlModel
    //F_VN_TrainImageColorExp2
    //F_VN_TrainImageColorExp2_ITcVnMlModel
    //F_VN_WhiteBalance
    
    // Image Filtering
    //F_VN_BilateralFilter
    //F_VN_BilateralFilterExp
    node_F_VN_BoxFilter : Node_F_VN_BoxFilter;
    //F_VN_BoxFilterExp
    //F_VN_BrightBorderObjects
    //F_VN_CreateStructuringElement
    //F_VN_CustomFilter
    //F_VN_CustomFilterExp
    //F_VN_DarkBorderObjects
    //F_VN_FillHoles
    node_F_VN_GaussianFilter : Node_F_VN_GaussianFilter;
    //F_VN_GaussianFilterExp
    node_F_VN_LaplacianFilter : Node_F_VN_LaplacianFilter;
    //F_VN_LaplacianFilterExp
    //F_VN_LocalMaxima
    //F_VN_LocalMinima
    //F_VN_MedianFilter
    //F_VN_MorphologicalOperator
    //F_VN_RemoveLocalMaxima
    //F_VN_RemoveLocalMinima
    //F_VN_ScharrFilter
    //F_VN_ScharrFilterExp
    //F_VN_SeparableCustomFilter
    //F_VN_SeparableCustomFilterExp
    //F_VN_SobelFilter
    //F_VN_SobelFilterExp
    //F_VN_VarianceFilter
    //F_VN_VarianceFilterExp
    
    // Image Segmentation
    //F_VN_AdaptiveThreshold
    //F_VN_AdaptiveThresholdExp
    //F_VN_CheckColorRange
    //F_VN_DoubleThreshold
    node_F_VN_Threshold : Node_F_VN_Threshold;
    //F_VN_WatershedSegmentationExp
    
    // Keypoint Features
    //F_VN_FilterGoodMatches
    //F_VN_FindReferenceKeyPointsInImage
    //F_VN_FindReferenceKeyPointsInImageAKAZE
    //F_VN_FindReferenceKeyPointsInImageAKAZEExp
    //F_VN_FindReferenceKeyPointsInImageBRISK
    //F_VN_FindReferenceKeyPointsInImageBRISKExp
    //F_VN_FindReferenceKeyPointsInImageExp
    //F_VN_FindReferenceKeyPointsInImageORB
    //F_VN_FindReferenceKeyPointsInImageORBExp
    //F_VN_GetMatchCoordinates
    //F_VN_KeyPointsAGAST
    //F_VN_KeyPointsAGASTExp
    //F_VN_KeyPointsAndDescriptorsAKAZE
    //F_VN_KeyPointsAndDescriptorsAKAZEExp
    //F_VN_KeyPointsAndDescriptorsBRISK
    //F_VN_KeyPointsAndDescriptorsBRISKExp
    //F_VN_KeyPointsAndDescriptorsKAZE
    //F_VN_KeyPointsAndDescriptorsKAZEExp
    //F_VN_KeyPointsAndDescriptorsORB
    //F_VN_KeyPointsAndDescriptorsORBExp
    //F_VN_KeyPointsFAST
    //F_VN_KeyPointsFASTExp
    //F_VN_KeyPointsGFTT
    //F_VN_KeyPointsGFTTExp
    //F_VN_KeyPointsMSER
    //F_VN_KeyPointsMSERExp
    //F_VN_KeyPointsSB
    //F_VN_KeyPointsSBExp
    //F_VN_MatchDescriptorsBF
    //F_VN_MatchDescriptorsBFExp
    //F_VN_MatchDescriptorsFlannLsh
    //F_VN_MatchDescriptorsFlannLshExp
    //F_VN_MatchDescriptorsKnnBF
    //F_VN_MatchDescriptorsKnnBFExp
    //F_VN_MatchDescriptorsKnnFlannLsh
    //F_VN_MatchDescriptorsKnnFlannLshExp
    //F_VN_RegionsMSER
    //F_VN_RegionsMSERExp
    
    // Machine Learning
    //F_VN_CreateBoostClassifier
    //F_VN_CreateBoostClassifierExp
    //F_VN_CreateBoostClassifierExp2
    //F_VN_CreateKmppModel
    //F_VN_CreateKmppModelExp
    //F_VN_CreateKnnModel
    //F_VN_CreateLbgModel
    //F_VN_CreateLbgModelExp
    //F_VN_CreateLdaTransform
    //F_VN_CreateLdaTransformViaComponentNum
    //F_VN_CreateNbcModel
    //F_VN_CreatePcaTransform
    //F_VN_CreatePcaTransformViaComponentNum
    //F_VN_CreatePcaTransformViaVariance
    //F_VN_CreateRTreesModel
    //F_VN_CreateRTreesModelExp
    //F_VN_CreateRTreesModelExp2
    //F_VN_CreateStaModel
    //F_VN_CreateStaModelExp
    //F_VN_CreateStaModelExp2
    //F_VN_CreateSvmModel
    //F_VN_CreateSvmModelExp
    //F_VN_CreateSvmModelExp2
    //F_VN_CreateSvmSgdClassifier
    //F_VN_CreateSvmSgdClassifierExp
    //F_VN_FeatureScaling
    //F_VN_FeatureScalingExp
    //F_VN_FeatureTransform
    //F_VN_GetBatchClusters
    //F_VN_GetBatchClustersExp
    //F_VN_GetBatchNovelties
    //F_VN_GetClusterCenter
    //F_VN_GetClusterNum
    //F_VN_GetFeatureScales
    //F_VN_GetSampleCluster
    //F_VN_GetSampleClusterExp
    //F_VN_GetSampleNovelty
    //F_VN_InverseFeatureScaling
    //F_VN_InverseFeatureScaling_REAL
    //F_VN_InverseFeatureScalingExp
    //F_VN_InverseFeatureScalingExp_REAL
    //F_VN_InverseFeatureTransform
    //F_VN_PredictBatch
    //F_VN_PredictBatchExp
    //F_VN_PredictSampleClass
    //F_VN_PredictSampleClassExp
    //F_VN_PredictSampleScalar
    //F_VN_PredictSampleScalarExp
    //F_VN_PredictSampleVector
    //F_VN_PredictSampleVectorExp
    //F_VN_TrainBatch
    //F_VN_TrainBatchClusters
    //F_VN_TrainSample
    //F_VN_TrainSampleClass
    //F_VN_TrainSampleCluster
    //F_VN_TrainSampleScalar
    //F_VN_TrainSampleVector

    // Measurement
    //F_VN_AdjustSearchWindowOrientationToLinearEdge
    //F_VN_ClosestPointsBF
    //F_VN_LocateCircularArc
    //F_VN_LocateCircularArcExp
    node_F_VN_LocateEdge : Node_F_VN_LocateEdge;
    //F_VN_LocateEdgeExp
    //F_VN_LocateEdges
    //F_VN_LocateEdgesExp
    //F_VN_LocateEllipse
    //F_VN_LocateEllipseExp
    //F_VN_MeasureAngleBetweenEdges
    //F_VN_MeasureAngleBetweenEdgesExp
    //F_VN_MeasureEdgeDistance
    //F_VN_MeasureEdgeDistanceExp
    //F_VN_MeasureMinEdgeDistance
    //F_VN_MeasureMinEdgeDistanceExp
    
    // Miscellaneous
    //F_VN_CheckFunctionInitialization
    //F_VN_ClipLineToBoundary
    //F_VN_ClipLineToBoundary_ITcVnImage
    //F_VN_ClipLineToBoundary_TcVnRectangle_DINT
    //F_VN_ConvertITcUnknownToITcVnBitmapExport
    //F_VN_ConvertITcUnknownToITcVnContainer
    //F_VN_ConvertITcUnknownToITcVnImage
    //F_VN_ConvertITcUnknownToITcVnMlModel
    //F_VN_DeinitializeFunction
    //F_VN_GetTimestamp
    //F_VN_HuMomentInvariants
    //F_VN_InitMatrixStruct
    //F_VN_InvertMatrix3x3
    //F_VN_LineIntersectionPoint
    //F_VN_LineIntersectionPointAndAngle
    //F_VN_MultiplyMatrices
    //F_VN_RotatedRectangleCorners
    //F_VN_RotatedRectangleIntersection
    //F_VN_SetRngSeed
    //F_VN_UpdateTimestamp
    
    // OCR
    //F_VN_OCR
    //F_VN_OCRExp
    
    // Texture Analysis
    //F_VN_Granulometry
    //F_VN_HaralickFeatures
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="RegisterWithNodeFactory" Id="{9eda346d-cc38-44e9-a636-4948bc24f687}">
      <Declaration><![CDATA[METHOD PUBLIC RegisterWithNodeFactory
VAR_INPUT
	NodeFactory : I_NodeFactory;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Algebraic Container Operations

// Algebraic Image Operations
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseNotImage', node_F_VN_BitwiseNotImage);

// Basic Container Operations
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_DINT', node_F_VN_AppendToContainer_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_INT', node_F_VN_AppendToContainer_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ITcVnContainer', node_F_VN_AppendToContainer_ITcVnContainer);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ITcVnForwardIterator', node_F_VN_AppendToContainer_ITcVnForwardIterator);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ITcVnImage', node_F_VN_AppendToContainer_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_LREAL', node_F_VN_AppendToContainer_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_REAL', node_F_VN_AppendToContainer_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_SINT', node_F_VN_AppendToContainer_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnDMatch', node_F_VN_AppendToContainer_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnKeyPoint', node_F_VN_AppendToContainer_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint2_DINT', node_F_VN_AppendToContainer_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint2_LREAL', node_F_VN_AppendToContainer_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint2_REAL', node_F_VN_AppendToContainer_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint3_LREAL', node_F_VN_AppendToContainer_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint3_REAL', node_F_VN_AppendToContainer_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnRectangle_DINT', node_F_VN_AppendToContainer_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_DINT', node_F_VN_AppendToContainer_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_INT', node_F_VN_AppendToContainer_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_REAL', node_F_VN_AppendToContainer_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_SINT', node_F_VN_AppendToContainer_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_UINT', node_F_VN_AppendToContainer_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_USINT', node_F_VN_AppendToContainer_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_INT', node_F_VN_AppendToContainer_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_REAL', node_F_VN_AppendToContainer_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_SINT', node_F_VN_AppendToContainer_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_UINT', node_F_VN_AppendToContainer_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_USINT', node_F_VN_AppendToContainer_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_DINT', node_F_VN_AppendToContainer_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_INT', node_F_VN_AppendToContainer_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_LREAL', node_F_VN_AppendToContainer_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_SINT', node_F_VN_AppendToContainer_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_UINT', node_F_VN_AppendToContainer_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_USINT', node_F_VN_AppendToContainer_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_UDINT', node_F_VN_AppendToContainer_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_UINT', node_F_VN_AppendToContainer_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ULINT', node_F_VN_AppendToContainer_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_USINT', node_F_VN_AppendToContainer_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_DINT', node_F_VN_FillContainer_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_INT', node_F_VN_FillContainer_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_ITcVnImage', node_F_VN_FillContainer_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_LREAL', node_F_VN_FillContainer_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_REAL', node_F_VN_FillContainer_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_SINT', node_F_VN_FillContainer_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnDMatch', node_F_VN_FillContainer_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnKeyPoint', node_F_VN_FillContainer_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint2_DINT', node_F_VN_FillContainer_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint2_LREAL', node_F_VN_FillContainer_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint2_REAL', node_F_VN_FillContainer_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint3_LREAL', node_F_VN_FillContainer_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint3_REAL', node_F_VN_FillContainer_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnRectangle_DINT', node_F_VN_FillContainer_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_DINT', node_F_VN_FillContainer_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_INT', node_F_VN_FillContainer_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_REAL', node_F_VN_FillContainer_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_SINT', node_F_VN_FillContainer_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_UINT', node_F_VN_FillContainer_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_USINT', node_F_VN_FillContainer_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_INT', node_F_VN_FillContainer_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_REAL', node_F_VN_FillContainer_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_SINT', node_F_VN_FillContainer_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_UINT', node_F_VN_FillContainer_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_USINT', node_F_VN_FillContainer_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_DINT', node_F_VN_FillContainer_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_INT', node_F_VN_FillContainer_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_LREAL', node_F_VN_FillContainer_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_SINT', node_F_VN_FillContainer_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_UINT', node_F_VN_FillContainer_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_USINT', node_F_VN_FillContainer_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_UDINT', node_F_VN_FillContainer_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_UINT', node_F_VN_FillContainer_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_ULINT', node_F_VN_FillContainer_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_USINT', node_F_VN_FillContainer_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_DINT', node_F_VN_InsertIntoContainer_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_INT', node_F_VN_InsertIntoContainer_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ITcVnContainer', node_F_VN_InsertIntoContainer_ITcVnContainer);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ITcVnForwardIterator', node_F_VN_InsertIntoContainer_ITcVnForwardIterator);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ITcVnImage', node_F_VN_InsertIntoContainer_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_LREAL', node_F_VN_InsertIntoContainer_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_REAL', node_F_VN_InsertIntoContainer_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_SINT', node_F_VN_InsertIntoContainer_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnDMatch', node_F_VN_InsertIntoContainer_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnKeyPoint', node_F_VN_InsertIntoContainer_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint2_DINT', node_F_VN_InsertIntoContainer_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint2_LREAL', node_F_VN_InsertIntoContainer_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint2_REAL', node_F_VN_InsertIntoContainer_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint3_LREAL', node_F_VN_InsertIntoContainer_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint3_REAL', node_F_VN_InsertIntoContainer_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnRectangle_DINT', node_F_VN_InsertIntoContainer_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_DINT', node_F_VN_InsertIntoContainer_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_INT', node_F_VN_InsertIntoContainer_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_REAL', node_F_VN_InsertIntoContainer_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_SINT', node_F_VN_InsertIntoContainer_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_UINT', node_F_VN_InsertIntoContainer_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_USINT', node_F_VN_InsertIntoContainer_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_INT', node_F_VN_InsertIntoContainer_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_REAL', node_F_VN_InsertIntoContainer_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_SINT', node_F_VN_InsertIntoContainer_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_UINT', node_F_VN_InsertIntoContainer_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_USINT', node_F_VN_InsertIntoContainer_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_DINT', node_F_VN_InsertIntoContainer_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_INT', node_F_VN_InsertIntoContainer_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_LREAL', node_F_VN_InsertIntoContainer_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_SINT', node_F_VN_InsertIntoContainer_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_UINT', node_F_VN_InsertIntoContainer_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_USINT', node_F_VN_InsertIntoContainer_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_UDINT', node_F_VN_InsertIntoContainer_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_UINT', node_F_VN_InsertIntoContainer_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ULINT', node_F_VN_InsertIntoContainer_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_USINT', node_F_VN_InsertIntoContainer_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_DINT', node_F_VN_SetAt_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_INT', node_F_VN_SetAt_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_ITcVnContainer', node_F_VN_SetAt_ITcVnContainer);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_ITcVnImage', node_F_VN_SetAt_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_LREAL', node_F_VN_SetAt_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_REAL', node_F_VN_SetAt_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_SINT', node_F_VN_SetAt_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnDMatch', node_F_VN_SetAt_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnKeyPoint', node_F_VN_SetAt_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint2_DINT', node_F_VN_SetAt_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint2_LREAL', node_F_VN_SetAt_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint2_REAL', node_F_VN_SetAt_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint3_LREAL', node_F_VN_SetAt_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint3_REAL', node_F_VN_SetAt_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnRectangle_DINT', node_F_VN_SetAt_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_DINT', node_F_VN_SetAt_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_INT', node_F_VN_SetAt_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_REAL', node_F_VN_SetAt_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_SINT', node_F_VN_SetAt_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_UINT', node_F_VN_SetAt_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_USINT', node_F_VN_SetAt_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_INT', node_F_VN_SetAt_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_REAL', node_F_VN_SetAt_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_SINT', node_F_VN_SetAt_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_UINT', node_F_VN_SetAt_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_USINT', node_F_VN_SetAt_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_DINT', node_F_VN_SetAt_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_INT', node_F_VN_SetAt_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_LREAL', node_F_VN_SetAt_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_SINT', node_F_VN_SetAt_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_UINT', node_F_VN_SetAt_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_USINT', node_F_VN_SetAt_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_UDINT', node_F_VN_SetAt_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_UINT', node_F_VN_SetAt_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_ULINT', node_F_VN_SetAt_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_USINT', node_F_VN_SetAt_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetNumberOfElements', node_F_VN_GetNumberOfElements);

// Basic Image Operations
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CopyImage', node_F_VN_CopyImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageChannel', node_F_VN_GetImageChannel);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageHeight', node_F_VN_GetImageHeight);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageInfo', node_F_VN_GetImageInfo);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageWidth', node_F_VN_GetImageWidth);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetPixelFormat', node_F_VN_GetPixelFormat);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetRoi', node_F_VN_SetRoi);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetRoi_TcVnRectangle_DINT', node_F_VN_SetRoi_TcVnRectangle_DINT);
 
// Code Quality

// Code Reading

// Constants
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_BLACK', node_RGBA_BLACK);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_RED', node_RGBA_RED);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_YELLOW', node_RGBA_YELLOW);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_GREEN', node_RGBA_GREEN);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_CYAN', node_RGBA_CYAN);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_BLUE', node_RGBA_BLUE);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_MAGENTA', node_RGBA_MAGENTA);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_WHITE', node_RGBA_WHITE);

// Container Statistics

// Contour Analysis
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_FitLine', node_F_VN_FitLine);

// Control Functions
    
// Drawing
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawContours', node_F_VN_DrawContours);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLine', node_F_VN_DrawLine);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLine_TcVnVector4_LREAL', node_F_VN_DrawLine_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PutLabel', node_F_VN_PutLabel);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PutText', node_F_VN_PutText);

// Fourier Analysis

// Geometric and Coordinate Transformations
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_FlipImage', node_F_VN_FlipImage);

// Image Analysis
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/Object Detection/F_VN_DetectBlobs', node_F_VN_DetectBlobs);

// Image Color and Contrast Processing
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_ApplyColorMap', node_F_VN_ApplyColorMap);
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_ConvertColorSpace', node_F_VN_ConvertColorSpace);
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_GenerateColorMap', node_F_VN_GenerateColorMap);

// Image Filtering
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_BoxFilter', node_F_VN_BoxFilter);
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_GaussianFilter', node_F_VN_GaussianFilter);
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_LaplacianFilter', node_F_VN_LaplacianFilter);
    
// Image Segmentation
NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_Threshold', node_F_VN_Threshold);

// Keypoint Features

// Machine Learning

// Measurement
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_LocateEdge', node_F_VN_LocateEdge);

// Miscellaneous

// OCR

// Texture Analysis
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>