<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="VisionNodePack" Id="{257fc325-f932-4b89-a50a-e9a0a38418f4}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK VisionNodePack IMPLEMENTS I_NodePack
VAR
    // Algebraic Container Operations
    node_F_VN_AddToContainerElements_DINT : Node_F_VN_AddToContainerElements_DINT;
    node_F_VN_AddToContainerElements_INT : Node_F_VN_AddToContainerElements_INT;
    node_F_VN_AddToContainerElements_LREAL : Node_F_VN_AddToContainerElements_LREAL;
    node_F_VN_AddToContainerElements_REAL : Node_F_VN_AddToContainerElements_REAL;
    node_F_VN_AddToContainerElements_SINT : Node_F_VN_AddToContainerElements_SINT;
    node_F_VN_AddToContainerElements_TcVnKeyPoint : Node_F_VN_AddToContainerElements_TcVnKeyPoint;
    node_F_VN_AddToContainerElements_TcVnPoint2_DINT : Node_F_VN_AddToContainerElements_TcVnPoint2_DINT;
    node_F_VN_AddToContainerElements_TcVnPoint2_LREAL : Node_F_VN_AddToContainerElements_TcVnPoint2_LREAL;
    node_F_VN_AddToContainerElements_TcVnPoint2_REAL : Node_F_VN_AddToContainerElements_TcVnPoint2_REAL;
    node_F_VN_AddToContainerElements_TcVnPoint3_LREAL : Node_F_VN_AddToContainerElements_TcVnPoint3_LREAL;
    node_F_VN_AddToContainerElements_TcVnPoint3_REAL : Node_F_VN_AddToContainerElements_TcVnPoint3_REAL;
    node_F_VN_AddToContainerElements_TcVnRectangle_DINT : Node_F_VN_AddToContainerElements_TcVnRectangle_DINT;
    node_F_VN_AddToContainerElements_TcVnVector2_DINT : Node_F_VN_AddToContainerElements_TcVnVector2_DINT;
    node_F_VN_AddToContainerElements_TcVnVector2_INT : Node_F_VN_AddToContainerElements_TcVnVector2_INT;
    node_F_VN_AddToContainerElements_TcVnVector2_REAL : Node_F_VN_AddToContainerElements_TcVnVector2_REAL;
    node_F_VN_AddToContainerElements_TcVnVector2_SINT : Node_F_VN_AddToContainerElements_TcVnVector2_SINT;
    node_F_VN_AddToContainerElements_TcVnVector2_UINT : Node_F_VN_AddToContainerElements_TcVnVector2_UINT;
    node_F_VN_AddToContainerElements_TcVnVector2_USINT : Node_F_VN_AddToContainerElements_TcVnVector2_USINT;
    node_F_VN_AddToContainerElements_TcVnVector3_INT : Node_F_VN_AddToContainerElements_TcVnVector3_INT;
    node_F_VN_AddToContainerElements_TcVnVector3_REAL : Node_F_VN_AddToContainerElements_TcVnVector3_REAL;
    node_F_VN_AddToContainerElements_TcVnVector3_SINT : Node_F_VN_AddToContainerElements_TcVnVector3_SINT;
    node_F_VN_AddToContainerElements_TcVnVector3_UINT : Node_F_VN_AddToContainerElements_TcVnVector3_UINT;
    node_F_VN_AddToContainerElements_TcVnVector3_USINT : Node_F_VN_AddToContainerElements_TcVnVector3_USINT;
    node_F_VN_AddToContainerElements_TcVnVector4_DINT : Node_F_VN_AddToContainerElements_TcVnVector4_DINT;
    node_F_VN_AddToContainerElements_TcVnVector4_INT : Node_F_VN_AddToContainerElements_TcVnVector4_INT;
    node_F_VN_AddToContainerElements_TcVnVector4_LREAL : Node_F_VN_AddToContainerElements_TcVnVector4_LREAL;
    node_F_VN_AddToContainerElements_TcVnVector4_SINT : Node_F_VN_AddToContainerElements_TcVnVector4_SINT;
    node_F_VN_AddToContainerElements_TcVnVector4_UINT : Node_F_VN_AddToContainerElements_TcVnVector4_UINT;
    node_F_VN_AddToContainerElements_TcVnVector4_USINT : Node_F_VN_AddToContainerElements_TcVnVector4_USINT;
    node_F_VN_AddToContainerElements_UDINT : Node_F_VN_AddToContainerElements_UDINT;
    node_F_VN_AddToContainerElements_UINT : node_F_VN_AddToContainerElements_UINT;
    node_F_VN_AddToContainerElements_ULINT : Node_F_VN_AddToContainerElements_ULINT;
    node_F_VN_AddToContainerElements_USINT : Node_F_VN_AddToContainerElements_USINT;
    node_F_VN_AddContainers : Node_F_VN_AddContainers;
    //F_VN_BitwiseAndContainers
    //F_VN_BitwiseNotContainer
    //F_VN_BitwiseOrContainers
    //F_VN_BitwiseXorContainers
    node_F_VN_DivideContainers : Node_F_VN_DivideContainers;
    node_F_VN_DivideContainersExp : Node_F_VN_DivideContainersExp;
    node_F_VN_MaxContainer : Node_F_VN_MaxContainer;
    node_F_VN_MinContainer : Node_F_VN_MinContainer;
    node_F_VN_MultiplyContainers : Node_F_VN_MultiplyContainers;
    //F_VN_MultiplyWithContainerElements1
    //F_VN_MultiplyWithContainerElements2
    //F_VN_MultiplyWithContainerElements3
    //F_VN_MultiplyWithContainerElements4
    //F_VN_NegateContainer
    node_F_VN_SubtractContainers : Node_F_VN_SubtractContainers;
   
    // Algebraic Image Operations
    node_F_VN_AddImages : Node_F_VN_AddImages;
    node_F_VN_AddImagesWeighted : Node_F_VN_AddImagesWeighted;
    node_F_VN_AddImagesWeightedExp : Node_F_VN_AddImagesWeightedExp;
    node_F_VN_AddScalarToImage : Node_F_VN_AddScalarToImage;
    node_F_VN_AddVectorToImage : Node_F_VN_AddVectorToImage;
    node_F_VN_BitwiseAndImages : Node_F_VN_BitwiseAndImages;
    node_F_VN_BitwiseAndImagesExp : Node_F_VN_BitwiseAndImagesExp;
    node_F_VN_BitwiseAndScalarWithImage : Node_F_VN_BitwiseAndScalarWithImage;
    node_F_VN_BitwiseAndVectorWithImage : Node_F_VN_BitwiseAndVectorWithImage;
    node_F_VN_BitwiseNotImage : Node_F_VN_BitwiseNotImage;
    node_F_VN_BitwiseNotImageExp : Node_F_VN_BitwiseNotImageExp;
    node_F_VN_BitwiseOrImages : Node_F_VN_BitwiseOrImages;
    node_F_VN_BitwiseOrImagesExp : Node_F_VN_BitwiseOrImagesExp;
    node_F_VN_BitwiseOrScalarWithImage : Node_F_VN_BitwiseOrScalarWithImage;
    node_F_VN_BitwiseOrVectorWithImage : Node_F_VN_BitwiseOrVectorWithImage;
    node_F_VN_BitwiseXorImages : Node_F_VN_BitwiseXorImages;
    node_F_VN_BitwiseXorImagesExp : Node_F_VN_BitwiseXorImagesExp;
    node_F_VN_BitwiseXorScalarWithImage : Node_F_VN_BitwiseXorScalarWithImage;
    node_F_VN_BitwiseXorVectorWithImage : Node_F_VN_BitwiseXorVectorWithImage;
    //node_F_VN_BlendImages : Node_F_VN_BlendImages;
    node_F_VN_DivideImageByScalar : Node_F_VN_DivideImageByScalar;
    node_F_VN_DivideImageByVector : Node_F_VN_DivideImageByVector;
    node_F_VN_DivideImages : Node_F_VN_DivideImages;
    node_F_VN_DivideScalarByImage : Node_F_VN_DivideScalarByImage;
    node_F_VN_DivideVectorByImage : Node_F_VN_DivideVectorByImage;
    node_F_VN_ElementwiseExp : Node_F_VN_ElementwiseExp;
    node_F_VN_ElementwiseLog : Node_F_VN_ElementwiseLog;
    node_F_VN_MaxImage : Node_F_VN_MaxImage;
    node_F_VN_MaxImageExp : Node_F_VN_MaxImageExp;
    node_F_VN_MaxImageWithScalar : Node_F_VN_MaxImageWithScalar;
    node_F_VN_MaxImageWithScalarExp : Node_F_VN_MaxImageWithScalarExp;
    node_F_VN_MaxImageWithVector : Node_F_VN_MaxImageWithVector;
    node_F_VN_MaxImageWithVectorExp : Node_F_VN_MaxImageWithVectorExp;
    node_F_VN_MinImage : Node_F_VN_MinImage;
    node_F_VN_MinImageExp : Node_F_VN_MinImageExp;
    node_F_VN_MinImageWithScalar : Node_F_VN_MinImageWithScalar;
    node_F_VN_MinImageWithScalarExp : Node_F_VN_MinImageWithScalarExp;
    node_F_VN_MinImageWithVector : Node_F_VN_MinImageWithVector;
    node_F_VN_MinImageWithVectorExp : Node_F_VN_MinImageWithVectorExp;
    node_F_VN_MultiplyImages : Node_F_VN_MultiplyImages;
    node_F_VN_MultiplyImageWithScalar : Node_F_VN_MultiplyImageWithScalar;
    node_F_VN_MultiplyImageWithVector : Node_F_VN_MultiplyImageWithVector;
    node_F_VN_SubtractImageFromScalar : Node_F_VN_SubtractImageFromScalar;
    node_F_VN_SubtractImageFromVector : Node_F_VN_SubtractImageFromVector;
    node_F_VN_SubtractImages : Node_F_VN_SubtractImages;
    node_F_VN_SubtractScalarFromImage : Node_F_VN_SubtractScalarFromImage;
    node_F_VN_SubtractVectorFromImage : Node_F_VN_SubtractVectorFromImage;
        
    // Basic Container Operations
    node_F_VN_AppendToContainer_DINT : Node_F_VN_AppendToContainer_DINT;
    node_F_VN_AppendToContainer_INT : Node_F_VN_AppendToContainer_INT;
    node_F_VN_AppendToContainer_ITcVnContainer : Node_F_VN_AppendToContainer_ITcVnContainer;
    //node_F_VN_AppendToContainer_ITcVnForwardIterator : Node_F_VN_AppendToContainer_ITcVnForwardIterator;
    node_F_VN_AppendToContainer_ITcVnImage : Node_F_VN_AppendToContainer_ITcVnImage;
    node_F_VN_AppendToContainer_LREAL : Node_F_VN_AppendToContainer_LREAL;
    node_F_VN_AppendToContainer_REAL : Node_F_VN_AppendToContainer_REAL;
    node_F_VN_AppendToContainer_SINT : Node_F_VN_AppendToContainer_SINT;
    node_F_VN_AppendToContainer_TcVnDMatch : Node_F_VN_AppendToContainer_TcVnDMatch;
    node_F_VN_AppendToContainer_TcVnKeyPoint : Node_F_VN_AppendToContainer_TcVnKeyPoint;
    node_F_VN_AppendToContainer_TcVnPoint2_DINT : Node_F_VN_AppendToContainer_TcVnPoint2_DINT;
    node_F_VN_AppendToContainer_TcVnPoint2_LREAL : Node_F_VN_AppendToContainer_TcVnPoint2_LREAL;
    node_F_VN_AppendToContainer_TcVnPoint2_REAL : Node_F_VN_AppendToContainer_TcVnPoint2_REAL;
    node_F_VN_AppendToContainer_TcVnPoint3_LREAL : Node_F_VN_AppendToContainer_TcVnPoint3_LREAL;
    node_F_VN_AppendToContainer_TcVnPoint3_REAL : Node_F_VN_AppendToContainer_TcVnPoint3_REAL;
    node_F_VN_AppendToContainer_TcVnRectangle_DINT : Node_F_VN_AppendToContainer_TcVnRectangle_DINT;
    node_F_VN_AppendToContainer_TcVnVector2_DINT : Node_F_VN_AppendToContainer_TcVnVector2_DINT;
    node_F_VN_AppendToContainer_TcVnVector2_INT : Node_F_VN_AppendToContainer_TcVnVector2_INT;
    node_F_VN_AppendToContainer_TcVnVector2_REAL : Node_F_VN_AppendToContainer_TcVnVector2_REAL;
    node_F_VN_AppendToContainer_TcVnVector2_SINT : Node_F_VN_AppendToContainer_TcVnVector2_SINT;
    node_F_VN_AppendToContainer_TcVnVector2_UINT : Node_F_VN_AppendToContainer_TcVnVector2_UINT;
    node_F_VN_AppendToContainer_TcVnVector2_USINT : Node_F_VN_AppendToContainer_TcVnVector2_USINT;
    node_F_VN_AppendToContainer_TcVnVector3_INT : Node_F_VN_AppendToContainer_TcVnVector3_INT;
    node_F_VN_AppendToContainer_TcVnVector3_REAL : Node_F_VN_AppendToContainer_TcVnVector3_REAL;
    node_F_VN_AppendToContainer_TcVnVector3_SINT : Node_F_VN_AppendToContainer_TcVnVector3_SINT;
    node_F_VN_AppendToContainer_TcVnVector3_UINT : Node_F_VN_AppendToContainer_TcVnVector3_UINT;
    node_F_VN_AppendToContainer_TcVnVector3_USINT : Node_F_VN_AppendToContainer_TcVnVector3_USINT;
    node_F_VN_AppendToContainer_TcVnVector4_DINT : Node_F_VN_AppendToContainer_TcVnVector4_DINT;
    node_F_VN_AppendToContainer_TcVnVector4_INT : Node_F_VN_AppendToContainer_TcVnVector4_INT;
    node_F_VN_AppendToContainer_TcVnVector4_LREAL : Node_F_VN_AppendToContainer_TcVnVector4_LREAL;
    node_F_VN_AppendToContainer_TcVnVector4_SINT : Node_F_VN_AppendToContainer_TcVnVector4_SINT;
    node_F_VN_AppendToContainer_TcVnVector4_UINT : Node_F_VN_AppendToContainer_TcVnVector4_UINT;
    node_F_VN_AppendToContainer_TcVnVector4_USINT : Node_F_VN_AppendToContainer_TcVnVector4_USINT;
    node_F_VN_AppendToContainer_UDINT : Node_F_VN_AppendToContainer_UDINT;
    node_F_VN_AppendToContainer_UINT : node_F_VN_AppendToContainer_UINT;
    node_F_VN_AppendToContainer_ULINT : Node_F_VN_AppendToContainer_ULINT;
    node_F_VN_AppendToContainer_USINT : Node_F_VN_AppendToContainer_USINT;
    
    node_F_VN_FillContainer_DINT : Node_F_VN_FillContainer_DINT;
    node_F_VN_FillContainer_INT : Node_F_VN_FillContainer_INT;
    node_F_VN_FillContainer_ITcVnImage : Node_F_VN_FillContainer_ITcVnImage;
    node_F_VN_FillContainer_LREAL : Node_F_VN_FillContainer_LREAL;
    node_F_VN_FillContainer_REAL : Node_F_VN_FillContainer_REAL;
    node_F_VN_FillContainer_SINT : Node_F_VN_FillContainer_SINT;
    node_F_VN_FillContainer_TcVnDMatch : Node_F_VN_FillContainer_TcVnDMatch;
    node_F_VN_FillContainer_TcVnKeyPoint : Node_F_VN_FillContainer_TcVnKeyPoint;
    node_F_VN_FillContainer_TcVnPoint2_DINT : Node_F_VN_FillContainer_TcVnPoint2_DINT;
    node_F_VN_FillContainer_TcVnPoint2_LREAL : Node_F_VN_FillContainer_TcVnPoint2_LREAL;
    node_F_VN_FillContainer_TcVnPoint2_REAL : Node_F_VN_FillContainer_TcVnPoint2_REAL;
    node_F_VN_FillContainer_TcVnPoint3_LREAL : Node_F_VN_FillContainer_TcVnPoint3_LREAL;
    node_F_VN_FillContainer_TcVnPoint3_REAL : Node_F_VN_FillContainer_TcVnPoint3_REAL;
    node_F_VN_FillContainer_TcVnRectangle_DINT : Node_F_VN_FillContainer_TcVnRectangle_DINT;
    node_F_VN_FillContainer_TcVnVector2_DINT : Node_F_VN_FillContainer_TcVnVector2_DINT;
    node_F_VN_FillContainer_TcVnVector2_INT : Node_F_VN_FillContainer_TcVnVector2_INT;
    node_F_VN_FillContainer_TcVnVector2_REAL : Node_F_VN_FillContainer_TcVnVector2_REAL;
    node_F_VN_FillContainer_TcVnVector2_SINT : Node_F_VN_FillContainer_TcVnVector2_SINT;
    node_F_VN_FillContainer_TcVnVector2_UINT : Node_F_VN_FillContainer_TcVnVector2_UINT;
    node_F_VN_FillContainer_TcVnVector2_USINT : Node_F_VN_FillContainer_TcVnVector2_USINT;
    node_F_VN_FillContainer_TcVnVector3_INT : Node_F_VN_FillContainer_TcVnVector3_INT;
    node_F_VN_FillContainer_TcVnVector3_REAL : Node_F_VN_FillContainer_TcVnVector3_REAL;
    node_F_VN_FillContainer_TcVnVector3_SINT : Node_F_VN_FillContainer_TcVnVector3_SINT;
    node_F_VN_FillContainer_TcVnVector3_UINT : Node_F_VN_FillContainer_TcVnVector3_UINT;
    node_F_VN_FillContainer_TcVnVector3_USINT : Node_F_VN_FillContainer_TcVnVector3_USINT;
    node_F_VN_FillContainer_TcVnVector4_DINT : Node_F_VN_FillContainer_TcVnVector4_DINT;
    node_F_VN_FillContainer_TcVnVector4_INT : Node_F_VN_FillContainer_TcVnVector4_INT;
    node_F_VN_FillContainer_TcVnVector4_LREAL : Node_F_VN_FillContainer_TcVnVector4_LREAL;
    node_F_VN_FillContainer_TcVnVector4_SINT : Node_F_VN_FillContainer_TcVnVector4_SINT;
    node_F_VN_FillContainer_TcVnVector4_UINT : Node_F_VN_FillContainer_TcVnVector4_UINT;
    node_F_VN_FillContainer_TcVnVector4_USINT : Node_F_VN_FillContainer_TcVnVector4_USINT;
    node_F_VN_FillContainer_UDINT : Node_F_VN_FillContainer_UDINT;
    node_F_VN_FillContainer_UINT : node_F_VN_FillContainer_UINT;
    node_F_VN_FillContainer_ULINT : Node_F_VN_FillContainer_ULINT;
    node_F_VN_FillContainer_USINT : Node_F_VN_FillContainer_USINT;
    
    node_F_VN_FillContainerExp_DINT : Node_F_VN_FillContainerExp_DINT;
    node_F_VN_FillContainerExp_INT : Node_F_VN_FillContainerExp_INT;
    node_F_VN_FillContainerExp_ITcVnImage : Node_F_VN_FillContainerExp_ITcVnImage;
    node_F_VN_FillContainerExp_LREAL : Node_F_VN_FillContainerExp_LREAL;
    node_F_VN_FillContainerExp_REAL : Node_F_VN_FillContainerExp_REAL;
    node_F_VN_FillContainerExp_SINT : Node_F_VN_FillContainerExp_SINT;
    node_F_VN_FillContainerExp_TcVnDMatch : Node_F_VN_FillContainerExp_TcVnDMatch;
    node_F_VN_FillContainerExp_TcVnKeyPoint : Node_F_VN_FillContainerExp_TcVnKeyPoint;
    node_F_VN_FillContainerExp_TcVnPoint2_DINT : Node_F_VN_FillContainerExp_TcVnPoint2_DINT;
    node_F_VN_FillContainerExp_TcVnPoint2_LREAL : Node_F_VN_FillContainerExp_TcVnPoint2_LREAL;
    node_F_VN_FillContainerExp_TcVnPoint2_REAL : Node_F_VN_FillContainerExp_TcVnPoint2_REAL;
    node_F_VN_FillContainerExp_TcVnPoint3_LREAL : Node_F_VN_FillContainerExp_TcVnPoint3_LREAL;
    node_F_VN_FillContainerExp_TcVnPoint3_REAL : Node_F_VN_FillContainerExp_TcVnPoint3_REAL;
    node_F_VN_FillContainerExp_TcVnRectangle_DINT : Node_F_VN_FillContainerExp_TcVnRectangle_DINT;
    node_F_VN_FillContainerExp_TcVnVector2_DINT : Node_F_VN_FillContainerExp_TcVnVector2_DINT;
    node_F_VN_FillContainerExp_TcVnVector2_INT : Node_F_VN_FillContainerExp_TcVnVector2_INT;
    node_F_VN_FillContainerExp_TcVnVector2_REAL : Node_F_VN_FillContainerExp_TcVnVector2_REAL;
    node_F_VN_FillContainerExp_TcVnVector2_SINT : Node_F_VN_FillContainerExp_TcVnVector2_SINT;
    node_F_VN_FillContainerExp_TcVnVector2_UINT : Node_F_VN_FillContainerExp_TcVnVector2_UINT;
    node_F_VN_FillContainerExp_TcVnVector2_USINT : Node_F_VN_FillContainerExp_TcVnVector2_USINT;
    node_F_VN_FillContainerExp_TcVnVector3_INT : Node_F_VN_FillContainerExp_TcVnVector3_INT;
    node_F_VN_FillContainerExp_TcVnVector3_REAL : Node_F_VN_FillContainerExp_TcVnVector3_REAL;
    node_F_VN_FillContainerExp_TcVnVector3_SINT : Node_F_VN_FillContainerExp_TcVnVector3_SINT;
    node_F_VN_FillContainerExp_TcVnVector3_UINT : Node_F_VN_FillContainerExp_TcVnVector3_UINT;
    node_F_VN_FillContainerExp_TcVnVector3_USINT : Node_F_VN_FillContainerExp_TcVnVector3_USINT;
    node_F_VN_FillContainerExp_TcVnVector4_DINT : Node_F_VN_FillContainerExp_TcVnVector4_DINT;
    node_F_VN_FillContainerExp_TcVnVector4_INT : Node_F_VN_FillContainerExp_TcVnVector4_INT;
    node_F_VN_FillContainerExp_TcVnVector4_LREAL : Node_F_VN_FillContainerExp_TcVnVector4_LREAL;
    node_F_VN_FillContainerExp_TcVnVector4_SINT : Node_F_VN_FillContainerExp_TcVnVector4_SINT;
    node_F_VN_FillContainerExp_TcVnVector4_UINT : Node_F_VN_FillContainerExp_TcVnVector4_UINT;
    node_F_VN_FillContainerExp_TcVnVector4_USINT : Node_F_VN_FillContainerExp_TcVnVector4_USINT;
    node_F_VN_FillContainerExp_UDINT : Node_F_VN_FillContainerExp_UDINT;
    node_F_VN_FillContainerExp_UINT : node_F_VN_FillContainerExp_UINT;
    node_F_VN_FillContainerExp_ULINT : Node_F_VN_FillContainerExp_ULINT;
    node_F_VN_FillContainerExp_USINT : Node_F_VN_FillContainerExp_USINT;
    
    node_F_VN_GetAt_DINT : Node_F_VN_GetAt_DINT;
    node_F_VN_GetAt_INT : Node_F_VN_GetAt_INT;
    node_F_VN_GetAt_ITcVnContainer : Node_F_VN_GetAt_ITcVnContainer;
    node_F_VN_GetAt_ITcVnImage : Node_F_VN_GetAt_ITcVnImage;
    node_F_VN_GetAt_LREAL : Node_F_VN_GetAt_LREAL;
    node_F_VN_GetAt_REAL : Node_F_VN_GetAt_REAL;
    node_F_VN_GetAt_SINT : Node_F_VN_GetAt_SINT;
    node_F_VN_GetAt_TcVnDMatch : Node_F_VN_GetAt_TcVnDMatch;
    node_F_VN_GetAt_TcVnKeyPoint : Node_F_VN_GetAt_TcVnKeyPoint;
    node_F_VN_GetAt_TcVnPoint2_DINT : Node_F_VN_GetAt_TcVnPoint2_DINT;
    node_F_VN_GetAt_TcVnPoint2_LREAL : Node_F_VN_GetAt_TcVnPoint2_LREAL;
    node_F_VN_GetAt_TcVnPoint2_REAL : Node_F_VN_GetAt_TcVnPoint2_REAL;
    node_F_VN_GetAt_TcVnPoint3_LREAL : Node_F_VN_GetAt_TcVnPoint3_LREAL;
    node_F_VN_GetAt_TcVnPoint3_REAL : Node_F_VN_GetAt_TcVnPoint3_REAL;
    node_F_VN_GetAt_TcVnRectangle_DINT : Node_F_VN_GetAt_TcVnRectangle_DINT;
    node_F_VN_GetAt_TcVnVector2_DINT : Node_F_VN_GetAt_TcVnVector2_DINT;
    node_F_VN_GetAt_TcVnVector2_INT : Node_F_VN_GetAt_TcVnVector2_INT;
    node_F_VN_GetAt_TcVnVector2_REAL : Node_F_VN_GetAt_TcVnVector2_REAL;
    node_F_VN_GetAt_TcVnVector2_SINT : Node_F_VN_GetAt_TcVnVector2_SINT;
    node_F_VN_GetAt_TcVnVector2_UINT : Node_F_VN_GetAt_TcVnVector2_UINT;
    node_F_VN_GetAt_TcVnVector2_USINT : Node_F_VN_GetAt_TcVnVector2_USINT;
    node_F_VN_GetAt_TcVnVector3_INT : Node_F_VN_GetAt_TcVnVector3_INT;
    node_F_VN_GetAt_TcVnVector3_REAL : Node_F_VN_GetAt_TcVnVector3_REAL;
    node_F_VN_GetAt_TcVnVector3_SINT : Node_F_VN_GetAt_TcVnVector3_SINT;
    node_F_VN_GetAt_TcVnVector3_UINT : Node_F_VN_GetAt_TcVnVector3_UINT;
    node_F_VN_GetAt_TcVnVector3_USINT : Node_F_VN_GetAt_TcVnVector3_USINT;
    node_F_VN_GetAt_TcVnVector4_DINT : Node_F_VN_GetAt_TcVnVector4_DINT;
    node_F_VN_GetAt_TcVnVector4_INT : Node_F_VN_GetAt_TcVnVector4_INT;
    node_F_VN_GetAt_TcVnVector4_LREAL : Node_F_VN_GetAt_TcVnVector4_LREAL;
    node_F_VN_GetAt_TcVnVector4_SINT : Node_F_VN_GetAt_TcVnVector4_SINT;
    node_F_VN_GetAt_TcVnVector4_UINT : Node_F_VN_GetAt_TcVnVector4_UINT;
    node_F_VN_GetAt_TcVnVector4_USINT : Node_F_VN_GetAt_TcVnVector4_USINT;
    node_F_VN_GetAt_UDINT : Node_F_VN_GetAt_UDINT;
    node_F_VN_GetAt_UINT : node_F_VN_GetAt_UINT;
    node_F_VN_GetAt_ULINT : Node_F_VN_GetAt_ULINT;
    node_F_VN_GetAt_USINT : Node_F_VN_GetAt_USINT;
    
    node_F_VN_InsertIntoContainer_DINT : Node_F_VN_InsertIntoContainer_DINT;
    node_F_VN_InsertIntoContainer_INT : Node_F_VN_InsertIntoContainer_INT;
    node_F_VN_InsertIntoContainer_ITcVnContainer : Node_F_VN_InsertIntoContainer_ITcVnContainer;
    //node_F_VN_InsertIntoContainer_ITcVnForwardIterator : Node_F_VN_InsertIntoContainer_ITcVnForwardIterator;
    node_F_VN_InsertIntoContainer_ITcVnImage : Node_F_VN_InsertIntoContainer_ITcVnImage;
    node_F_VN_InsertIntoContainer_LREAL : Node_F_VN_InsertIntoContainer_LREAL;
    node_F_VN_InsertIntoContainer_REAL : Node_F_VN_InsertIntoContainer_REAL;
    node_F_VN_InsertIntoContainer_SINT : Node_F_VN_InsertIntoContainer_SINT;
    node_F_VN_InsertIntoContainer_TcVnDMatch : Node_F_VN_InsertIntoContainer_TcVnDMatch;
    node_F_VN_InsertIntoContainer_TcVnKeyPoint : Node_F_VN_InsertIntoContainer_TcVnKeyPoint;
    node_F_VN_InsertIntoContainer_TcVnPoint2_DINT : Node_F_VN_InsertIntoContainer_TcVnPoint2_DINT;
    node_F_VN_InsertIntoContainer_TcVnPoint2_LREAL : Node_F_VN_InsertIntoContainer_TcVnPoint2_LREAL;
    node_F_VN_InsertIntoContainer_TcVnPoint2_REAL : Node_F_VN_InsertIntoContainer_TcVnPoint2_REAL;
    node_F_VN_InsertIntoContainer_TcVnPoint3_LREAL : Node_F_VN_InsertIntoContainer_TcVnPoint3_LREAL;
    node_F_VN_InsertIntoContainer_TcVnPoint3_REAL : Node_F_VN_InsertIntoContainer_TcVnPoint3_REAL;
    node_F_VN_InsertIntoContainer_TcVnRectangle_DINT : Node_F_VN_InsertIntoContainer_TcVnRectangle_DINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_DINT : Node_F_VN_InsertIntoContainer_TcVnVector2_DINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_INT : Node_F_VN_InsertIntoContainer_TcVnVector2_INT;
    node_F_VN_InsertIntoContainer_TcVnVector2_REAL : Node_F_VN_InsertIntoContainer_TcVnVector2_REAL;
    node_F_VN_InsertIntoContainer_TcVnVector2_SINT : Node_F_VN_InsertIntoContainer_TcVnVector2_SINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_UINT : Node_F_VN_InsertIntoContainer_TcVnVector2_UINT;
    node_F_VN_InsertIntoContainer_TcVnVector2_USINT : Node_F_VN_InsertIntoContainer_TcVnVector2_USINT;
    node_F_VN_InsertIntoContainer_TcVnVector3_INT : Node_F_VN_InsertIntoContainer_TcVnVector3_INT;
    node_F_VN_InsertIntoContainer_TcVnVector3_REAL : Node_F_VN_InsertIntoContainer_TcVnVector3_REAL;
    node_F_VN_InsertIntoContainer_TcVnVector3_SINT : Node_F_VN_InsertIntoContainer_TcVnVector3_SINT;
    node_F_VN_InsertIntoContainer_TcVnVector3_UINT : Node_F_VN_InsertIntoContainer_TcVnVector3_UINT;
    node_F_VN_InsertIntoContainer_TcVnVector3_USINT : Node_F_VN_InsertIntoContainer_TcVnVector3_USINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_DINT : Node_F_VN_InsertIntoContainer_TcVnVector4_DINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_INT : Node_F_VN_InsertIntoContainer_TcVnVector4_INT;
    node_F_VN_InsertIntoContainer_TcVnVector4_LREAL : Node_F_VN_InsertIntoContainer_TcVnVector4_LREAL;
    node_F_VN_InsertIntoContainer_TcVnVector4_SINT : Node_F_VN_InsertIntoContainer_TcVnVector4_SINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_UINT : Node_F_VN_InsertIntoContainer_TcVnVector4_UINT;
    node_F_VN_InsertIntoContainer_TcVnVector4_USINT : Node_F_VN_InsertIntoContainer_TcVnVector4_USINT;
    node_F_VN_InsertIntoContainer_UDINT : Node_F_VN_InsertIntoContainer_UDINT;
    node_F_VN_InsertIntoContainer_UINT : node_F_VN_InsertIntoContainer_UINT;
    node_F_VN_InsertIntoContainer_ULINT : Node_F_VN_InsertIntoContainer_ULINT;
    node_F_VN_InsertIntoContainer_USINT : Node_F_VN_InsertIntoContainer_USINT;
    
    node_F_VN_SetAt_DINT : Node_F_VN_SetAt_DINT;
    node_F_VN_SetAt_INT : Node_F_VN_SetAt_INT;
    node_F_VN_SetAt_ITcVnContainer : Node_F_VN_SetAt_ITcVnContainer;
    node_F_VN_SetAt_ITcVnImage : Node_F_VN_SetAt_ITcVnImage;
    node_F_VN_SetAt_LREAL : Node_F_VN_SetAt_LREAL;
    node_F_VN_SetAt_REAL : Node_F_VN_SetAt_REAL;
    node_F_VN_SetAt_SINT : Node_F_VN_SetAt_SINT;
    node_F_VN_SetAt_TcVnDMatch : Node_F_VN_SetAt_TcVnDMatch;
    node_F_VN_SetAt_TcVnKeyPoint : Node_F_VN_SetAt_TcVnKeyPoint;
    node_F_VN_SetAt_TcVnPoint2_DINT : Node_F_VN_SetAt_TcVnPoint2_DINT;
    node_F_VN_SetAt_TcVnPoint2_LREAL : Node_F_VN_SetAt_TcVnPoint2_LREAL;
    node_F_VN_SetAt_TcVnPoint2_REAL : Node_F_VN_SetAt_TcVnPoint2_REAL;
    node_F_VN_SetAt_TcVnPoint3_LREAL : Node_F_VN_SetAt_TcVnPoint3_LREAL;
    node_F_VN_SetAt_TcVnPoint3_REAL : Node_F_VN_SetAt_TcVnPoint3_REAL;
    node_F_VN_SetAt_TcVnRectangle_DINT : Node_F_VN_SetAt_TcVnRectangle_DINT;
    node_F_VN_SetAt_TcVnVector2_DINT : Node_F_VN_SetAt_TcVnVector2_DINT;
    node_F_VN_SetAt_TcVnVector2_INT : Node_F_VN_SetAt_TcVnVector2_INT;
    node_F_VN_SetAt_TcVnVector2_REAL : Node_F_VN_SetAt_TcVnVector2_REAL;
    node_F_VN_SetAt_TcVnVector2_SINT : Node_F_VN_SetAt_TcVnVector2_SINT;
    node_F_VN_SetAt_TcVnVector2_UINT : Node_F_VN_SetAt_TcVnVector2_UINT;
    node_F_VN_SetAt_TcVnVector2_USINT : Node_F_VN_SetAt_TcVnVector2_USINT;
    node_F_VN_SetAt_TcVnVector3_INT : Node_F_VN_SetAt_TcVnVector3_INT;
    node_F_VN_SetAt_TcVnVector3_REAL : Node_F_VN_SetAt_TcVnVector3_REAL;
    node_F_VN_SetAt_TcVnVector3_SINT : Node_F_VN_SetAt_TcVnVector3_SINT;
    node_F_VN_SetAt_TcVnVector3_UINT : Node_F_VN_SetAt_TcVnVector3_UINT;
    node_F_VN_SetAt_TcVnVector3_USINT : Node_F_VN_SetAt_TcVnVector3_USINT;
    node_F_VN_SetAt_TcVnVector4_DINT : Node_F_VN_SetAt_TcVnVector4_DINT;
    node_F_VN_SetAt_TcVnVector4_INT : Node_F_VN_SetAt_TcVnVector4_INT;
    node_F_VN_SetAt_TcVnVector4_LREAL : Node_F_VN_SetAt_TcVnVector4_LREAL;
    node_F_VN_SetAt_TcVnVector4_SINT : Node_F_VN_SetAt_TcVnVector4_SINT;
    node_F_VN_SetAt_TcVnVector4_UINT : Node_F_VN_SetAt_TcVnVector4_UINT;
    node_F_VN_SetAt_TcVnVector4_USINT : Node_F_VN_SetAt_TcVnVector4_USINT;
    node_F_VN_SetAt_UDINT : Node_F_VN_SetAt_UDINT;
    node_F_VN_SetAt_UINT : node_F_VN_SetAt_UINT;
    node_F_VN_SetAt_ULINT : Node_F_VN_SetAt_ULINT;
    node_F_VN_SetAt_USINT : Node_F_VN_SetAt_USINT;
    
    //F_VN_AdvanceIterator
    //F_VN_CheckIfEmpty
    //F_VN_CheckIfIteratorIsAtEnd
    //F_VN_ConvertContainerType
    //F_VN_CopyContainer
    //F_VN_CopyContainerElementsConditional_ITcVnContainer
    //F_VN_CopyContainerElementsConditional_ITcVnForwardIterator
    //F_VN_CreateContainer
    //F_VN_CreateContainerFromArray
    //F_VN_EraseFromContainer
    //F_VN_ExportContainer
    //F_VN_ExportContainer_String
    //F_VN_ExportContainerSize
    //F_VN_ExportSubContainer
    //F_VN_ExportSubContainer_String
    //F_VN_ExportSubContainerSize
    //F_VN_ExtractContainerRange
    //F_VN_GetContainer
    //F_VN_GetContainerExp
    //F_VN_GetForwardIterator
    node_F_VN_GetNumberOfElements : Node_F_VN_GetNumberOfElements;
    //F_VN_GetRandomAccessIterator
    //F_VN_IncrementIterator
    //F_VN_IteratorDistance
    //F_VN_ReserveContainerMemory
    //F_VN_ReverseContainer
    //F_VN_SetContainer
    //F_VN_SetIteratorToBegin
    
    // Basic Image Operations
    //F_VN_CombineImageChannels
    node_F_VN_ConvertElementType : Node_F_VN_ConvertElementType;
    node_F_VN_ConvertElementTypeExp : Node_F_VN_ConvertElementTypeExp;
    node_F_VN_CopyImage : Node_F_VN_CopyImage;
    node_F_VN_CopyImageRegion : Node_F_VN_CopyImageRegion;
    node_F_VN_CopyImageRegionToRegion : Node_F_VN_CopyImageRegionToRegion;
    //node_F_VN_CopyIntoDisplayableImage : Node_F_VN_CopyIntoDisplayableImage;
    node_F_VN_CreateAssociatedImage : Node_F_VN_CreateAssociatedImage;
    node_F_VN_CreateEmptyImage : Node_F_VN_CreateEmptyImage;
    node_F_VN_CreateImage : Node_F_VN_CreateImage;
    node_F_VN_CreateImageAndSetPixels : Node_F_VN_CreateImageAndSetPixels;
    //F_VN_CreateImageFromArray
    //F_VN_ExportImage
    //F_VN_ExportImageAsBmp
    //F_VN_ExportImageAsBmpExp
    node_F_VN_ExportImageAsBmpSize : Node_F_VN_ExportImageAsBmpSize;
    //F_VN_ExportImageAsBmpSizeExp
    node_F_VN_ExportImageSize : Node_F_VN_ExportImageSize;
    node_F_VN_FuseImages : Node_F_VN_FuseImages;
    //F_VN_FuseImagesArray
    node_F_VN_GetImageChannel : Node_F_VN_GetImageChannel;
    node_F_VN_GetImageHeight : Node_F_VN_GetImageHeight;
    node_F_VN_GetImageInfo : Node_F_VN_GetImageInfo;
    node_F_VN_GetImageWidth : Node_F_VN_GetImageWidth;
    node_F_VN_GetPixel : Node_F_VN_GetPixel;
    node_F_VN_GetPixelFormat : Node_F_VN_GetPixelFormat;
    node_F_VN_GetRoi : Node_F_VN_GetRoi;
    //F_VN_MixImageChannels
    node_F_VN_ResetRoi : Node_F_VN_ResetRoi;
    node_F_VN_SetImageChannel : Node_F_VN_SetImageChannel;
    node_F_VN_SetPixel : Node_F_VN_SetPixel;
    node_F_VN_SetPixels : Node_F_VN_SetPixels;
    node_F_VN_SetPixelsExp : Node_F_VN_SetPixelsExp;
    node_F_VN_SetRoi : Node_F_VN_SetRoi;
    //node_F_VN_SetRoi_TcVnRectangle_DINT : Node_F_VN_SetRoi_TcVnRectangle_DINT;
    node_F_VN_SetRoi_TcVnRectangle_UDINT : Node_F_VN_SetRoi_TcVnRectangle_UDINT;
    //F_VN_SplitImageChannels
    //node_F_VN_TransformIntoDisplayableImage : Node_F_VN_TransformIntoDisplayableImage;
    //node_F_VN_TransformIntoDisplayableImageExp : Node_F_VN_TransformIntoDisplayableImageExp;
    
    // Code Quality
    //F_VN_GradeBarcode
    //F_VN_GradeBarcodeExp
    //F_VN_GradeDataMatrixCode
    //F_VN_GradeDataMatrixCodeExp
    //F_VN_GradeQRCode
    //F_VN_GradeQRCodeExp
    
    // Code Reading
    node_F_VN_ReadBarcode : Node_F_VN_ReadBarcode;
    // node_F_VN_ReadBarcodeExp : Node_F_VN_ReadBarcodeExp;
    // node_F_VN_ReadBarcodeExp2 : Node_F_VN_ReadBarcodeExp2;
    node_F_VN_ReadDataMatrixCode : Node_F_VN_ReadDataMatrixCode;
    // node_F_VN_ReadDataMatrixCodeExp : Node_F_VN_ReadDataMatrixCodeExp;
    // node_F_VN_ReadDataMatrixCodeExp2 : Node_F_VN_ReadDataMatrixCodeExp2;
    node_F_VN_ReadPharmaCode : Node_F_VN_ReadPharmaCode;
    // node_F_VN_ReadPharmaCodeExp : Node_F_VN_ReadPharmaCodeExp;
    // node_F_VN_ReadPharmaCodeExp2 : Node_F_VN_ReadPharmaCodeExp2;
    node_F_VN_ReadQRCode : Node_F_VN_ReadQRCode;
    // node_F_VN_ReadQRCodeExp : Node_F_VN_ReadQRCodeExp;
    // node_F_VN_ReadQRCodeExp2 : Node_F_VN_ReadQRCodeExp2;
    
    // Constants
    node_RGBA_BLACK : Node_RGBA_BLACK;
    node_RGBA_RED : Node_RGBA_RED;
    node_RGBA_YELLOW : Node_RGBA_YELLOW;
    node_RGBA_GREEN : Node_RGBA_GREEN;
    node_RGBA_CYAN : Node_RGBA_CYAN;
    node_RGBA_BLUE : Node_RGBA_BLUE;
    node_RGBA_MAGENTA : Node_RGBA_MAGENTA;
    node_RGBA_WHITE : Node_RGBA_WHITE;
    
    // Container Statistics
    node_F_VN_MaxElementElementwise_DINT : Node_F_VN_MaxElementElementwise_DINT;
    node_F_VN_MaxElementElementwise_INT : Node_F_VN_MaxElementElementwise_INT;
    node_F_VN_MaxElementElementwise_LREAL : Node_F_VN_MaxElementElementwise_LREAL;
    node_F_VN_MaxElementElementwise_REAL : Node_F_VN_MaxElementElementwise_REAL;
    node_F_VN_MaxElementElementwise_SINT : Node_F_VN_MaxElementElementwise_SINT;
    node_F_VN_MaxElementElementwise_TcVnPoint2_DINT : Node_F_VN_MaxElementElementwise_TcVnPoint2_DINT;
    node_F_VN_MaxElementElementwise_TcVnPoint2_LREAL : Node_F_VN_MaxElementElementwise_TcVnPoint2_LREAL;
    node_F_VN_MaxElementElementwise_TcVnPoint2_REAL : Node_F_VN_MaxElementElementwise_TcVnPoint2_REAL;
    node_F_VN_MaxElementElementwise_TcVnPoint3_LREAL : Node_F_VN_MaxElementElementwise_TcVnPoint3_LREAL;
    node_F_VN_MaxElementElementwise_TcVnPoint3_REAL : Node_F_VN_MaxElementElementwise_TcVnPoint3_REAL;
    node_F_VN_MaxElementElementwise_TcVnVector2_DINT : Node_F_VN_MaxElementElementwise_TcVnVector2_DINT;
    node_F_VN_MaxElementElementwise_TcVnVector2_INT : Node_F_VN_MaxElementElementwise_TcVnVector2_INT;
    node_F_VN_MaxElementElementwise_TcVnVector2_REAL : Node_F_VN_MaxElementElementwise_TcVnVector2_REAL;
    node_F_VN_MaxElementElementwise_TcVnVector2_SINT : Node_F_VN_MaxElementElementwise_TcVnVector2_SINT;
    node_F_VN_MaxElementElementwise_TcVnVector2_UINT : Node_F_VN_MaxElementElementwise_TcVnVector2_UINT;
    node_F_VN_MaxElementElementwise_TcVnVector2_USINT : Node_F_VN_MaxElementElementwise_TcVnVector2_USINT;
    node_F_VN_MaxElementElementwise_TcVnVector3_INT : Node_F_VN_MaxElementElementwise_TcVnVector3_INT;
    node_F_VN_MaxElementElementwise_TcVnVector3_REAL : Node_F_VN_MaxElementElementwise_TcVnVector3_REAL;
    node_F_VN_MaxElementElementwise_TcVnVector3_SINT : Node_F_VN_MaxElementElementwise_TcVnVector3_SINT;
    node_F_VN_MaxElementElementwise_TcVnVector3_UINT : Node_F_VN_MaxElementElementwise_TcVnVector3_UINT;
    node_F_VN_MaxElementElementwise_TcVnVector3_USINT : Node_F_VN_MaxElementElementwise_TcVnVector3_USINT;
    node_F_VN_MaxElementElementwise_TcVnVector4_DINT : Node_F_VN_MaxElementElementwise_TcVnVector4_DINT;
    node_F_VN_MaxElementElementwise_TcVnVector4_INT : Node_F_VN_MaxElementElementwise_TcVnVector4_INT;
    node_F_VN_MaxElementElementwise_TcVnVector4_LREAL : Node_F_VN_MaxElementElementwise_TcVnVector4_LREAL;
    node_F_VN_MaxElementElementwise_TcVnVector4_SINT : Node_F_VN_MaxElementElementwise_TcVnVector4_SINT;
    node_F_VN_MaxElementElementwise_TcVnVector4_UINT : Node_F_VN_MaxElementElementwise_TcVnVector4_UINT;
    node_F_VN_MaxElementElementwise_TcVnVector4_USINT : Node_F_VN_MaxElementElementwise_TcVnVector4_USINT;
    node_F_VN_MaxElementElementwise_UDINT : Node_F_VN_MaxElementElementwise_UDINT;
    node_F_VN_MaxElementElementwise_UINT : node_F_VN_MaxElementElementwise_UINT;
    node_F_VN_MaxElementElementwise_ULINT : Node_F_VN_MaxElementElementwise_ULINT;
    node_F_VN_MaxElementElementwise_USINT : Node_F_VN_MaxElementElementwise_USINT;
    node_F_VN_MedianElementElementwise_DINT : Node_F_VN_MedianElementElementwise_DINT;
    node_F_VN_MedianElementElementwise_INT : Node_F_VN_MedianElementElementwise_INT;
    node_F_VN_MedianElementElementwise_LREAL : Node_F_VN_MedianElementElementwise_LREAL;
    node_F_VN_MedianElementElementwise_REAL : Node_F_VN_MedianElementElementwise_REAL;
    node_F_VN_MedianElementElementwise_SINT : Node_F_VN_MedianElementElementwise_SINT;
    node_F_VN_MedianElementElementwise_TcVnPoint2_DINT : Node_F_VN_MedianElementElementwise_TcVnPoint2_DINT;
    node_F_VN_MedianElementElementwise_TcVnPoint2_LREAL : Node_F_VN_MedianElementElementwise_TcVnPoint2_LREAL;
    node_F_VN_MedianElementElementwise_TcVnPoint2_REAL : Node_F_VN_MedianElementElementwise_TcVnPoint2_REAL;
    node_F_VN_MedianElementElementwise_TcVnPoint3_LREAL : Node_F_VN_MedianElementElementwise_TcVnPoint3_LREAL;
    node_F_VN_MedianElementElementwise_TcVnPoint3_REAL : Node_F_VN_MedianElementElementwise_TcVnPoint3_REAL;
    node_F_VN_MedianElementElementwise_TcVnVector2_DINT : Node_F_VN_MedianElementElementwise_TcVnVector2_DINT;
    node_F_VN_MedianElementElementwise_TcVnVector2_INT : Node_F_VN_MedianElementElementwise_TcVnVector2_INT;
    node_F_VN_MedianElementElementwise_TcVnVector2_REAL : Node_F_VN_MedianElementElementwise_TcVnVector2_REAL;
    node_F_VN_MedianElementElementwise_TcVnVector2_SINT : Node_F_VN_MedianElementElementwise_TcVnVector2_SINT;
    node_F_VN_MedianElementElementwise_TcVnVector2_UINT : Node_F_VN_MedianElementElementwise_TcVnVector2_UINT;
    node_F_VN_MedianElementElementwise_TcVnVector2_USINT : Node_F_VN_MedianElementElementwise_TcVnVector2_USINT;
    node_F_VN_MedianElementElementwise_TcVnVector3_INT : Node_F_VN_MedianElementElementwise_TcVnVector3_INT;
    node_F_VN_MedianElementElementwise_TcVnVector3_REAL : Node_F_VN_MedianElementElementwise_TcVnVector3_REAL;
    node_F_VN_MedianElementElementwise_TcVnVector3_SINT : Node_F_VN_MedianElementElementwise_TcVnVector3_SINT;
    node_F_VN_MedianElementElementwise_TcVnVector3_UINT : Node_F_VN_MedianElementElementwise_TcVnVector3_UINT;
    node_F_VN_MedianElementElementwise_TcVnVector3_USINT : Node_F_VN_MedianElementElementwise_TcVnVector3_USINT;
    node_F_VN_MedianElementElementwise_TcVnVector4_DINT : Node_F_VN_MedianElementElementwise_TcVnVector4_DINT;
    node_F_VN_MedianElementElementwise_TcVnVector4_INT : Node_F_VN_MedianElementElementwise_TcVnVector4_INT;
    node_F_VN_MedianElementElementwise_TcVnVector4_LREAL : Node_F_VN_MedianElementElementwise_TcVnVector4_LREAL;
    node_F_VN_MedianElementElementwise_TcVnVector4_SINT : Node_F_VN_MedianElementElementwise_TcVnVector4_SINT;
    node_F_VN_MedianElementElementwise_TcVnVector4_UINT : Node_F_VN_MedianElementElementwise_TcVnVector4_UINT;
    node_F_VN_MedianElementElementwise_TcVnVector4_USINT : Node_F_VN_MedianElementElementwise_TcVnVector4_USINT;
    node_F_VN_MedianElementElementwise_UDINT : Node_F_VN_MedianElementElementwise_UDINT;
    node_F_VN_MedianElementElementwise_UINT : node_F_VN_MedianElementElementwise_UINT;
    node_F_VN_MedianElementElementwise_ULINT : Node_F_VN_MedianElementElementwise_ULINT;
    node_F_VN_MedianElementElementwise_USINT : Node_F_VN_MedianElementElementwise_USINT;
    node_F_VN_MinElementElementwise_DINT : Node_F_VN_MinElementElementwise_DINT;
    node_F_VN_MinElementElementwise_INT : Node_F_VN_MinElementElementwise_INT;
    node_F_VN_MinElementElementwise_LREAL : Node_F_VN_MinElementElementwise_LREAL;
    node_F_VN_MinElementElementwise_REAL : Node_F_VN_MinElementElementwise_REAL;
    node_F_VN_MinElementElementwise_SINT : Node_F_VN_MinElementElementwise_SINT;
    node_F_VN_MinElementElementwise_TcVnPoint2_DINT : Node_F_VN_MinElementElementwise_TcVnPoint2_DINT;
    node_F_VN_MinElementElementwise_TcVnPoint2_LREAL : Node_F_VN_MinElementElementwise_TcVnPoint2_LREAL;
    node_F_VN_MinElementElementwise_TcVnPoint2_REAL : Node_F_VN_MinElementElementwise_TcVnPoint2_REAL;
    node_F_VN_MinElementElementwise_TcVnPoint3_LREAL : Node_F_VN_MinElementElementwise_TcVnPoint3_LREAL;
    node_F_VN_MinElementElementwise_TcVnPoint3_REAL : Node_F_VN_MinElementElementwise_TcVnPoint3_REAL;
    node_F_VN_MinElementElementwise_TcVnVector2_DINT : Node_F_VN_MinElementElementwise_TcVnVector2_DINT;
    node_F_VN_MinElementElementwise_TcVnVector2_INT : Node_F_VN_MinElementElementwise_TcVnVector2_INT;
    node_F_VN_MinElementElementwise_TcVnVector2_REAL : Node_F_VN_MinElementElementwise_TcVnVector2_REAL;
    node_F_VN_MinElementElementwise_TcVnVector2_SINT : Node_F_VN_MinElementElementwise_TcVnVector2_SINT;
    node_F_VN_MinElementElementwise_TcVnVector2_UINT : Node_F_VN_MinElementElementwise_TcVnVector2_UINT;
    node_F_VN_MinElementElementwise_TcVnVector2_USINT : Node_F_VN_MinElementElementwise_TcVnVector2_USINT;
    node_F_VN_MinElementElementwise_TcVnVector3_INT : Node_F_VN_MinElementElementwise_TcVnVector3_INT;
    node_F_VN_MinElementElementwise_TcVnVector3_REAL : Node_F_VN_MinElementElementwise_TcVnVector3_REAL;
    node_F_VN_MinElementElementwise_TcVnVector3_SINT : Node_F_VN_MinElementElementwise_TcVnVector3_SINT;
    node_F_VN_MinElementElementwise_TcVnVector3_UINT : Node_F_VN_MinElementElementwise_TcVnVector3_UINT;
    node_F_VN_MinElementElementwise_TcVnVector3_USINT : Node_F_VN_MinElementElementwise_TcVnVector3_USINT;
    node_F_VN_MinElementElementwise_TcVnVector4_DINT : Node_F_VN_MinElementElementwise_TcVnVector4_DINT;
    node_F_VN_MinElementElementwise_TcVnVector4_INT : Node_F_VN_MinElementElementwise_TcVnVector4_INT;
    node_F_VN_MinElementElementwise_TcVnVector4_LREAL : Node_F_VN_MinElementElementwise_TcVnVector4_LREAL;
    node_F_VN_MinElementElementwise_TcVnVector4_SINT : Node_F_VN_MinElementElementwise_TcVnVector4_SINT;
    node_F_VN_MinElementElementwise_TcVnVector4_UINT : Node_F_VN_MinElementElementwise_TcVnVector4_UINT;
    node_F_VN_MinElementElementwise_TcVnVector4_USINT : Node_F_VN_MinElementElementwise_TcVnVector4_USINT;
    node_F_VN_MinElementElementwise_UDINT : Node_F_VN_MinElementElementwise_UDINT;
    node_F_VN_MinElementElementwise_UINT : node_F_VN_MinElementElementwise_UINT;
    node_F_VN_MinElementElementwise_ULINT : Node_F_VN_MinElementElementwise_ULINT;
    node_F_VN_MinElementElementwise_USINT : Node_F_VN_MinElementElementwise_USINT;
    //F_VN_ContainerAverage
    //F_VN_ContainerAverageElementwise2
    //F_VN_ContainerAverageElementwise3
    //F_VN_ContainerAverageElementwise4
    //F_VN_ContainerAverageVariance
    //F_VN_ContainerAverageVarianceElementwise2
    //F_VN_ContainerAverageVarianceElementwise3
    //F_VN_ContainerAverageVarianceElementwise4
    //F_VN_MaxElement
    //F_VN_MedianElement
    //F_VN_MinElement
   
    // Contour Analysis
    //F_VN_ApproximatePolygon
    //F_VN_CheckIfPointIsInsideContour
    node_F_VN_ContourArea : Node_F_VN_ContourArea;
    node_F_VN_ContourCenterOfMass : Node_F_VN_ContourCenterOfMass;
    node_F_VN_ContourCircularity : Node_F_VN_ContourCircularity;
    node_F_VN_ContourConvexity : Node_F_VN_ContourConvexity;
    node_F_VN_ContourEccentricity : Node_F_VN_ContourEccentricity;
    //F_VN_ContourElongation
    //F_VN_ContourExtremePoint
    node_F_VN_ContourInertiaRatio : Node_F_VN_ContourInertiaRatio;
    node_F_VN_ContourMoments : Node_F_VN_ContourMoments;
    node_F_VN_ContourOrientation : Node_F_VN_ContourOrientation;
    //F_VN_ContourOrientationExp
    node_F_VN_ContourPerimeter : Node_F_VN_ContourPerimeter;
    node_F_VN_ContourRoundness : Node_F_VN_ContourRoundness;
    //F_VN_ConvexHullPoints
    //F_VN_ConvexHullPointsExp
    //F_VN_ConvexityDefects
    //F_VN_CustomElementWiseContainerOperation_ITcVnContainer
    //F_VN_CustomElementWiseContainerOperation_ITcVnForwardIterator
    node_F_VN_EnclosingCircle : Node_F_VN_EnclosingCircle;
    node_F_VN_EnclosingRectangle : Node_F_VN_EnclosingRectangle;
    node_F_VN_EnclosingTriangle : Node_F_VN_EnclosingTriangle;
    node_F_VN_FitEllipse : Node_F_VN_FitEllipse;
    node_F_VN_FitLine : Node_F_VN_FitLine;
    //F_VN_FitLineExp
    //F_VN_FourierDescriptors
    //F_VN_MatchContours
    //F_VN_MatchContours1vsN
    //F_VN_MatchContours1vsNExp
    //F_VN_MatchContoursExp
    //F_VN_UprightBoundingRectangle
    
    // Control Functions
    //F_VN_StartAbsWatchdog
    //F_VN_StartAbsWatchdogExp
    //F_VN_StartRelWatchdog
    //F_VN_StartRelWatchdogExp
    //F_VN_StopWatchdog
    
    // Drawing
    node_F_VN_DrawArrow : Node_F_VN_DrawArrow;
    node_F_VN_DrawArrow_TcVnVector4_DINT : Node_F_VN_DrawArrow_TcVnVector4_DINT;
    node_F_VN_DrawArrowExp : Node_F_VN_DrawArrowExp;
    node_F_VN_DrawArrowExp_TcVnVector4_DINT : Node_F_VN_DrawArrowExp_TcVnVector4_DINT;
    node_F_VN_DrawCircle : Node_F_VN_DrawCircle;
    node_F_VN_DrawCircleExp : Node_F_VN_DrawCircleExp;
    node_F_VN_DrawCircles : Node_F_VN_DrawCircles;
    node_F_VN_DrawCirclesExp : Node_F_VN_DrawCirclesExp;
    node_F_VN_DrawCircularArc : Node_F_VN_DrawCircularArc;
    node_F_VN_DrawCircularArcExp : Node_F_VN_DrawCircularArcExp;
    //F_VN_DrawComponents
    //F_VN_DrawComponentsExp
    node_F_VN_DrawContours : Node_F_VN_DrawContours;
    //F_VN_DrawContoursExp
    node_F_VN_DrawEllipse : Node_F_VN_DrawEllipse;
    node_F_VN_DrawEllipseExp : Node_F_VN_DrawEllipseExp;
    node_F_VN_DrawKeypoints : Node_F_VN_DrawKeypoints;
    //F_VN_DrawKeypointsExp
    node_F_VN_DrawLine : Node_F_VN_DrawLine;
    node_F_VN_DrawLine_TcVnVector4_DINT : Node_F_VN_DrawLine_TcVnVector4_DINT;
    node_F_VN_DrawLine_TcVnVector4_LREAL : Node_F_VN_DrawLine_TcVnVector4_LREAL;
    node_F_VN_DrawLineExp : Node_F_VN_DrawLineExp;
    node_F_VN_DrawLineExp_TcVnVector4_DINT : Node_F_VN_DrawLineExp_TcVnVector4_DINT;
    node_F_VN_DrawLineExp_TcVnVector4_LREAL : Node_F_VN_DrawLineExp_TcVnVector4_LREAL;
    //F_VN_DrawLines
    //F_VN_DrawLinesExp
    //F_VN_DrawMatches
    //F_VN_DrawMatchesExp
    node_F_VN_DrawOrientation : Node_F_VN_DrawOrientation;
    //F_VN_DrawOrientationExp
    node_F_VN_DrawPoint : Node_F_VN_DrawPoint;
    //F_VN_DrawPointExp
    //F_VN_DrawPoints
    //F_VN_DrawPointsExp
    node_F_VN_DrawPolygon : Node_F_VN_DrawPolygon;
    //F_VN_DrawPolygonExp
    node_F_VN_DrawRectangle : Node_F_VN_DrawRectangle;
    //node_F_VN_DrawRectangle_TcVnRectangle_DINT : Node_F_VN_DrawRectangle_TcVnRectangle_DINT;
    node_F_VN_DrawRectangle_TcVnRectangle_UDINT : Node_F_VN_DrawRectangle_TcVnRectangle_UDINT;
    node_F_VN_DrawRotatedRectangle : Node_F_VN_DrawRotatedRectangle;
    node_F_VN_DrawRotatedRectangleExp : Node_F_VN_DrawRotatedRectangleExp;
    node_F_VN_FillCircle : Node_F_VN_FillCircle;
    node_F_VN_FillContours : Node_F_VN_FillContours;
    node_F_VN_FillEllipse : Node_F_VN_FillEllipse;
    node_F_VN_FillPolygon : Node_F_VN_FillPolygon;
    node_F_VN_FillRectangle : Node_F_VN_FillRectangle;
    node_F_VN_FillRotatedRectangle : Node_F_VN_FillRotatedRectangle;
    node_F_VN_PlotIntensityProfile : Node_F_VN_PlotIntensityProfile;
    node_F_VN_PlotIntensityProfileExp : Node_F_VN_PlotIntensityProfileExp;
    node_F_VN_PutLabel : Node_F_VN_PutLabel;
    node_F_VN_PutLabelExp : Node_F_VN_PutLabelExp;
    node_F_VN_PutText : Node_F_VN_PutText;
    node_F_VN_PutTextExp : Node_F_VN_PutTextExp;
    
    // Fourier Analysis
    //F_VN_CreateBandpassButterworthFilter
    //F_VN_CreateBandpassGaussianFilter
    //F_VN_CreateBandrejectButterworthFilter
    //F_VN_CreateBandrejectGaussianFilter
    //F_VN_CreateHighpassButterworthFilter
    //F_VN_CreateHighpassGaussianFilter
    //F_VN_CreateLowpassButterworthFilter
    //F_VN_CreateLowpassGaussianFilter
    //F_VN_Dft
    //F_VN_InverseDft
    //F_VN_OptimalDftSize
    node_F_VN_PadImageBorder : Node_F_VN_PadImageBorder;
    node_F_VN_PadImageBorderExp : Node_F_VN_PadImageBorderExp;
    
    // Geometric and Coordinate Transformations
    //F_VN_CalibrateCamera
    //F_VN_CalibrateCameraExp
    //F_VN_CalibrateCameraExp2
    //F_VN_CalibrateCameraExp3
    //F_VN_CalibrateCameraManually
    //F_VN_CalibrateCameraManuallyExp
    //F_VN_CalibrateCameraPlanar
    //F_VN_CalibrateCameraPlanarExp
    //F_VN_CalibrateLinescanCamera
    //F_VN_CalibrateLinescanCameraExp
    //F_VN_CompensateLensDistortion
    //F_VN_CompensateLensDistortionExp1
    //F_VN_CompensateLensDistortionExp2
    //F_VN_CompensateLensDistortionForPoints
    //F_VN_CompensateLensDistortionForPointsExp1
    //F_VN_CompensateLensDistortionForPointsExp2
    //F_VN_DetectPatternPoints
    //F_VN_DetectPatternPointsExp
    //F_VN_GenerateCalibrationPatternReferencePoints
    //F_VN_ImagePointsWorldDistance
    //F_VN_SolvePnP
    //F_VN_SolvePnPExp
    //F_VN_SortDetectedPatternPoints
    //F_VN_TransformCoordinatesImageToWorld_Container
    //F_VN_TransformCoordinatesImageToWorld_Point
    //F_VN_TransformCoordinatesPlanar_Container
    //F_VN_TransformCoordinatesPlanar_Point
    //F_VN_TransformCoordinatesWorldToImage_Container
    //F_VN_TransformCoordinatesWorldToImage_Point
    node_F_VN_AlignRotatedImageRegion : Node_F_VN_AlignRotatedImageRegion;
    //F_VN_AlignRotatedImageRegionExp
    node_F_VN_ApplyRotationToAffineTransformation : Node_F_VN_ApplyRotationToAffineTransformation;
    node_F_VN_ApplyRotationToAffineTransformationExp : Node_F_VN_ApplyRotationToAffineTransformationExp;
    node_F_VN_ApplyScalingToAffineTransformation : Node_F_VN_ApplyScalingToAffineTransformation;
    node_F_VN_ApplyScalingToAffineTransformationExp : Node_F_VN_ApplyScalingToAffineTransformationExp;
    node_F_VN_ApplyTranslationToAffineTransformation : Node_F_VN_ApplyTranslationToAffineTransformation;
    node_F_VN_ApplyTranslationToAffineTransformationExp : Node_F_VN_ApplyTranslationToAffineTransformationExp;
    node_F_VN_ApplyYAxisInversionToAffineTransformation : Node_F_VN_ApplyYAxisInversionToAffineTransformation;
    node_F_VN_ApplyYAxisInversionToAffineTransformationExp : Node_F_VN_ApplyYAxisInversionToAffineTransformationExp;
    //F_VN_ConvertCartesianToPolarAngleImage
    //F_VN_ConvertCartesianToPolarAngleImageExp
    //F_VN_ConvertCartesianToPolarAngles
    //F_VN_ConvertCartesianToPolarAnglesExp
    //F_VN_ConvertCartesianToPolarImages
    //F_VN_ConvertCartesianToPolarImagesExp
    //F_VN_ConvertCartesianToPolarMagnitudeImage
    //F_VN_ConvertCartesianToPolarMagnitudes
    //F_VN_ConvertCartesianToPolarPoints
    //F_VN_ConvertCartesianToPolarPointsExp
    //F_VN_ConvertPolarToCartesianImages
    //F_VN_ConvertPolarToCartesianImagesExp
    //F_VN_ConvertPolarToCartesianPoints
    //F_VN_ConvertPolarToCartesianPointsExp
    //F_VN_DecomposeAffineTransformation
    //F_VN_DecomposeAffineTransformationExp
    //F_VN_DecomposeHomography
    //F_VN_DecomposeHomographyExp
    node_F_VN_FlipImage : Node_F_VN_FlipImage;
    node_F_VN_GenerateAffineTransformationUnitMatrix2D : Node_F_VN_GenerateAffineTransformationUnitMatrix2D;
    node_F_VN_GetAffineTransformation : Node_F_VN_GetAffineTransformation;
    //F_VN_GetAffineTransformation2D
    //F_VN_GetAffineTransformation2DExp
    //F_VN_GetPerspectiveTransformation
    //F_VN_Homography
    //F_VN_HomographyExp
    node_F_VN_InvertAffineTransformation : Node_F_VN_InvertAffineTransformation;
    //F_VN_PerspectiveTransformation
    node_F_VN_PyramidDown : Node_F_VN_PyramidDown;
    node_F_VN_PyramidUp : Node_F_VN_PyramidUp;
    //F_VN_RemapImageToLogPolarSpace
    //F_VN_RemapImageToLogPolarSpaceExp
    //F_VN_RemapImageToLogPolarSpaceExp2
    //F_VN_RemapImageToPolarSpace
    //F_VN_RemapImageToPolarSpaceExp
    //F_VN_RemapImageToPolarSpaceExp2
    node_F_VN_ResizeImage : Node_F_VN_ResizeImage;
    //F_VN_ResizeImageExp
    node_F_VN_RotateImage : Node_F_VN_RotateImage;
    //F_VN_RotateImageExp
    //F_VN_RotateImageExp2
    node_F_VN_WarpAffine : Node_F_VN_WarpAffine;
    //F_VN_WarpAffine_Container
    //F_VN_WarpAffine_Point
    //F_VN_WarpAffine_Rectangle
    //F_VN_WarpAffineExp
    node_F_VN_WarpPerspective : Node_F_VN_WarpPerspective;
    //F_VN_WarpPerspective_Container
    //F_VN_WarpPerspective_Point
    //F_VN_WarpPerspective_Rectangle
    //F_VN_WarpPerspectiveExp
    
    // Image Analysis
    //F_VN_AdjustActiveContour
    node_F_VN_DetectBlobs : Node_F_VN_DetectBlobs;
    node_F_VN_DetectBlobsExp : Node_F_VN_DetectBlobsExp;
    //F_VN_FindContourHierarchyExp
    //F_VN_FindContours
    //F_VN_FindContoursExp
    //F_VN_HoughCircles
    //F_VN_HoughCirclesExp
    //F_VN_HoughLines
    //F_VN_HoughLinesExp
    //F_VN_HoughLinesP
    //F_VN_HoughLinesPExp
    //F_VN_MatchImageHuMoments
    //F_VN_MatchTemplate
    //F_VN_MatchTemplateAndEvaluate
    //F_VN_MatchTemplateAndEvaluateExp
    //F_VN_MatchTemplateExp
    node_F_VN_CannyEdgeDetection : Node_F_VN_CannyEdgeDetection;
    node_F_VN_CannyEdgeDetectionExp : Node_F_VN_CannyEdgeDetectionExp;
    //F_VN_ConnectedComponents
    //F_VN_ConnectedComponentsExp
    //F_VN_ConnectedComponentsWithStats
    //F_VN_ConnectedComponentsWithStatsExp
    node_F_VN_CountNonZeroPixels : Node_F_VN_CountNonZeroPixels;
    node_F_VN_DistanceTransformation : Node_F_VN_DistanceTransformation;
    //F_VN_DistanceTransformationExp
    //F_VN_GetConnectedComponent
    //F_VN_GetConnectedComponentExp
    node_F_VN_ImageAverage : Node_F_VN_ImageAverage;
    node_F_VN_ImageAverageExp : Node_F_VN_ImageAverageExp;
    node_F_VN_ImageAverageStdDev : Node_F_VN_ImageAverageStdDev;
    node_F_VN_ImageAverageStdDevExp : Node_F_VN_ImageAverageStdDevExp;
    node_F_VN_ImageCenterOfMass : Node_F_VN_ImageCenterOfMass;
    node_F_VN_ImageCenterOfMassExp : Node_F_VN_ImageCenterOfMassExp;
    node_F_VN_ImageMedian : Node_F_VN_ImageMedian;
    node_F_VN_ImageMedianExp : Node_F_VN_ImageMedianExp;
    node_F_VN_ImageMoments : Node_F_VN_ImageMoments;
    node_F_VN_MaxPixelValue : Node_F_VN_MaxPixelValue;
    node_F_VN_MaxPixelValueExp : Node_F_VN_MaxPixelValueExp;
    node_F_VN_MinPixelValue : Node_F_VN_MinPixelValue;
    node_F_VN_MinPixelValueExp : Node_F_VN_MinPixelValueExp;
    node_F_VN_RegionOrientation : Node_F_VN_RegionOrientation;
    node_F_VN_RegionOrientationExp : Node_F_VN_RegionOrientationExp;
    
    // Image Color and Contrast Processing
    node_F_VN_ApplyColorMap : Node_F_VN_ApplyColorMap;
    //F_VN_ApplyLut
    node_F_VN_Clahe : Node_F_VN_Clahe;
    node_F_VN_ClaheExp : Node_F_VN_ClaheExp;
    node_F_VN_ConvertColorSpace : Node_F_VN_ConvertColorSpace;
    node_F_VN_GenerateColorMap : Node_F_VN_GenerateColorMap;
    //F_VN_GenerateCustomColorMap
    node_F_VN_Histogram : Node_F_VN_Histogram;
    node_F_VN_HistogramEqualization : Node_F_VN_HistogramEqualization;
    //F_VN_HistogramEqualizationExp
    //F_VN_HistogramExp
    node_F_VN_InvertImageColor : Node_F_VN_InvertImageColor;
    //F_VN_InvertImageColorExp
    node_F_VN_NormalizeImage : Node_F_VN_NormalizeImage;
    //F_VN_NormalizeImageExp
    node_F_VN_NormalizeImageForDisplay : Node_F_VN_NormalizeImageForDisplay;
    //F_VN_ReferenceColorSimilarity_ITcVnColorModel
    //F_VN_ReferenceColorSimilarity_ITcVnMlModel
    //F_VN_ReferenceColorSimilarity_TcVnVector3_LREAL
    //F_VN_ReferenceColorSimilarityExp_ITcVnColorModel
    //F_VN_ReferenceColorSimilarityExp_ITcVnMlModel
    //F_VN_ReferenceColorSimilarityExp_TcVnVector3_LREAL
    //F_VN_TrainImageColor
    //F_VN_TrainImageColor_ITcVnMlModel
    //F_VN_TrainImageColorExp
    //F_VN_TrainImageColorExp_ITcVnMlModel
    //F_VN_TrainImageColorExp2
    //F_VN_TrainImageColorExp2_ITcVnMlModel
    //F_VN_WhiteBalance
    
    // Image Filtering
    //F_VN_BilateralFilter
    //F_VN_BilateralFilterExp
    node_F_VN_BoxFilter : Node_F_VN_BoxFilter;
    //F_VN_BoxFilterExp
    node_F_VN_BrightBorderObjects : Node_F_VN_BrightBorderObjects;
    node_F_VN_CreateStructuringElement : Node_F_VN_CreateStructuringElement;
    //F_VN_CustomFilter
    //F_VN_CustomFilterExp
    node_F_VN_DarkBorderObjects : Node_F_VN_DarkBorderObjects;
    node_F_VN_FillHoles : Node_F_VN_FillHoles;
    node_F_VN_GaussianFilter : Node_F_VN_GaussianFilter;
    //F_VN_GaussianFilterExp
    node_F_VN_LaplacianFilter : Node_F_VN_LaplacianFilter;
    //F_VN_LaplacianFilterExp
    node_F_VN_LocalMaxima : Node_F_VN_LocalMaxima;
    node_F_VN_LocalMinima : Node_F_VN_LocalMinima;
    //F_VN_MedianFilter
    node_F_VN_MorphologicalOperator : Node_F_VN_MorphologicalOperator;
    //F_VN_RemoveLocalMaxima
    //F_VN_RemoveLocalMinima
    //F_VN_ScharrFilter
    //F_VN_ScharrFilterExp
    //F_VN_SeparableCustomFilter
    //F_VN_SeparableCustomFilterExp
    //F_VN_SobelFilter
    //F_VN_SobelFilterExp
    node_F_VN_VarianceFilter : Node_F_VN_VarianceFilter;
    //F_VN_VarianceFilterExp
    
    // Image Segmentation
    node_F_VN_AdaptiveThreshold : Node_F_VN_AdaptiveThreshold;
    node_F_VN_AdaptiveThresholdExp : Node_F_VN_AdaptiveThresholdExp;
    node_F_VN_CheckColorRange : Node_F_VN_CheckColorRange;
    //node_F_VN_DoubleThreshold : Node_F_VN_DoubleThreshold;
    node_F_VN_Threshold : Node_F_VN_Threshold;
    node_F_VN_WatershedSegmentationExp : Node_F_VN_WatershedSegmentationExp;
    
    // Keypoint Features
    //F_VN_FilterGoodMatches
    //F_VN_FindReferenceKeyPointsInImage
    //F_VN_FindReferenceKeyPointsInImageAKAZE
    //F_VN_FindReferenceKeyPointsInImageAKAZEExp
    //F_VN_FindReferenceKeyPointsInImageBRISK
    //F_VN_FindReferenceKeyPointsInImageBRISKExp
    //F_VN_FindReferenceKeyPointsInImageExp
    //F_VN_FindReferenceKeyPointsInImageORB
    //F_VN_FindReferenceKeyPointsInImageORBExp
    //F_VN_GetMatchCoordinates
    node_F_VN_KeyPointsAGAST : Node_F_VN_KeyPointsAGAST;
    //F_VN_KeyPointsAGASTExp
    //F_VN_KeyPointsAndDescriptorsAKAZE
    //F_VN_KeyPointsAndDescriptorsAKAZEExp
    //F_VN_KeyPointsAndDescriptorsBRISK
    //F_VN_KeyPointsAndDescriptorsBRISKExp
    //F_VN_KeyPointsAndDescriptorsKAZE
    //F_VN_KeyPointsAndDescriptorsKAZEExp
    //F_VN_KeyPointsAndDescriptorsORB
    //F_VN_KeyPointsAndDescriptorsORBExp
    node_F_VN_KeyPointsFAST : Node_F_VN_KeyPointsFAST;
    //F_VN_KeyPointsFASTExp
    node_F_VN_KeyPointsGFTT : Node_F_VN_KeyPointsGFTT;
    //F_VN_KeyPointsGFTTExp
    node_F_VN_KeyPointsMSER : Node_F_VN_KeyPointsMSER;
    //F_VN_KeyPointsMSERExp
    node_F_VN_KeyPointsSB : Node_F_VN_KeyPointsSB;
    //F_VN_KeyPointsSBExp
    //F_VN_MatchDescriptorsBF
    //F_VN_MatchDescriptorsBFExp
    //F_VN_MatchDescriptorsFlannLsh
    //F_VN_MatchDescriptorsFlannLshExp
    //F_VN_MatchDescriptorsKnnBF
    //F_VN_MatchDescriptorsKnnBFExp
    //F_VN_MatchDescriptorsKnnFlannLsh
    //F_VN_MatchDescriptorsKnnFlannLshExp
    node_F_VN_RegionsMSER : Node_F_VN_RegionsMSER;
    node_F_VN_RegionsMSERExp : Node_F_VN_RegionsMSERExp;
    
    // Machine Learning
    //F_VN_CreateBoostClassifier
    //F_VN_CreateBoostClassifierExp
    //F_VN_CreateBoostClassifierExp2
    //F_VN_CreateKmppModel
    //F_VN_CreateKmppModelExp
    //F_VN_CreateKnnModel
    //F_VN_CreateLbgModel
    //F_VN_CreateLbgModelExp
    //F_VN_CreateLdaTransform
    //F_VN_CreateLdaTransformViaComponentNum
    //F_VN_CreateNbcModel
    //F_VN_CreatePcaTransform
    //F_VN_CreatePcaTransformViaComponentNum
    //F_VN_CreatePcaTransformViaVariance
    //F_VN_CreateRTreesModel
    //F_VN_CreateRTreesModelExp
    //F_VN_CreateRTreesModelExp2
    //F_VN_CreateStaModel
    //F_VN_CreateStaModelExp
    //F_VN_CreateStaModelExp2
    //F_VN_CreateSvmModel
    //F_VN_CreateSvmModelExp
    //F_VN_CreateSvmModelExp2
    //F_VN_CreateSvmSgdClassifier
    //F_VN_CreateSvmSgdClassifierExp
    //F_VN_FeatureScaling
    //F_VN_FeatureScalingExp
    //F_VN_FeatureTransform
    //F_VN_GetBatchClusters
    //F_VN_GetBatchClustersExp
    //F_VN_GetBatchNovelties
    //F_VN_GetClusterCenter
    //F_VN_GetClusterNum
    //F_VN_GetFeatureScales
    //F_VN_GetSampleCluster
    //F_VN_GetSampleClusterExp
    //F_VN_GetSampleNovelty
    //F_VN_InverseFeatureScaling
    //F_VN_InverseFeatureScaling_REAL
    //F_VN_InverseFeatureScalingExp
    //F_VN_InverseFeatureScalingExp_REAL
    //F_VN_InverseFeatureTransform
    //F_VN_PredictBatch
    //F_VN_PredictBatchExp
    //F_VN_PredictSampleClass
    //F_VN_PredictSampleClassExp
    //F_VN_PredictSampleScalar
    //F_VN_PredictSampleScalarExp
    //F_VN_PredictSampleVector
    //F_VN_PredictSampleVectorExp
    //F_VN_TrainBatch
    //F_VN_TrainBatchClusters
    //F_VN_TrainSample
    //F_VN_TrainSampleClass
    //F_VN_TrainSampleCluster
    //F_VN_TrainSampleScalar
    //F_VN_TrainSampleVector

    // Measurement
    //F_VN_AdjustSearchWindowOrientationToLinearEdge
    //F_VN_ClosestPointsBF
    //F_VN_LocateCircularArc
    //F_VN_LocateCircularArcExp
    node_F_VN_LocateEdge : Node_F_VN_LocateEdge;
    node_F_VN_LocateEdgeExp : Node_F_VN_LocateEdgeExp;
    node_F_VN_LocateEdges : Node_F_VN_LocateEdges;
    node_F_VN_LocateEdgesExp : Node_F_VN_LocateEdgesExp;
    node_F_VN_LocateEllipse : Node_F_VN_LocateEllipse;
    //F_VN_LocateEllipseExp
    node_F_VN_MeasureAngleBetweenEdges : Node_F_VN_MeasureAngleBetweenEdges;
    //F_VN_MeasureAngleBetweenEdgesExp
    //F_VN_MeasureEdgeDistance
    //F_VN_MeasureEdgeDistanceExp
    //F_VN_MeasureMinEdgeDistance
    //F_VN_MeasureMinEdgeDistanceExp
    
    // Miscellaneous
    //F_VN_CheckFunctionInitialization
    node_F_VN_ClipLineToBoundary : Node_F_VN_ClipLineToBoundary;
    node_F_VN_ClipLineToBoundary_ITcVnImage : Node_F_VN_ClipLineToBoundary_ITcVnImage;
    node_F_VN_ClipLineToBoundary_TcVnRectangle_DINT : Node_F_VN_ClipLineToBoundary_TcVnRectangle_DINT;
    //F_VN_ConvertITcUnknownToITcVnBitmapExport
    //F_VN_ConvertITcUnknownToITcVnContainer
    //F_VN_ConvertITcUnknownToITcVnImage
    //F_VN_ConvertITcUnknownToITcVnMlModel
    //F_VN_DeinitializeFunction
    //F_VN_GetTimestamp
    node_F_VN_HuMomentInvariants : Node_F_VN_HuMomentInvariants;
    //F_VN_InitMatrixStruct
    node_F_VN_InvertMatrix3x3 : Node_F_VN_InvertMatrix3x3;
    node_F_VN_LineIntersectionPoint : Node_F_VN_LineIntersectionPoint;
    node_F_VN_LineIntersectionPointAndAngle : Node_F_VN_LineIntersectionPointAndAngle;
    //node_F_VN_MultiplyMatrices : Node_F_VN_MultiplyMatrices;
    node_F_VN_RotatedRectangleCorners : Node_F_VN_RotatedRectangleCorners;
    node_F_VN_RotatedRectangleIntersection : Node_F_VN_RotatedRectangleIntersection;
    //F_VN_SetRngSeed
    //F_VN_UpdateTimestamp
    
    // OCR
    //F_VN_OCR
    //F_VN_OCRExp
    
    // Texture Analysis
    //F_VN_Granulometry
    //F_VN_HaralickFeatures
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="RegisterWithNodeFactory" Id="{9eda346d-cc38-44e9-a636-4948bc24f687}">
      <Declaration><![CDATA[METHOD PUBLIC RegisterWithNodeFactory
VAR_INPUT
	NodeFactory : I_NodeFactory;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[// Algebraic Container Operations
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_DINT', node_F_VN_AddToContainerElements_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_INT', node_F_VN_AddToContainerElements_INT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_LREAL', node_F_VN_AddToContainerElements_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_REAL', node_F_VN_AddToContainerElements_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_SINT', node_F_VN_AddToContainerElements_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnKeyPoint', node_F_VN_AddToContainerElements_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnPoint2_DINT', node_F_VN_AddToContainerElements_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnPoint2_LREAL', node_F_VN_AddToContainerElements_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnPoint2_REAL', node_F_VN_AddToContainerElements_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnPoint3_LREAL', node_F_VN_AddToContainerElements_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnPoint3_REAL', node_F_VN_AddToContainerElements_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnRectangle_DINT', node_F_VN_AddToContainerElements_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector2_DINT', node_F_VN_AddToContainerElements_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector2_INT', node_F_VN_AddToContainerElements_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector2_REAL', node_F_VN_AddToContainerElements_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector2_SINT', node_F_VN_AddToContainerElements_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector2_UINT', node_F_VN_AddToContainerElements_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector2_USINT', node_F_VN_AddToContainerElements_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector3_INT', node_F_VN_AddToContainerElements_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector3_REAL', node_F_VN_AddToContainerElements_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector3_SINT', node_F_VN_AddToContainerElements_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector3_UINT', node_F_VN_AddToContainerElements_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector3_USINT', node_F_VN_AddToContainerElements_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector4_DINT', node_F_VN_AddToContainerElements_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector4_INT', node_F_VN_AddToContainerElements_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector4_LREAL', node_F_VN_AddToContainerElements_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector4_SINT', node_F_VN_AddToContainerElements_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector4_UINT', node_F_VN_AddToContainerElements_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_TcVnVector4_USINT', node_F_VN_AddToContainerElements_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_UDINT', node_F_VN_AddToContainerElements_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_UINT', node_F_VN_AddToContainerElements_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_ULINT', node_F_VN_AddToContainerElements_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddToContainerElements/F_VN_AddToContainerElements_USINT', node_F_VN_AddToContainerElements_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_AddContainers', node_F_VN_AddContainers);
//F_VN_BitwiseAndContainers
//F_VN_BitwiseNotContainer
//F_VN_BitwiseOrContainers
//F_VN_BitwiseXorContainers
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_DivideContainers', node_F_VN_DivideContainers);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_DivideContainersExp', node_F_VN_DivideContainersExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MaxContainer', node_F_VN_MaxContainer);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MinContainer', node_F_VN_MinContainer);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MultiplyContainers', node_F_VN_MultiplyContainers);
//NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MultiplyWithContainerElements1', node_F_VN_MultiplyWithContainerElements1);
//NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MultiplyWithContainerElements2', node_F_VN_MultiplyWithContainerElements2);
//NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MultiplyWithContainerElements3', node_F_VN_MultiplyWithContainerElements3);
//NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_MultiplyWithContainerElements4', node_F_VN_MultiplyWithContainerElements4);
//NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_NegateContainer', node_F_VN_NegateContainer);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Container Operations/F_VN_SubtractContainers', node_F_VN_SubtractContainers);

// Algebraic Image Operations
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_AddImages', node_F_VN_AddImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_AddImagesWeighted', node_F_VN_AddImagesWeighted);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_AddImagesWeightedExp', node_F_VN_AddImagesWeightedExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_AddScalarToImage', node_F_VN_AddScalarToImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_AddVectorToImage', node_F_VN_AddVectorToImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseAndImages', node_F_VN_BitwiseAndImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseAndImagesExp', node_F_VN_BitwiseAndImagesExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseAndScalarWithImage', node_F_VN_BitwiseAndScalarWithImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseAndVectorWithImage', node_F_VN_BitwiseAndVectorWithImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseNotImage', node_F_VN_BitwiseNotImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseNotImageExp', node_F_VN_BitwiseNotImageExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseOrImages', node_F_VN_BitwiseOrImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseOrImagesExp', node_F_VN_BitwiseOrImagesExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseOrScalarWithImage', node_F_VN_BitwiseOrScalarWithImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseOrVectorWithImage', node_F_VN_BitwiseOrVectorWithImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseXorImages', node_F_VN_BitwiseXorImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseXorImagesExp', node_F_VN_BitwiseXorImagesExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseXorScalarWithImage', node_F_VN_BitwiseXorScalarWithImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BitwiseXorVectorWithImage', node_F_VN_BitwiseXorVectorWithImage);
//NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_BlendImages', node_F_VN_BlendImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_DivideImageByScalar', node_F_VN_DivideImageByScalar);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_DivideImageByVector', node_F_VN_DivideImageByVector);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_DivideImages', node_F_VN_DivideImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_DivideScalarByImage', node_F_VN_DivideScalarByImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_DivideVectorByImage', node_F_VN_DivideVectorByImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_ElementwiseExp', node_F_VN_ElementwiseExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_ElementwiseLog', node_F_VN_ElementwiseLog);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MaxImage', node_F_VN_MaxImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MaxImageExp', node_F_VN_MaxImageExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MaxImageWithScalar', node_F_VN_MaxImageWithScalar);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MaxImageWithScalarExp', node_F_VN_MaxImageWithScalarExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MaxImageWithVector', node_F_VN_MaxImageWithVector);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MaxImageWithVectorExp', node_F_VN_MaxImageWithVectorExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MinImage', node_F_VN_MinImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MinImageExp', node_F_VN_MinImageExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MinImageWithScalar', node_F_VN_MinImageWithScalar);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MinImageWithScalarExp', node_F_VN_MinImageWithScalarExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MinImageWithVector', node_F_VN_MinImageWithVector);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MinImageWithVectorExp', node_F_VN_MinImageWithVectorExp);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MultiplyImages', node_F_VN_MultiplyImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MultiplyImageWithScalar', node_F_VN_MultiplyImageWithScalar);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_MultiplyImageWithVector', node_F_VN_MultiplyImageWithVector);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_SubtractImageFromScalar', node_F_VN_SubtractImageFromScalar);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_SubtractImageFromVector', node_F_VN_SubtractImageFromVector);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_SubtractImages', node_F_VN_SubtractImages);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_SubtractScalarFromImage', node_F_VN_SubtractScalarFromImage);
NodeFactory.AddNodeAsPrototype('Vision/Algebraic Image Operations/F_VN_SubtractVectorFromImage', node_F_VN_SubtractVectorFromImage);

// Basic Container Operations
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_DINT', node_F_VN_AppendToContainer_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_INT', node_F_VN_AppendToContainer_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ITcVnContainer', node_F_VN_AppendToContainer_ITcVnContainer);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ITcVnForwardIterator', node_F_VN_AppendToContainer_ITcVnForwardIterator);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ITcVnImage', node_F_VN_AppendToContainer_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_LREAL', node_F_VN_AppendToContainer_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_REAL', node_F_VN_AppendToContainer_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_SINT', node_F_VN_AppendToContainer_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnDMatch', node_F_VN_AppendToContainer_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnKeyPoint', node_F_VN_AppendToContainer_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint2_DINT', node_F_VN_AppendToContainer_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint2_LREAL', node_F_VN_AppendToContainer_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint2_REAL', node_F_VN_AppendToContainer_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint3_LREAL', node_F_VN_AppendToContainer_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnPoint3_REAL', node_F_VN_AppendToContainer_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnRectangle_DINT', node_F_VN_AppendToContainer_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_DINT', node_F_VN_AppendToContainer_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_INT', node_F_VN_AppendToContainer_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_REAL', node_F_VN_AppendToContainer_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_SINT', node_F_VN_AppendToContainer_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_UINT', node_F_VN_AppendToContainer_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector2_USINT', node_F_VN_AppendToContainer_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_INT', node_F_VN_AppendToContainer_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_REAL', node_F_VN_AppendToContainer_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_SINT', node_F_VN_AppendToContainer_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_UINT', node_F_VN_AppendToContainer_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector3_USINT', node_F_VN_AppendToContainer_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_DINT', node_F_VN_AppendToContainer_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_INT', node_F_VN_AppendToContainer_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_LREAL', node_F_VN_AppendToContainer_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_SINT', node_F_VN_AppendToContainer_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_UINT', node_F_VN_AppendToContainer_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_TcVnVector4_USINT', node_F_VN_AppendToContainer_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_UDINT', node_F_VN_AppendToContainer_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_UINT', node_F_VN_AppendToContainer_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_ULINT', node_F_VN_AppendToContainer_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_AppendToContainer/F_VN_AppendToContainer_USINT', node_F_VN_AppendToContainer_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_DINT', node_F_VN_FillContainer_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_INT', node_F_VN_FillContainer_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_ITcVnImage', node_F_VN_FillContainer_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_LREAL', node_F_VN_FillContainer_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_REAL', node_F_VN_FillContainer_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_SINT', node_F_VN_FillContainer_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnDMatch', node_F_VN_FillContainer_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnKeyPoint', node_F_VN_FillContainer_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint2_DINT', node_F_VN_FillContainer_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint2_LREAL', node_F_VN_FillContainer_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint2_REAL', node_F_VN_FillContainer_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint3_LREAL', node_F_VN_FillContainer_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnPoint3_REAL', node_F_VN_FillContainer_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnRectangle_DINT', node_F_VN_FillContainer_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_DINT', node_F_VN_FillContainer_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_INT', node_F_VN_FillContainer_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_REAL', node_F_VN_FillContainer_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_SINT', node_F_VN_FillContainer_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_UINT', node_F_VN_FillContainer_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector2_USINT', node_F_VN_FillContainer_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_INT', node_F_VN_FillContainer_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_REAL', node_F_VN_FillContainer_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_SINT', node_F_VN_FillContainer_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_UINT', node_F_VN_FillContainer_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector3_USINT', node_F_VN_FillContainer_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_DINT', node_F_VN_FillContainer_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_INT', node_F_VN_FillContainer_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_LREAL', node_F_VN_FillContainer_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_SINT', node_F_VN_FillContainer_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_UINT', node_F_VN_FillContainer_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_TcVnVector4_USINT', node_F_VN_FillContainer_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_UDINT', node_F_VN_FillContainer_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_UINT', node_F_VN_FillContainer_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_ULINT', node_F_VN_FillContainer_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainer/F_VN_FillContainer_USINT', node_F_VN_FillContainer_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_DINT', node_F_VN_FillContainerExp_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_INT', node_F_VN_FillContainerExp_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_ITcVnImage', node_F_VN_FillContainerExp_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_LREAL', node_F_VN_FillContainerExp_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_REAL', node_F_VN_FillContainerExp_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_SINT', node_F_VN_FillContainerExp_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnDMatch', node_F_VN_FillContainerExp_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnKeyPoint', node_F_VN_FillContainerExp_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnPoint2_DINT', node_F_VN_FillContainerExp_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnPoint2_LREAL', node_F_VN_FillContainerExp_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnPoint2_REAL', node_F_VN_FillContainerExp_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnPoint3_LREAL', node_F_VN_FillContainerExp_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnPoint3_REAL', node_F_VN_FillContainerExp_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnRectangle_DINT', node_F_VN_FillContainerExp_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector2_DINT', node_F_VN_FillContainerExp_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector2_INT', node_F_VN_FillContainerExp_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector2_REAL', node_F_VN_FillContainerExp_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector2_SINT', node_F_VN_FillContainerExp_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector2_UINT', node_F_VN_FillContainerExp_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector2_USINT', node_F_VN_FillContainerExp_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector3_INT', node_F_VN_FillContainerExp_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector3_REAL', node_F_VN_FillContainerExp_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector3_SINT', node_F_VN_FillContainerExp_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector3_UINT', node_F_VN_FillContainerExp_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector3_USINT', node_F_VN_FillContainerExp_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector4_DINT', node_F_VN_FillContainerExp_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector4_INT', node_F_VN_FillContainerExp_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector4_LREAL', node_F_VN_FillContainerExp_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector4_SINT', node_F_VN_FillContainerExp_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector4_UINT', node_F_VN_FillContainerExp_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_TcVnVector4_USINT', node_F_VN_FillContainerExp_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_UDINT', node_F_VN_FillContainerExp_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_UINT', node_F_VN_FillContainerExp_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_ULINT', node_F_VN_FillContainerExp_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_FillContainerExp/F_VN_FillContainerExp_USINT', node_F_VN_FillContainerExp_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_DINT', node_F_VN_GetAt_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_INT', node_F_VN_GetAt_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_ITcVnContainer', node_F_VN_GetAt_ITcVnContainer);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_ITcVnImage', node_F_VN_GetAt_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_LREAL', node_F_VN_GetAt_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_REAL', node_F_VN_GetAt_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_SINT', node_F_VN_GetAt_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnDMatch', node_F_VN_GetAt_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnKeyPoint', node_F_VN_GetAt_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnPoint2_DINT', node_F_VN_GetAt_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnPoint2_LREAL', node_F_VN_GetAt_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnPoint2_REAL', node_F_VN_GetAt_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnPoint3_LREAL', node_F_VN_GetAt_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnPoint3_REAL', node_F_VN_GetAt_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnRectangle_DINT', node_F_VN_GetAt_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector2_DINT', node_F_VN_GetAt_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector2_INT', node_F_VN_GetAt_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector2_REAL', node_F_VN_GetAt_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector2_SINT', node_F_VN_GetAt_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector2_UINT', node_F_VN_GetAt_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector2_USINT', node_F_VN_GetAt_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector3_INT', node_F_VN_GetAt_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector3_REAL', node_F_VN_GetAt_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector3_SINT', node_F_VN_GetAt_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector3_UINT', node_F_VN_GetAt_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector3_USINT', node_F_VN_GetAt_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector4_DINT', node_F_VN_GetAt_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector4_INT', node_F_VN_GetAt_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector4_LREAL', node_F_VN_GetAt_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector4_SINT', node_F_VN_GetAt_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector4_UINT', node_F_VN_GetAt_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_TcVnVector4_USINT', node_F_VN_GetAt_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_UDINT', node_F_VN_GetAt_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_UINT', node_F_VN_GetAt_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_ULINT', node_F_VN_GetAt_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetAt/F_VN_GetAt_USINT', node_F_VN_GetAt_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_DINT', node_F_VN_InsertIntoContainer_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_INT', node_F_VN_InsertIntoContainer_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ITcVnContainer', node_F_VN_InsertIntoContainer_ITcVnContainer);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ITcVnForwardIterator', node_F_VN_InsertIntoContainer_ITcVnForwardIterator);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ITcVnImage', node_F_VN_InsertIntoContainer_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_LREAL', node_F_VN_InsertIntoContainer_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_REAL', node_F_VN_InsertIntoContainer_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_SINT', node_F_VN_InsertIntoContainer_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnDMatch', node_F_VN_InsertIntoContainer_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnKeyPoint', node_F_VN_InsertIntoContainer_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint2_DINT', node_F_VN_InsertIntoContainer_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint2_LREAL', node_F_VN_InsertIntoContainer_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint2_REAL', node_F_VN_InsertIntoContainer_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint3_LREAL', node_F_VN_InsertIntoContainer_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnPoint3_REAL', node_F_VN_InsertIntoContainer_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnRectangle_DINT', node_F_VN_InsertIntoContainer_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_DINT', node_F_VN_InsertIntoContainer_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_INT', node_F_VN_InsertIntoContainer_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_REAL', node_F_VN_InsertIntoContainer_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_SINT', node_F_VN_InsertIntoContainer_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_UINT', node_F_VN_InsertIntoContainer_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector2_USINT', node_F_VN_InsertIntoContainer_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_INT', node_F_VN_InsertIntoContainer_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_REAL', node_F_VN_InsertIntoContainer_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_SINT', node_F_VN_InsertIntoContainer_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_UINT', node_F_VN_InsertIntoContainer_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector3_USINT', node_F_VN_InsertIntoContainer_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_DINT', node_F_VN_InsertIntoContainer_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_INT', node_F_VN_InsertIntoContainer_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_LREAL', node_F_VN_InsertIntoContainer_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_SINT', node_F_VN_InsertIntoContainer_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_UINT', node_F_VN_InsertIntoContainer_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_TcVnVector4_USINT', node_F_VN_InsertIntoContainer_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_UDINT', node_F_VN_InsertIntoContainer_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_UINT', node_F_VN_InsertIntoContainer_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_ULINT', node_F_VN_InsertIntoContainer_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_InsertIntoContainer/F_VN_InsertIntoContainer_USINT', node_F_VN_InsertIntoContainer_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_DINT', node_F_VN_SetAt_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_INT', node_F_VN_SetAt_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_ITcVnContainer', node_F_VN_SetAt_ITcVnContainer);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_ITcVnImage', node_F_VN_SetAt_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_LREAL', node_F_VN_SetAt_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_REAL', node_F_VN_SetAt_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_SINT', node_F_VN_SetAt_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnDMatch', node_F_VN_SetAt_TcVnDMatch);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnKeyPoint', node_F_VN_SetAt_TcVnKeyPoint);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint2_DINT', node_F_VN_SetAt_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint2_LREAL', node_F_VN_SetAt_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint2_REAL', node_F_VN_SetAt_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint3_LREAL', node_F_VN_SetAt_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnPoint3_REAL', node_F_VN_SetAt_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnRectangle_DINT', node_F_VN_SetAt_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_DINT', node_F_VN_SetAt_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_INT', node_F_VN_SetAt_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_REAL', node_F_VN_SetAt_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_SINT', node_F_VN_SetAt_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_UINT', node_F_VN_SetAt_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector2_USINT', node_F_VN_SetAt_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_INT', node_F_VN_SetAt_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_REAL', node_F_VN_SetAt_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_SINT', node_F_VN_SetAt_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_UINT', node_F_VN_SetAt_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector3_USINT', node_F_VN_SetAt_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_DINT', node_F_VN_SetAt_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_INT', node_F_VN_SetAt_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_LREAL', node_F_VN_SetAt_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_SINT', node_F_VN_SetAt_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_UINT', node_F_VN_SetAt_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_TcVnVector4_USINT', node_F_VN_SetAt_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_UDINT', node_F_VN_SetAt_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_UINT', node_F_VN_SetAt_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_ULINT', node_F_VN_SetAt_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_SetAt/F_VN_SetAt_USINT', node_F_VN_SetAt_USINT);

//F_VN_AdvanceIterator
//F_VN_CheckIfEmpty
//F_VN_CheckIfIteratorIsAtEnd
//F_VN_ConvertContainerType
//F_VN_CopyContainer
//F_VN_CopyContainerElementsConditional_ITcVnContainer
//F_VN_CopyContainerElementsConditional_ITcVnForwardIterator
//F_VN_CreateContainer
//F_VN_CreateContainerFromArray
//F_VN_EraseFromContainer
//F_VN_ExportContainer
//F_VN_ExportContainer_String
//F_VN_ExportContainerSize
//F_VN_ExportSubContainer
//F_VN_ExportSubContainer_String
//F_VN_ExportSubContainerSize
//F_VN_ExtractContainerRange
//F_VN_GetContainer
//F_VN_GetContainerExp
//F_VN_GetForwardIterator
NodeFactory.AddNodeAsPrototype('Vision/Basic Container Operations/F_VN_GetNumberOfElements', node_F_VN_GetNumberOfElements);
//F_VN_GetRandomAccessIterator
//F_VN_IncrementIterator
//F_VN_IteratorDistance
//F_VN_ReserveContainerMemory
//F_VN_ReverseContainer
//F_VN_SetContainer
//F_VN_SetIteratorToBegin

// Basic Image Operations
//F_VN_CombineImageChannels
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_ConvertElementType', node_F_VN_ConvertElementType);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_ConvertElementTypeExp', node_F_VN_ConvertElementTypeExp);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CopyImage', node_F_VN_CopyImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CopyImageRegion', node_F_VN_CopyImageRegion);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CopyImageRegionToRegion', node_F_VN_CopyImageRegionToRegion);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CopyIntoDisplayableImage', node_F_VN_CopyIntoDisplayableImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CreateAssociatedImage', node_F_VN_CreateAssociatedImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CreateEmptyImage', node_F_VN_CreateEmptyImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CreateImage', node_F_VN_CreateImage);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_CreateImageAndSetPixels', node_F_VN_CreateImageAndSetPixels);
//F_VN_CreateImageFromArray
//F_VN_ExportImage
//F_VN_ExportImageAsBmp
//F_VN_ExportImageAsBmpExp
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_ExportImageAsBmpSize', node_F_VN_ExportImageAsBmpSize);
//F_VN_ExportImageAsBmpSizeExp
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_ExportImageSize', node_F_VN_ExportImageSize);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_FuseImages', node_F_VN_FuseImages);
//F_VN_FuseImagesArray
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageChannel', node_F_VN_GetImageChannel);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageHeight', node_F_VN_GetImageHeight);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageInfo', node_F_VN_GetImageInfo);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetImageWidth', node_F_VN_GetImageWidth);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetPixel', node_F_VN_GetPixel);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetPixelFormat', node_F_VN_GetPixelFormat);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_GetRoi', node_F_VN_GetRoi);
//F_VN_MixImageChannels
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_ResetRoi', node_F_VN_ResetRoi);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetImageChannel', node_F_VN_SetImageChannel);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetPixel', node_F_VN_SetPixel);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetPixels', node_F_VN_SetPixels);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetPixelsExp', node_F_VN_SetPixelsExp);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetRoi', node_F_VN_SetRoi);
//NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetRoi_TcVnRectangle_DINT', node_F_VN_SetRoi_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_SetRoi_TcVnRectangle_UDINT', node_F_VN_SetRoi_TcVnRectangle_UDINT);
//F_VN_SplitImageChannels
//NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_TransformIntoDisplayableImage', node_F_VN_TransformIntoDisplayableImage); 
//NodeFactory.AddNodeAsPrototype('Vision/Basic Image Operations/F_VN_TransformIntoDisplayableImageExp', node_F_VN_TransformIntoDisplayableImageExp); 

// Code Quality
//F_VN_GradeBarcode
//F_VN_GradeBarcodeExp
//F_VN_GradeDataMatrixCode
//F_VN_GradeDataMatrixCodeExp
//F_VN_GradeQRCode
//F_VN_GradeQRCodeExp

// Code Reading
NodeFactory.AddNodeAsPrototype('Vision/Code Reading/F_VN_ReadBarcode', node_F_VN_ReadBarcode);
//F_VN_ReadBarcodeExp
//F_VN_ReadBarcodeExp2
NodeFactory.AddNodeAsPrototype('Vision/Code Reading/F_VN_ReadDataMatrixCode', node_F_VN_ReadDataMatrixCode);
//F_VN_ReadDataMatrixCodeExp
//F_VN_ReadDataMatrixCodeExp2
NodeFactory.AddNodeAsPrototype('Vision/Code Reading/F_VN_ReadPharmaCode', node_F_VN_ReadPharmaCode);
//F_VN_ReadPharmaCodeExp
//F_VN_ReadPharmaCodeExp2
NodeFactory.AddNodeAsPrototype('Vision/Code Reading/F_VN_ReadQRCode', node_F_VN_ReadQRCode);
//F_VN_ReadQRCodeExp
//F_VN_ReadQRCodeExp2

// Constants
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_BLACK', node_RGBA_BLACK);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_RED', node_RGBA_RED);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_YELLOW', node_RGBA_YELLOW);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_GREEN', node_RGBA_GREEN);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_CYAN', node_RGBA_CYAN);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_BLUE', node_RGBA_BLUE);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_MAGENTA', node_RGBA_MAGENTA);
NodeFactory.AddNodeAsPrototype('Vision/Constants/RGBA_WHITE', node_RGBA_WHITE);

// Container Statistics
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_DINT', node_F_VN_MaxElementElementwise_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_INT', node_F_VN_MaxElementElementwise_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_LREAL', node_F_VN_MaxElementElementwise_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_REAL', node_F_VN_MaxElementElementwise_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_SINT', node_F_VN_MaxElementElementwise_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnPoint2_DINT', node_F_VN_MaxElementElementwise_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnPoint2_LREAL', node_F_VN_MaxElementElementwise_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnPoint2_REAL', node_F_VN_MaxElementElementwise_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnPoint3_LREAL', node_F_VN_MaxElementElementwise_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnPoint3_REAL', node_F_VN_MaxElementElementwise_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector2_DINT', node_F_VN_MaxElementElementwise_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector2_INT', node_F_VN_MaxElementElementwise_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector2_REAL', node_F_VN_MaxElementElementwise_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector2_SINT', node_F_VN_MaxElementElementwise_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector2_UINT', node_F_VN_MaxElementElementwise_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector2_USINT', node_F_VN_MaxElementElementwise_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector3_INT', node_F_VN_MaxElementElementwise_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector3_REAL', node_F_VN_MaxElementElementwise_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector3_SINT', node_F_VN_MaxElementElementwise_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector3_UINT', node_F_VN_MaxElementElementwise_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector3_USINT', node_F_VN_MaxElementElementwise_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector4_DINT', node_F_VN_MaxElementElementwise_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector4_INT', node_F_VN_MaxElementElementwise_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector4_LREAL', node_F_VN_MaxElementElementwise_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector4_SINT', node_F_VN_MaxElementElementwise_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector4_UINT', node_F_VN_MaxElementElementwise_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_TcVnVector4_USINT', node_F_VN_MaxElementElementwise_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_UDINT', node_F_VN_MaxElementElementwise_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_UINT', node_F_VN_MaxElementElementwise_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_ULINT', node_F_VN_MaxElementElementwise_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MaxElementElementwise/F_VN_MaxElementElementwise_USINT', node_F_VN_MaxElementElementwise_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_DINT', node_F_VN_MedianElementElementwise_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_INT', node_F_VN_MedianElementElementwise_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_LREAL', node_F_VN_MedianElementElementwise_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_REAL', node_F_VN_MedianElementElementwise_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_SINT', node_F_VN_MedianElementElementwise_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnPoint2_DINT', node_F_VN_MedianElementElementwise_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnPoint2_LREAL', node_F_VN_MedianElementElementwise_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnPoint2_REAL', node_F_VN_MedianElementElementwise_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnPoint3_LREAL', node_F_VN_MedianElementElementwise_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnPoint3_REAL', node_F_VN_MedianElementElementwise_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector2_DINT', node_F_VN_MedianElementElementwise_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector2_INT', node_F_VN_MedianElementElementwise_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector2_REAL', node_F_VN_MedianElementElementwise_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector2_SINT', node_F_VN_MedianElementElementwise_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector2_UINT', node_F_VN_MedianElementElementwise_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector2_USINT', node_F_VN_MedianElementElementwise_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector3_INT', node_F_VN_MedianElementElementwise_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector3_REAL', node_F_VN_MedianElementElementwise_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector3_SINT', node_F_VN_MedianElementElementwise_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector3_UINT', node_F_VN_MedianElementElementwise_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector3_USINT', node_F_VN_MedianElementElementwise_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector4_DINT', node_F_VN_MedianElementElementwise_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector4_INT', node_F_VN_MedianElementElementwise_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector4_LREAL', node_F_VN_MedianElementElementwise_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector4_SINT', node_F_VN_MedianElementElementwise_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector4_UINT', node_F_VN_MedianElementElementwise_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_TcVnVector4_USINT', node_F_VN_MedianElementElementwise_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_UDINT', node_F_VN_MedianElementElementwise_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_UINT', node_F_VN_MedianElementElementwise_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_ULINT', node_F_VN_MedianElementElementwise_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MedianElementElementwise/F_VN_MedianElementElementwise_USINT', node_F_VN_MedianElementElementwise_USINT);

NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_DINT', node_F_VN_MinElementElementwise_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_INT', node_F_VN_MinElementElementwise_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_LREAL', node_F_VN_MinElementElementwise_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_REAL', node_F_VN_MinElementElementwise_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_SINT', node_F_VN_MinElementElementwise_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnPoint2_DINT', node_F_VN_MinElementElementwise_TcVnPoint2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnPoint2_LREAL', node_F_VN_MinElementElementwise_TcVnPoint2_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnPoint2_REAL', node_F_VN_MinElementElementwise_TcVnPoint2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnPoint3_LREAL', node_F_VN_MinElementElementwise_TcVnPoint3_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnPoint3_REAL', node_F_VN_MinElementElementwise_TcVnPoint3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector2_DINT', node_F_VN_MinElementElementwise_TcVnVector2_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector2_INT', node_F_VN_MinElementElementwise_TcVnVector2_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector2_REAL', node_F_VN_MinElementElementwise_TcVnVector2_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector2_SINT', node_F_VN_MinElementElementwise_TcVnVector2_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector2_UINT', node_F_VN_MinElementElementwise_TcVnVector2_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector2_USINT', node_F_VN_MinElementElementwise_TcVnVector2_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector3_INT', node_F_VN_MinElementElementwise_TcVnVector3_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector3_REAL', node_F_VN_MinElementElementwise_TcVnVector3_REAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector3_SINT', node_F_VN_MinElementElementwise_TcVnVector3_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector3_UINT', node_F_VN_MinElementElementwise_TcVnVector3_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector3_USINT', node_F_VN_MinElementElementwise_TcVnVector3_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector4_DINT', node_F_VN_MinElementElementwise_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector4_INT', node_F_VN_MinElementElementwise_TcVnVector4_INT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector4_LREAL', node_F_VN_MinElementElementwise_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector4_SINT', node_F_VN_MinElementElementwise_TcVnVector4_SINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector4_UINT', node_F_VN_MinElementElementwise_TcVnVector4_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_TcVnVector4_USINT', node_F_VN_MinElementElementwise_TcVnVector4_USINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_UDINT', node_F_VN_MinElementElementwise_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_UINT', node_F_VN_MinElementElementwise_UINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_ULINT', node_F_VN_MinElementElementwise_ULINT);
NodeFactory.AddNodeAsPrototype('Vision/Container Statistics/F_VN_MinElementElementwise/F_VN_MinElementElementwise_USINT', node_F_VN_MinElementElementwise_USINT);
//F_VN_ContainerAverage
//F_VN_ContainerAverageElementwise2
//F_VN_ContainerAverageElementwise3
//F_VN_ContainerAverageElementwise4
//F_VN_ContainerAverageVariance
//F_VN_ContainerAverageVarianceElementwise2
//F_VN_ContainerAverageVarianceElementwise3
//F_VN_ContainerAverageVarianceElementwise4
//F_VN_MaxElement
//F_VN_MedianElement
//F_VN_MinElement

// Contour Analysis
//F_VN_ApproximatePolygon
//F_VN_CheckIfPointIsInsideContour
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourArea', node_F_VN_ContourArea);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourCenterOfMass', node_F_VN_ContourCenterOfMass);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourCircularity', node_F_VN_ContourCircularity);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourConvexity', node_F_VN_ContourConvexity);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourEccentricity', node_F_VN_ContourEccentricity);
//F_VN_ContourElongation
//F_VN_ContourExtremePoint
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourInertiaRatio', node_F_VN_ContourInertiaRatio);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourMoments', node_F_VN_ContourMoments);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourOrientation', node_F_VN_ContourOrientation);
//F_VN_ContourOrientationExp
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourPerimeter', node_F_VN_ContourPerimeter);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_ContourRoundness', node_F_VN_ContourRoundness);
//F_VN_ConvexHullPoints
//F_VN_ConvexHullPointsExp
//F_VN_ConvexityDefects
//F_VN_CustomElementWiseContainerOperation_ITcVnContainer
//F_VN_CustomElementWiseContainerOperation_ITcVnForwardIterator
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_EnclosingCircle', node_F_VN_EnclosingCircle);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_EnclosingRectangle', node_F_VN_EnclosingRectangle);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_EnclosingTriangle', node_F_VN_EnclosingTriangle);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_FitEllipse', node_F_VN_FitEllipse);
NodeFactory.AddNodeAsPrototype('Vision/Contour Analysis/F_VN_FitLine', node_F_VN_FitLine);
//F_VN_FitLineExp
//F_VN_FourierDescriptors
//F_VN_MatchContours
//F_VN_MatchContours1vsN
//F_VN_MatchContours1vsNExp
//F_VN_MatchContoursExp
//F_VN_UprightBoundingRectangle

// Control Functions
//F_VN_StartAbsWatchdog
//F_VN_StartAbsWatchdogExp
//F_VN_StartRelWatchdog
//F_VN_StartRelWatchdogExp
//F_VN_StopWatchdog
    
// Drawing
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawArrow', node_F_VN_DrawArrow);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawArrow_TcVnVector4_DINT', node_F_VN_DrawArrow_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawArrowExp', node_F_VN_DrawArrowExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawArrowExp_TcVnVector4_DINT', node_F_VN_DrawArrowExp_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawCircle', node_F_VN_DrawCircle);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawCircleExp', node_F_VN_DrawCircleExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawCircles', node_F_VN_DrawCircles);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawCirclesExp', node_F_VN_DrawCirclesExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawCircularArc', node_F_VN_DrawCircularArc);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawCircularArcExp', node_F_VN_DrawCircularArcExp);
//F_VN_DrawComponents
//F_VN_DrawComponentsExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawContours', node_F_VN_DrawContours);
//F_VN_DrawContoursExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawEllipse', node_F_VN_DrawEllipse);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawEllipseExp', node_F_VN_DrawEllipseExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawKeypoints', node_F_VN_DrawKeypoints);
//F_VN_DrawKeypointsExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLine', node_F_VN_DrawLine);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLine_TcVnVector4_DINT', node_F_VN_DrawLine_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLine_TcVnVector4_LREAL', node_F_VN_DrawLine_TcVnVector4_LREAL);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLineExp', node_F_VN_DrawLineExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLineExp_TcVnVector4_DINT', node_F_VN_DrawLineExp_TcVnVector4_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawLineExp_TcVnVector4_LREAL', node_F_VN_DrawLineExp_TcVnVector4_LREAL);
//F_VN_DrawLines
//F_VN_DrawLinesExp
//F_VN_DrawMatches
//F_VN_DrawMatchesExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawOrientation', node_F_VN_DrawOrientation);
//F_VN_DrawOrientationExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawPoint', node_F_VN_DrawPoint);
//F_VN_DrawPointExp
//F_VN_DrawPoints
//F_VN_DrawPointsExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawPolygon', node_F_VN_DrawPolygon);
//F_VN_DrawPolygonExp
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawRectangle', node_F_VN_DrawRectangle);
//NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawRectangle_TcVnRectangle_DINT', node_F_VN_DrawRectangle_TcVnRectangle_DINT);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawRectangle_TcVnRectangle_UDINT', node_F_VN_DrawRectangle_TcVnRectangle_UDINT);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawRotatedRectangle', node_F_VN_DrawRotatedRectangle);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_DrawRotatedRectangleExp', node_F_VN_DrawRotatedRectangleExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_FillCircle', node_F_VN_FillCircle);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_FillContours', node_F_VN_FillContours);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_FillEllipse', node_F_VN_FillEllipse);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_FillPolygon', node_F_VN_FillPolygon);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_FillRectangle', node_F_VN_FillRectangle);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_FillRotatedRectangle', node_F_VN_FillRotatedRectangle);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PlotIntensityProfile', node_F_VN_PlotIntensityProfile);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PlotIntensityProfileExp', node_F_VN_PlotIntensityProfileExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PutLabel', node_F_VN_PutLabel);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PutLabelExp', node_F_VN_PutLabelExp);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PutText', node_F_VN_PutText);
NodeFactory.AddNodeAsPrototype('Vision/Drawing/F_VN_PutTextExp', node_F_VN_PutTextExp);

// Fourier Analysis
//F_VN_CreateBandpassButterworthFilter
//F_VN_CreateBandpassGaussianFilter
//F_VN_CreateBandrejectButterworthFilter
//F_VN_CreateBandrejectGaussianFilter
//F_VN_CreateHighpassButterworthFilter
//F_VN_CreateHighpassGaussianFilter
//F_VN_CreateLowpassButterworthFilter
//F_VN_CreateLowpassGaussianFilter
//F_VN_Dft
//F_VN_InverseDft
//F_VN_OptimalDftSize
NodeFactory.AddNodeAsPrototype('Vision/Fourier Analysis/F_VN_PadImageBorder', node_F_VN_PadImageBorder);
NodeFactory.AddNodeAsPrototype('Vision/Fourier Analysis/F_VN_PadImageBorderExp', node_F_VN_PadImageBorderExp);

// Geometric and Coordinate Transformations
//F_VN_CalibrateCamera
//F_VN_CalibrateCameraExp
//F_VN_CalibrateCameraExp2
//F_VN_CalibrateCameraExp3
//F_VN_CalibrateCameraManually
//F_VN_CalibrateCameraManuallyExp
//F_VN_CalibrateCameraPlanar
//F_VN_CalibrateCameraPlanarExp
//F_VN_CalibrateLinescanCamera
//F_VN_CalibrateLinescanCameraExp
//F_VN_CompensateLensDistortion
//F_VN_CompensateLensDistortionExp1
//F_VN_CompensateLensDistortionExp2
//F_VN_CompensateLensDistortionForPoints
//F_VN_CompensateLensDistortionForPointsExp1
//F_VN_CompensateLensDistortionForPointsExp2
//F_VN_DetectPatternPoints
//F_VN_DetectPatternPointsExp
//F_VN_GenerateCalibrationPatternReferencePoints
//F_VN_ImagePointsWorldDistance
//F_VN_SolvePnP
//F_VN_SolvePnPExp
//F_VN_SortDetectedPatternPoints
//F_VN_TransformCoordinatesImageToWorld_Container
//F_VN_TransformCoordinatesImageToWorld_Point
//F_VN_TransformCoordinatesPlanar_Container
//F_VN_TransformCoordinatesPlanar_Point
//F_VN_TransformCoordinatesWorldToImage_Container
//F_VN_TransformCoordinatesWorldToImage_Point
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_AlignRotatedImageRegion', node_F_VN_AlignRotatedImageRegion);
//F_VN_AlignRotatedImageRegionExp
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyRotationToAffineTransformation', node_F_VN_ApplyRotationToAffineTransformation);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyRotationToAffineTransformationExp', node_F_VN_ApplyRotationToAffineTransformationExp);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyScalingToAffineTransformation', node_F_VN_ApplyScalingToAffineTransformation);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyScalingToAffineTransformationExp', node_F_VN_ApplyScalingToAffineTransformationExp);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyTranslationToAffineTransformation', node_F_VN_ApplyTranslationToAffineTransformation);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyTranslationToAffineTransformationExp', node_F_VN_ApplyTranslationToAffineTransformationExp);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyYAxisInversionToAffineTransformation', node_F_VN_ApplyYAxisInversionToAffineTransformation);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ApplyYAxisInversionToAffineTransformationExp', node_F_VN_ApplyYAxisInversionToAffineTransformationExp);
//F_VN_ConvertCartesianToPolarAngleImage
//F_VN_ConvertCartesianToPolarAngleImageExp
//F_VN_ConvertCartesianToPolarAngles
//F_VN_ConvertCartesianToPolarAnglesExp
//F_VN_ConvertCartesianToPolarImages
//F_VN_ConvertCartesianToPolarImagesExp
//F_VN_ConvertCartesianToPolarMagnitudeImage
//F_VN_ConvertCartesianToPolarMagnitudes
//F_VN_ConvertCartesianToPolarPoints
//F_VN_ConvertCartesianToPolarPointsExp
//F_VN_ConvertPolarToCartesianImages
//F_VN_ConvertPolarToCartesianImagesExp
//F_VN_ConvertPolarToCartesianPoints
//F_VN_ConvertPolarToCartesianPointsExp
//F_VN_DecomposeAffineTransformation
//F_VN_DecomposeAffineTransformationExp
//F_VN_DecomposeHomography
//F_VN_DecomposeHomographyExp
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_FlipImage', node_F_VN_FlipImage);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_GenerateAffineTransformationUnitMatrix2D', node_F_VN_GenerateAffineTransformationUnitMatrix2D);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_GetAffineTransformation', node_F_VN_GetAffineTransformation);
//F_VN_GetAffineTransformation2D
//F_VN_GetAffineTransformation2DExp
//F_VN_GetPerspectiveTransformation
//F_VN_Homography
//F_VN_HomographyExp
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_InvertAffineTransformation', node_F_VN_InvertAffineTransformation);
//F_VN_PerspectiveTransformation
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_PyramidDown', node_F_VN_PyramidDown);
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_PyramidUp', node_F_VN_PyramidUp);
//F_VN_RemapImageToLogPolarSpace
//F_VN_RemapImageToLogPolarSpaceExp
//F_VN_RemapImageToLogPolarSpaceExp2
//F_VN_RemapImageToPolarSpace
//F_VN_RemapImageToPolarSpaceExp
//F_VN_RemapImageToPolarSpaceExp2
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_ResizeImage', node_F_VN_ResizeImage);
//F_VN_ResizeImageExp
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_RotateImage', node_F_VN_RotateImage);
//F_VN_RotateImageExp
//F_VN_RotateImageExp2
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_WarpAffine', node_F_VN_WarpAffine);
//F_VN_WarpAffine_Container
//F_VN_WarpAffine_Point
//F_VN_WarpAffine_Rectangle
//F_VN_WarpAffineExp
NodeFactory.AddNodeAsPrototype('Vision/Geometric and Coordinate Transformations/F_VN_WarpPerspective', node_F_VN_WarpPerspective);
//F_VN_WarpPerspective_Container
//F_VN_WarpPerspective_Point
//F_VN_WarpPerspective_Rectangle
//F_VN_WarpPerspectiveExp

// Image Analysis
//F_VN_AdjustActiveContour
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/Object Detection/F_VN_DetectBlobs', node_F_VN_DetectBlobs);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/Object Detection/F_VN_DetectBlobsExp', node_F_VN_DetectBlobsExp);
//F_VN_FindContourHierarchyExp
//F_VN_FindContours
//F_VN_FindContoursExp
//F_VN_HoughCircles
//F_VN_HoughCirclesExp
//F_VN_HoughLines
//F_VN_HoughLinesExp
//F_VN_HoughLinesP
//F_VN_HoughLinesPExp
//F_VN_MatchImageHuMoments
//F_VN_MatchTemplate
//F_VN_MatchTemplateAndEvaluate
//F_VN_MatchTemplateAndEvaluateExp
//F_VN_MatchTemplateExp
//F_VN_CannyEdgeDetection
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_CannyEdgeDetection', node_F_VN_CannyEdgeDetection);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_CannyEdgeDetectionExp', node_F_VN_CannyEdgeDetectionExp);
//F_VN_ConnectedComponents
//F_VN_ConnectedComponentsExp
//F_VN_ConnectedComponentsWithStats
//F_VN_ConnectedComponentsWithStatsExp
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_CountNonZeroPixels', node_F_VN_CountNonZeroPixels);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_DistanceTransformation', node_F_VN_DistanceTransformation);
//F_VN_DistanceTransformationExp
//F_VN_GetConnectedComponent
//F_VN_GetConnectedComponentExp
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageAverage', node_F_VN_ImageAverage);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageAverageExp', node_F_VN_ImageAverageExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageAverageStdDev', node_F_VN_ImageAverageStdDev);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageAverageStdDevExp', node_F_VN_ImageAverageStdDevExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageCenterOfMass', node_F_VN_ImageCenterOfMass);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageCenterOfMassExp', node_F_VN_ImageCenterOfMassExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageMedian', node_F_VN_ImageMedian);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageMedianExp', node_F_VN_ImageMedianExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_ImageMoments', node_F_VN_ImageMoments);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_MaxPixelValue', node_F_VN_MaxPixelValue);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_MaxPixelValueExp', node_F_VN_MaxPixelValueExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_MinPixelValue', node_F_VN_MinPixelValue);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_MinPixelValueExp', node_F_VN_MinPixelValueExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_RegionOrientation', node_F_VN_RegionOrientation);
NodeFactory.AddNodeAsPrototype('Vision/Image Analysis/F_VN_RegionOrientationExp', node_F_VN_RegionOrientationExp);

// Image Color and Contrast Processing
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_ApplyColorMap', node_F_VN_ApplyColorMap);
//F_VN_ApplyLut
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_Clahe', node_F_VN_Clahe);
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_ClaheExp', node_F_VN_ClaheExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_ConvertColorSpace', node_F_VN_ConvertColorSpace);
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_GenerateColorMap', node_F_VN_GenerateColorMap);
//F_VN_GenerateCustomColorMap
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_Histogram', node_F_VN_Histogram);
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_HistogramEqualization', node_F_VN_HistogramEqualization);
//F_VN_HistogramEqualizationExp
//F_VN_HistogramExp
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_InvertImageColor', node_F_VN_InvertImageColor);
//F_VN_InvertImageColorExp
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_NormalizeImage', node_F_VN_NormalizeImage);
//F_VN_NormalizeImageExp
NodeFactory.AddNodeAsPrototype('Vision/Image Color and Contrast Processing/F_VN_NormalizeImageForDisplay', node_F_VN_NormalizeImageForDisplay);
//F_VN_ReferenceColorSimilarity_ITcVnColorModel
//F_VN_ReferenceColorSimilarity_ITcVnMlModel
//F_VN_ReferenceColorSimilarity_TcVnVector3_LREAL
//F_VN_ReferenceColorSimilarityExp_ITcVnColorModel
//F_VN_ReferenceColorSimilarityExp_ITcVnMlModel
//F_VN_ReferenceColorSimilarityExp_TcVnVector3_LREAL
//F_VN_TrainImageColor
//F_VN_TrainImageColor_ITcVnMlModel
//F_VN_TrainImageColorExp
//F_VN_TrainImageColorExp_ITcVnMlModel
//F_VN_TrainImageColorExp2
//F_VN_TrainImageColorExp2_ITcVnMlModel
//F_VN_WhiteBalance

// Image Filtering
//F_VN_BilateralFilter
//F_VN_BilateralFilterExp
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_BoxFilter', node_F_VN_BoxFilter);
//F_VN_BoxFilterExp
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_BrightBorderObjects', node_F_VN_BrightBorderObjects);
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_CreateStructuringElement', node_F_VN_CreateStructuringElement);
//F_VN_CustomFilter
//F_VN_CustomFilterExp
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_DarkBorderObjects', node_F_VN_DarkBorderObjects);
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_FillHoles', node_F_VN_FillHoles);
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_GaussianFilter', node_F_VN_GaussianFilter);
//F_VN_GaussianFilterExp
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_LaplacianFilter', node_F_VN_LaplacianFilter);
//F_VN_LaplacianFilterExp
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_LocalMaxima', node_F_VN_LocalMaxima);
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_LocalMinima', node_F_VN_LocalMinima);
//F_VN_MedianFilter
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_MorphologicalOperator', node_F_VN_MorphologicalOperator);
//F_VN_RemoveLocalMaxima
//F_VN_RemoveLocalMinima
//F_VN_ScharrFilter
//F_VN_ScharrFilterExp
//F_VN_SeparableCustomFilter
//F_VN_SeparableCustomFilterExp
//F_VN_SobelFilter
//F_VN_SobelFilterExp
NodeFactory.AddNodeAsPrototype('Vision/Image Filtering/F_VN_VarianceFilter', node_F_VN_VarianceFilter);
//F_VN_VarianceFilterExp
    
// Image Segmentation
NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_AdaptiveThreshold', node_F_VN_AdaptiveThreshold);
NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_AdaptiveThresholdExp', node_F_VN_AdaptiveThresholdExp);
NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_CheckColorRange', node_F_VN_CheckColorRange);
//NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_DoubleThreshold', node_F_VN_DoubleThreshold);
NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_Threshold', node_F_VN_Threshold);
NodeFactory.AddNodeAsPrototype('Vision/Image Segmentation/F_VN_WatershedSegmentationExp', node_F_VN_WatershedSegmentationExp);

// Keypoint Features
//F_VN_FilterGoodMatches
//F_VN_FindReferenceKeyPointsInImage
//F_VN_FindReferenceKeyPointsInImageAKAZE
//F_VN_FindReferenceKeyPointsInImageAKAZEExp
//F_VN_FindReferenceKeyPointsInImageBRISK
//F_VN_FindReferenceKeyPointsInImageBRISKExp
//F_VN_FindReferenceKeyPointsInImageExp
//F_VN_FindReferenceKeyPointsInImageORB
//F_VN_FindReferenceKeyPointsInImageORBExp
//F_VN_GetMatchCoordinates
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_KeyPointsAGAST', node_F_VN_KeyPointsAGAST);
//F_VN_KeyPointsAGASTExp
//F_VN_KeyPointsAndDescriptorsAKAZE
//F_VN_KeyPointsAndDescriptorsAKAZEExp
//F_VN_KeyPointsAndDescriptorsBRISK
//F_VN_KeyPointsAndDescriptorsBRISKExp
//F_VN_KeyPointsAndDescriptorsKAZE
//F_VN_KeyPointsAndDescriptorsKAZEExp
//F_VN_KeyPointsAndDescriptorsORB
//F_VN_KeyPointsAndDescriptorsORBExp
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_KeyPointsFAST', node_F_VN_KeyPointsFAST);
//F_VN_KeyPointsFASTExp
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_KeyPointsGFTT', node_F_VN_KeyPointsGFTT);
//F_VN_KeyPointsGFTTExp
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_KeyPointsMSER', node_F_VN_KeyPointsMSER);
//F_VN_KeyPointsMSERExp
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_KeyPointsSB', node_F_VN_KeyPointsSB);
//F_VN_KeyPointsSBExp
//F_VN_MatchDescriptorsBF
//F_VN_MatchDescriptorsBFExp
//F_VN_MatchDescriptorsFlannLsh
//F_VN_MatchDescriptorsFlannLshExp
//F_VN_MatchDescriptorsKnnBF
//F_VN_MatchDescriptorsKnnBFExp
//F_VN_MatchDescriptorsKnnFlannLsh
//F_VN_MatchDescriptorsKnnFlannLshExp
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_RegionsMSER', node_F_VN_RegionsMSER);
NodeFactory.AddNodeAsPrototype('Vision/Keypoint Features/F_VN_RegionsMSERExp', node_F_VN_RegionsMSERExp);

// Machine Learning
//F_VN_CreateBoostClassifier
//F_VN_CreateBoostClassifierExp
//F_VN_CreateBoostClassifierExp2
//F_VN_CreateKmppModel
//F_VN_CreateKmppModelExp
//F_VN_CreateKnnModel
//F_VN_CreateLbgModel
//F_VN_CreateLbgModelExp
//F_VN_CreateLdaTransform
//F_VN_CreateLdaTransformViaComponentNum
//F_VN_CreateNbcModel
//F_VN_CreatePcaTransform
//F_VN_CreatePcaTransformViaComponentNum
//F_VN_CreatePcaTransformViaVariance
//F_VN_CreateRTreesModel
//F_VN_CreateRTreesModelExp
//F_VN_CreateRTreesModelExp2
//F_VN_CreateStaModel
//F_VN_CreateStaModelExp
//F_VN_CreateStaModelExp2
//F_VN_CreateSvmModel
//F_VN_CreateSvmModelExp
//F_VN_CreateSvmModelExp2
//F_VN_CreateSvmSgdClassifier
//F_VN_CreateSvmSgdClassifierExp
//F_VN_FeatureScaling
//F_VN_FeatureScalingExp
//F_VN_FeatureTransform
//F_VN_GetBatchClusters
//F_VN_GetBatchClustersExp
//F_VN_GetBatchNovelties
//F_VN_GetClusterCenter
//F_VN_GetClusterNum
//F_VN_GetFeatureScales
//F_VN_GetSampleCluster
//F_VN_GetSampleClusterExp
//F_VN_GetSampleNovelty
//F_VN_InverseFeatureScaling
//F_VN_InverseFeatureScaling_REAL
//F_VN_InverseFeatureScalingExp
//F_VN_InverseFeatureScalingExp_REAL
//F_VN_InverseFeatureTransform
//F_VN_PredictBatch
//F_VN_PredictBatchExp
//F_VN_PredictSampleClass
//F_VN_PredictSampleClassExp
//F_VN_PredictSampleScalar
//F_VN_PredictSampleScalarExp
//F_VN_PredictSampleVector
//F_VN_PredictSampleVectorExp
//F_VN_TrainBatch
//F_VN_TrainBatchClusters
//F_VN_TrainSample
//F_VN_TrainSampleClass
//F_VN_TrainSampleCluster
//F_VN_TrainSampleScalar
//F_VN_TrainSampleVector

// Measurement
//F_VN_AdjustSearchWindowOrientationToLinearEdge
//F_VN_ClosestPointsBF
//F_VN_LocateCircularArc
//F_VN_LocateCircularArcExp
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_LocateEdge', node_F_VN_LocateEdge);
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_LocateEdgeExp', node_F_VN_LocateEdgeExp);
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_LocateEdges', node_F_VN_LocateEdges);
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_LocateEdgesExp', node_F_VN_LocateEdgesExp);
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_LocateEllipse', node_F_VN_LocateEllipse);
//F_VN_LocateEllipseExp
NodeFactory.AddNodeAsPrototype('Vision/Measurement/F_VN_MeasureAngleBetweenEdges', node_F_VN_MeasureAngleBetweenEdges);
//F_VN_MeasureAngleBetweenEdgesExp
//F_VN_MeasureEdgeDistance
//F_VN_MeasureEdgeDistanceExp
//F_VN_MeasureMinEdgeDistance
//F_VN_MeasureMinEdgeDistanceExp

// Miscellaneous
//F_VN_CheckFunctionInitialization
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_ClipLineToBoundary', node_F_VN_ClipLineToBoundary);
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_ClipLineToBoundary_ITcVnImage', node_F_VN_ClipLineToBoundary_ITcVnImage);
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_ClipLineToBoundary_TcVnRectangle_DINT', node_F_VN_ClipLineToBoundary_TcVnRectangle_DINT);
//F_VN_ConvertITcUnknownToITcVnBitmapExport
//F_VN_ConvertITcUnknownToITcVnContainer
//F_VN_ConvertITcUnknownToITcVnImage
//F_VN_ConvertITcUnknownToITcVnMlModel
//F_VN_DeinitializeFunction
//F_VN_GetTimestamp
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_HuMomentInvariants', node_F_VN_HuMomentInvariants);
//F_VN_InitMatrixStruct
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_InvertMatrix3x3', node_F_VN_InvertMatrix3x3);
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_LineIntersectionPoint', node_F_VN_LineIntersectionPoint);
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_LineIntersectionPointAndAngle', node_F_VN_LineIntersectionPointAndAngle);
//NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_MultiplyMatrices', node_F_VN_MultiplyMatrices);
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_RotatedRectangleCorners', node_F_VN_RotatedRectangleCorners);
NodeFactory.AddNodeAsPrototype('Vision/Miscellaneous/F_VN_RotatedRectangleIntersection', node_F_VN_RotatedRectangleIntersection);
//F_VN_SetRngSeed
//F_VN_UpdateTimestamp

// OCR
//NodeFactory.AddNodeAsPrototype('Vision/OCR/F_VN_OCR', node_F_VN_OCR);
//NodeFactory.AddNodeAsPrototype('Vision/OCR/F_VN_OCRExp', node_F_VN_OCRExp);

// Texture Analysis
//NodeFactory.AddNodeAsPrototype('Vision/Texture Analysis/F_VN_Granulometry', node_F_VN_Granulometry);
//NodeFactory.AddNodeAsPrototype('Vision/Texture Analysis/F_VN_HaralickFeatures', node_F_VN_HaralickFeatures);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>