<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.15">
  <POU Name="VisionPack" Id="{fc907027-5c97-0887-0286-571c1554215c}" SpecialFunc="None">
    <Declaration><![CDATA[{attribute 'linkalways'} 
{attribute 'no_explicit_call' := 'This FB is a CLASS and must be accessed using methods or properties'}
{attribute 'enable_dynamic_creation'}
FUNCTION_BLOCK VisionPack IMPLEMENTS I_GraphPack
VAR
	visionDatatypePack : VisionDatatypePack;
	visionNodePack : VisionNodePack;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Register" Id="{79298ce9-536a-05e6-1fc1-f3b1b3687b20}">
      <Declaration><![CDATA[METHOD Register
VAR_INPUT
	Datatypes : I_Datatypes;
	NodeFactory : I_NodeFactory;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[visionDatatypePack.RegisterWithDatatypes(Datatypes);
visionNodePack.RegisterWithNodeFactory(NodeFactory);]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>