<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.13">
  <POU Name="VisionNode" Id="{f924a3b9-a7ea-048f-393e-cff5c17d2882}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK ABSTRACT VisionNode EXTENDS Node IMPLEMENTS I_PreCheckedNode
VAR
	preExecutionCheckExtension : PreExecutionCheckExtension('precheck', THIS^);
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="PreExecutionCheck" Id="{1cc0fb1a-9fc7-05d0-0dda-466734a3a96c}">
      <Declaration><![CDATA[METHOD PUBLIC ABSTRACT PreExecutionCheck
VAR_INPUT
	Check : I_PreExecutionChecks;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>